Adjustments to pre-requisite checks

diff --git a/billing/bin/billing-create-billingsubscriptions-stack b/billing/bin/billing-create-billingsubscriptions-stack
--- a/billing/bin/billing-create-billingsubscriptions-stack
+++ b/billing/bin/billing-create-billingsubscriptions-stack
@@ -2,9 +2,6 @@
 #
 # This script creates the BillingSubscriptions Stack in the Billing Account.
 #
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
-#
 
 #  1. Initalize Environment
 
@@ -18,12 +15,13 @@ run_default=10
 pause_default=2
 next_default=5
 create_default=15
-create_attempts=20
+create_attempts=40
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+monitor=0
+owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=Billing
@@ -35,14 +33,15 @@ user=${AWS_USER_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
-    echo "                  [-O owner] [-C company ] [-S system]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m]"
+    echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment]"
     echo "                  [-a account] [-u user]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
+    echo "  -m              monitor"
     echo "  -O owner        Owner Email (default: $owner)"
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
@@ -131,12 +130,13 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvO:C:S:E:a:u:? arg; do
+while getopts isfvmO:C:S:E:a:u:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
+    m)  monitor=1;;
     O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
@@ -149,6 +149,7 @@ while getopts IsfvO:C:S:E:a:u:? arg; do
 done
 
 shift $(($OPTIND - 1))
+[ $monitor = 0 ] && verbose=0
 
 
 #  4. Validate environment
@@ -163,18 +164,42 @@ if [ -z $company ]; then
     echo "-C company missing!"
     echo "Could not automatically determine company, and it was not specified as a parameter"
     exit 12
+else
+    case $company in
+      Travel)
+        ;;
+      *)
+        echo "-C $company invalid! Must be Travel"
+        exit 13;;
+    esac
 fi
 
 if [ -z $system ]; then
     echo "-S system missing!"
     echo "Could not automatically determine system, and it was not specified as a parameter"
     exit 14
+else
+    case $system in
+      IROPS)
+        ;;
+      *)
+        echo "-S $system invalid! Must be IROPS"
+        exit 15;;
+    esac
 fi
 
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
+    exit 20
+else
+    case $environment in
+      Billing)
+        ;;
+      *)
+        echo "-E $environment invalid! Must be Billing"
+        exit 21;;
+    esac
 fi
 
 s3_domain=s3.amazonaws.com
@@ -196,20 +221,27 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
+    exit 58
 fi
+
+echo -n "Confirming Stack pre-requisites "
+
+if ! aws cloudformation describe-stacks --stack-name BillingTopics \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo
+    echo "Stack dependency missing - BillingTopics Stack does not exist!"
+    exit 60
+else
+    echo -n "."
+fi
+echo " Done"
+sleep 1
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
 template_folder=billing
 
 if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
     unset templates_bucket
-fi
-
-if ! aws cloudformation describe-stacks --stack-name BillingTopics \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo "Stack dependency missing - BillingTopics Stack does not exist!"
-    exit 70
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -362,59 +394,61 @@ EOS
 run_statement2=$(echo "$statement2" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement2="${statement2//\\$'\n'} 2> /dev/null"
 
-clear
-echo
-echo "============================================================"
-echo
-echo "$(printf '%2d' $step). Monitor Stack creation"
-echo
-echo "============================================================"
-echo
-echo "Commands:"
-echo
-echo "$statement"
-echo
-echo "$statement2"
-
-if [ "$(aws cloudformation describe-stacks --stack-name BillingSubscriptions \
-                                           --query 'Stacks[].StackStatus' \
-                                           --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
+if [ $monitor = 1 ]; then
+    clear
     echo
-    tput rev
-    echo "Already Complete!"
-    tput sgr0
+    echo "============================================================"
+    echo
+    echo "$(printf '%2d' $step). Monitor Stack creation"
+    echo
+    echo "============================================================"
+    echo
+    echo "Commands:"
+    echo
+    echo "$statement"
+    echo
+    echo "$statement2"
 
-    next 50
+    if [ "$(aws cloudformation describe-stacks --stack-name BillingSubscriptions \
+                                               --query 'Stacks[].StackStatus' \
+                                               --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
+    echo
+        tput rev
+        echo "Already Complete!"
+        tput sgr0
 
-else
-    run 50
+        next 50
 
-    if [ $choice = y ]; then
-        echo
-        echo "$run_statement"
-        eval "$eval_statement"
+    else
+        run 50
 
-        attempt=0
-        seconds=$create_default
-        while ((attempt++ <= create_attempts)); do
+        if [ $choice = y ]; then
             echo
-            echo "$run_statement2"
-            eval "$eval_statement2"
+            echo "$run_statement"
+            eval "$eval_statement"
 
-            status=$(aws cloudformation describe-stacks --stack-name BillingSubscriptions \
-                                                        --query 'Stacks[].StackStatus' \
-                                                        --profile $profile --region $region --output text 2> /dev/null)
-            if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
-                break
-            else
+            attempt=0
+            seconds=$create_default
+            while ((attempt++ <= create_attempts)); do
                 echo
-                echo -n "Not finished ($status). Waiting $seconds seconds..."
-                sleep $seconds
-                echo " Done"
-            fi
-        done
+                echo "$run_statement2"
+                eval "$eval_statement2"
 
-        next
+                status=$(aws cloudformation describe-stacks --stack-name BillingSubscriptions \
+                                                            --query 'Stacks[].StackStatus' \
+                                                            --profile $profile --region $region --output text 2> /dev/null)
+                if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
+                    break
+                else
+                    echo
+                    echo -n "Not finished ($status). Waiting $seconds seconds..."
+                    sleep $seconds
+                    echo " Done"
+                fi
+            done
+
+            next
+        fi
     fi
 fi
 
