moved Billing to correct filesystem location

diff --git a/billing/bin/billing-update-billingsubscriptions-stack b/billing/bin/billing-update-billingsubscriptions-stack
--- a/billing/bin/billing-update-billingsubscriptions-stack
+++ b/billing/bin/billing-update-billingsubscriptions-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script creates the BillingAlarms Stack in the Core Account.
+# This script updates the BillingSubscriptions Stack in the Billing Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -17,8 +17,8 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-create_default=15
-create_attempts=20
+update_default=15
+update_attempts=20
 
 interactive=1
 speed=100
@@ -26,13 +26,13 @@ verbose=0
 owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
-environment=${CORE_NAME:-Core}
+environment=Billing
 region=us-east-1 # This must currently run only in us-east-1
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
 
 templatesbucket=${AWS_TEMPLATES_BUCKET:-templates-$account}
-templatespath=/core
+templatespath=/billing
 
 
 #  2. Define functions
@@ -41,7 +41,7 @@ usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment]"
-    echo "                  [-a account ] [-u user]"
+    echo "                  [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -206,9 +206,9 @@ if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region
     unset templatesbucket
 fi
 
-if ! aws cloudformation describe-stacks --stack-name BillingTopics \
+if ! aws cloudformation describe-stacks --stack-name BillingSubscriptions \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Stack dependency missing - BillingTopics Stack does not exist!"
+    echo "Unable to update - BillingSubscriptions Stack does not exist!"
     exit 70
 fi
 
@@ -260,7 +260,7 @@ fi
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
             s3://$templatesbucket$templatespath \\
-            --exclude '*' --include 'Core-BillingAlarms.json' --include 'Core-BillingAlarms-StackPolicy.json' \\
+            --exclude '*' --include 'Billing-BillingSubscriptions.json' --include 'Billing-BillingSubscriptions-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -291,14 +291,14 @@ fi
 
 ((++step))
 if [ ! -z $templatesbucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingAlarms.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingAlarms-StackPolicy.json"
+    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Billing-BillingSubscriptions.json"
+    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Billing-BillingSubscriptions-StackPolicy.json"
 else
-    template_parameter="--template-body file://$templatesdir/Core-BillingAlarms.json"
-    stack_policy_parameter="--stack-policy-body file://$templatesdir/Core-BillingAlarms-StackPolicy.json"
+    template_parameter="--template-body file://$templatesdir/Billing-BillingSubscriptions.json"
+    stack_policy_parameter="--stack-policy-body file://$templatesdir/Billing-BillingSubscriptions-StackPolicy.json"
 fi
 read -r -d '' statement << EOS
-aws cloudformation create-stack --stack-name BillingAlarms \\
+aws cloudformation update-stack --stack-name BillingSubscriptions \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
                                 --parameters ParameterKey=BillingTopicsStackName,ParameterValue=BillingTopics \\
@@ -315,7 +315,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Create the Stack"
+echo "$(printf '%2d' $step). Update the Stack"
 echo
 echo "============================================================"
 echo
@@ -323,31 +323,20 @@ echo "Commands:"
 echo
 echo "$statement"
 
-if aws cloudformation describe-stacks --stack-name BillingAlarms \
-                                      --profile $profile --region $region --output text &> /dev/null; then
+run
+
+if [ $choice = y ]; then
     echo
-    tput rev
-    echo "Already Created!"
-    tput sgr0
+    echo "$run_statement"
+    eval "$eval_statement"
 
-    next 50
-
-else
-    run
-
-    if [ $choice = y ]; then
-        echo
-        echo "$run_statement"
-        eval "$eval_statement"
-
-        next
-    fi
+    next
 fi
 
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name BillingAlarms \\
+aws cloudformation describe-stacks --stack-name BillingSubscriptions \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -355,7 +344,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name BillingAlarms --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name BillingSubscriptions --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -366,7 +355,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Monitor Stack creation"
+echo "$(printf '%2d' $step). Monitor Stack update"
 echo
 echo "============================================================"
 echo
@@ -376,9 +365,9 @@ echo "$statement"
 echo
 echo "$statement2"
 
-if [ "$(aws cloudformation describe-stacks --stack-name BillingAlarms \
+if [ "$(aws cloudformation describe-stacks --stack-name BillingSubscriptions \
                                            --query 'Stacks[].StackStatus' \
-                                           --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
+                                           --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
     echo
     tput rev
     echo "Already Complete!"
@@ -395,16 +384,16 @@ else
         eval "$eval_statement"
 
         attempt=0
-        seconds=$create_default
-        while ((attempt++ <= create_attempts)); do
+        seconds=$update_default
+        while ((attempt++ <= update_attempts)); do
             echo
             echo "$run_statement2"
             eval "$eval_statement2"
 
-            status=$(aws cloudformation describe-stacks --stack-name BillingAlarms \
+            status=$(aws cloudformation describe-stacks --stack-name BillingSubscriptions \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
-            if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
+            if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
                 break
             else
                 echo
@@ -454,7 +443,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stack-resources --stack-name BillingAlarms \\
+aws cloudformation describe-stack-resources --stack-name BillingSubscriptions \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
                                             --profile $profile --region $region --output table
 EOS
