Update remaining code with recent improvements in applications section (#9)
* Update driver scripts and templates with recent fixes for consistency first implemented in the applications section

* Update email addresses to @dxc.com

* Add Murali and Vijay to Topics

* Update/create S3-based versions of AMI functions to match in-line versions

* improvements to detect modified Lambda functions stored in S3

* Fix some sequence script ordering and environment issues

* Remove old VPC-PeeringConnection example

diff --git a/bootstrap/bin/bootstrap-create-linuxbastion-stack b/bootstrap/bin/bootstrap-create-linuxbastion-stack
--- a/bootstrap/bin/bootstrap-create-linuxbastion-stack
+++ b/bootstrap/bin/bootstrap-create-linuxbastion-stack
@@ -29,30 +29,27 @@ create_attempts=40
 interactive=1
 speed=100
 verbose=0
-monitor=1
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+monitor=0
+owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=Bootstrap # This exists outside Environments
-environment_size=${ENVIRONMENT_SIZE:-micro}
+environment_type=${ENVIRONMENT_TYPE:-micro}
 utility=${UTILITY_NAME:-LinuxBastion}
 home_snapshot=
-key=${AWS_KEY_NAME:-bootstrap}
-public_network=${PUBLIC_NETWORK:-0.0.0.0/0}
-public_network1=${PUBLIC_NETWORK1:-}
-public_network2=${PUBLIC_NETWORK2:-}
-public_network3=${PUBLIC_NETWORK3:-}
+public_user_network=${PUBLIC_USER_NETWORK:-0.0.0.0/0}
+public_user_network1=${PUBLIC_USER_NETWORK1:-}
+public_user_network2=${PUBLIC_USER_NETWORK2:-}
 region=us-east-1 # This should run only in us-east-1
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=bootstrapadministrator
+key=${AWS_KEY_NAME:-bootstrap}
 
 use_static_public_address=true
 use_static_home_volume=true
-use_log_monitoring=true
 log_retention=7
 log_alarm_email=mcrawford@hpe.com
 use_local_users=true
-use_schedule=false
 on_schedule="0 11 * * 1-5" # 11:00 UTC = 3:00 AM PST = 6:00 AM EST, Mon-Fri
 off_schedule="0 4 * * *" # 4:00 UTC = 8:00 PM PST = 11:00 PM EST, Mon-Fri
 
@@ -60,28 +57,27 @@ off_schedule="0 4 * * *" # 4:00 UTC = 8:00 PM PST = 11:00 PM EST, Mon-Fri
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-M]"
-    echo "                  [-O owner] [-C company ] [-S system]"
-    echo "                  [-Z size]"
+    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m]"
+    echo "                  [-O owner] [-C company] [-S system]"
+    echo "                  [-T type]"
     echo "                  [-U utility] [-h snapshot]"
-    echo "                  [-k key]"
     echo "                  [-p network]"
-    echo "                  [-a account] [-u user]"
+    echo "                  [-a account] [-u user] [-k key]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
-    echo "  -M              do not monitor stack creation"
+    echo "  -m              monitor stack creation"
     echo "  -O owner        Owner Email (default: $owner)"
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
-    echo "  -Z size         Environment Size (default: $environment_size)"
+    echo "  -T type         Environment Type (default: $environment_type)"
     echo "  -U utility      Utility Name (default: $utility)"
     echo "  -h snapshot     Home Snapshot (default: $home_snapshot)"
-    echo "  -k key          Key (default: $key)"
-    echo "  -p network      Public Network (default: $public_network)"
+    echo "  -p network      Public User Network (default: $public_user_network)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
+    echo "  -k key          Key (default: $key)"
 }
 
 run() {
@@ -163,28 +159,27 @@ next() {
 
 
 #  3. Parse command line options
-#     - Note, using options 1-9 as hidden options to set additional network ranges
+#     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvMO:C:S:Z:U:h:k:p:4:5:6:a:u:? arg; do
+while getopts IsfvmO:C:S:T:U:h:p:1:2:a:u:k:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
-    M)  monitor=0;;
+    m)  monitor=1;;
     O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
-    Z)  environment_size="$OPTARG";;
+    T)  environment_type="$OPTARG";;
     U)  utility="$OPTARG";;
     h)  home_snapshot="$OPTARG";;
-    k)  key="$OPTARG";;
-    p)  public_network="$OPTARG";;
-    4)  public_network1="$OPTARG";;
-    5)  public_network2="$OPTARG";;
-    6)  public_network3="$OPTARG";;
+    p)  public_user_network="$OPTARG";;
+    1)  public_user_network1="$OPTARG";;
+    2)  public_user_network2="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
+    k)  key="$OPTARG";;
     ?)  usage
         exit 1;;
     esac
@@ -206,36 +201,62 @@ if [ -z $company ]; then
     echo "-C company missing!"
     echo "Could not automatically determine company, and it was not specified as a parameter"
     exit 12
+else
+    case $company in
+      Travel)
+        ;;
+      *)
+        echo "-C $company invalid! Must be Travel"
+        exit 13;;
+    esac
 fi
 
 if [ -z $system ]; then
     echo "-S system missing!"
     echo "Could not automatically determine system, and it was not specified as a parameter"
     exit 14
+else
+    case $system in
+      IROPS)
+        ;;
+      *)
+        echo "-S $system invalid! Must be IROPS"
+        exit 15;;
+    esac
 fi
 
-if [ -z $environment_size ]; then
-    echo "-Z size missing!"
-    echo "Could not automatically determine size, and it was not specified as a parameter"
-    exit 18
+if [ -z $environment_type ]; then
+    echo "-T type missing!"
+    echo "Could not automatically determine environment type, and it was not specified as a parameter"
+    exit 22
+else
+    case $environment_type in
+      micro|small|medium|large|xlarge)
+        ;;
+      *)
+        echo "-T $environment_type invalid! Must be micro, small, medium, large or xlarge"
+        exit 23;;
+    esac
 fi
 
 if [ -z $utility ]; then
     echo "-U utility missing!"
     echo "Could not automatically determine utility, and it was not specified as a parameter"
-    exit 20
-fi
-
-if [ -z $key ]; then
-    echo "-K key missing!"
-    echo "Could not automatically determine key, and it was not specified as a parameter"
     exit 30
+else
+    case $utility in
+      LinuxBastion*)
+        ;;
+      *)
+        echo "-U $utility invalid! Must be LinuxBastion*"
+        exit 31;;
+    esac
 fi
 
-if [ -z $public_network ]; then
+if [ -z $public_user_network ]; then
     echo "-p network missing!"
-    echo "Could not automatically determine public network, and it was not specified as a parameter"
-    exit 34
+    echo "Could not automatically determine public user network, and it was not specified as a parameter"
+    exit 40
 fi
 
 s3_domain=s3.amazonaws.com
@@ -252,12 +273,18 @@ if [ -z $user ]; then
     exit 54
 fi
 
+if [ -z $key ]; then
+    echo "-k key missing!"
+    echo "Could not automatically determine key, and it was not specified as a parameter"
+    exit 56
+fi
+
 profile=$account-$user
 
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
+    exit 58
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -314,22 +341,19 @@ aws cloudformation create-stack --stack-name $environment-$utility \\
                                 --parameters ParameterKey=KeyName,ParameterValue=$key \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
-                                             ParameterKey=EnvironmentSize,ParameterValue=$environment_size \\
+                                             ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
                                              ParameterKey=UtilityName,ParameterValue=$utility \\
                                              ParameterKey=UseStaticPublicAddress,ParameterValue=$use_static_public_address \\
                                              ParameterKey=UseStaticHomeVolume,ParameterValue=$use_static_home_volume \\
                                              ParameterKey=HomeSnapshot,ParameterValue=$home_snapshot \\
-                                             ParameterKey=UseLogMonitoring,ParameterValue=$use_log_monitoring \\
+                                             ParameterKey=UseLocalUsers,ParameterValue=$use_local_users \\
                                              ParameterKey=LogRetention,ParameterValue=$log_retention \\
                                              ParameterKey=LogAlarmEmail,ParameterValue=$log_alarm_email \\
-                                             ParameterKey=UseLocalUsers,ParameterValue=$use_local_users \\
-                                             ParameterKey=UseSchedule,ParameterValue=$use_schedule \\
                                              ParameterKey=OnSchedule,ParameterValue="$on_schedule" \\
                                              ParameterKey=OffSchedule,ParameterValue="$off_schedule" \\
-                                             ParameterKey=PublicNetwork,ParameterValue=$public_network \\
-                                             ParameterKey=PublicNetwork1,ParameterValue=$public_network1 \\
-                                             ParameterKey=PublicNetwork2,ParameterValue=$public_network2 \\
-                                             ParameterKey=PublicNetwork3,ParameterValue=$public_network3 \\
+                                             ParameterKey=PublicUserNetwork,ParameterValue=$public_user_network \\
+                                             ParameterKey=PublicUserNetwork1,ParameterValue=$public_user_network1 \\
+                                             ParameterKey=PublicUserNetwork2,ParameterValue=$public_user_network2 \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
diff --git a/bootstrap/bin/bootstrap-delete-linuxbastion-stack b/bootstrap/bin/bootstrap-delete-linuxbastion-stack
--- a/bootstrap/bin/bootstrap-delete-linuxbastion-stack
+++ b/bootstrap/bin/bootstrap-delete-linuxbastion-stack
@@ -24,30 +24,30 @@ run_default=10
 pause_default=2
 next_default=5
 delete_default=15
-delete_attempts=20
+delete_attempts=40
 
 interactive=1
 speed=100
 verbose=0
-monitor=1
+monitor=0
 environment=Bootstrap # This exists outside Environments
 utility=${UTILITY_NAME:-LinuxBastion}
 region=us-east-1 # This should run only in us-east-1
 account=${AWS_ACCOUNT_ALIAS:-irops}
-user=${AWS_USER_NAME:-bootstrapadministrator}
+user=bootstrapadministrator
 
 
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-M]"
+    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m]"
     echo "                  [-U utility]"
     echo "                  [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
-    echo "  -M              do not monitor stack deletion"
+    echo "  -m              monitor stack deletion"
     echo "  -U utility      Utility Name (default: $utility)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -133,13 +133,13 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvMU:a:u:? arg; do
+while getopts IsfvmU:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
-    M)  monitor=0;;
+    m)  monitor=1;;
     U)  utility="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -157,7 +157,15 @@ shift $(($OPTIND - 1))
 if [ -z $utility ]; then
     echo "-U utility missing!"
     echo "Could not automatically determine utility, and it was not specified as a parameter"
-    exit 20
+    exit 30
+else
+    case $utility in
+      LinuxBastion)
+        ;;
+      *)
+        echo "-U $utility invalid! Must be LinuxBastion"
+        exit 31;;
+    esac
 fi
 
 s3_domain=s3.amazonaws.com
@@ -179,7 +187,7 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
+    exit 58
 fi
 
 # Prevent certain environment variables from breaking commands
diff --git a/common/bin/common-create-customergateway-stack b/common/bin/common-create-customergateway-stack
--- a/common/bin/common-create-customergateway-stack
+++ b/common/bin/common-create-customergateway-stack
@@ -18,12 +18,12 @@ run_default=10
 pause_default=2
 next_default=5
 create_default=15
-create_attempts=20
+create_attempts=40
 
 interactive=1
 speed=100
 verbose=0
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${CORE_NAME:-Core}
@@ -42,7 +42,7 @@ usage () {
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment]"
     echo "                  [-G gateway] [-b asn] [-i address]"
-    echo "                  [-r region ] [-a account] [-u user]"
+    echo "                  [-r region] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -175,36 +175,60 @@ if [ -z $company ]; then
     echo "-C company missing!"
     echo "Could not automatically determine company, and it was not specified as a parameter"
     exit 12
+else
+    case $company in
+      Travel)
+        ;;
+      *)
+        echo "-C $company invalid! Must be Travel"
+        exit 13;;
+    esac
 fi
 
 if [ -z $system ]; then
     echo "-S system missing!"
     echo "Could not automatically determine system, and it was not specified as a parameter"
     exit 14
+else
+    case $system in
+      IROPS)
+        ;;
+      *)
+        echo "-S $system invalid! Must be IROPS"
+        exit 15;;
+    esac
 fi
 
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
+    exit 20
+else
+    case $environment in
+      Core)
+        ;;
+      *)
+        echo "-E $environment invalid! Must be Core"
+        exit 21;;
+    esac
 fi
 
 if [ -z $gateway ]; then
     echo "-G gateway missing!"
     echo "Could not automatically determine gateway, and it was not specified as a parameter"
-    exit 18
+    exit 30
 fi
 
 if [ -z $gateway_asn ]; then
     echo "-b asn missing!"
     echo "Could not automatically determine gateway BGP ASN, and it was not specified as a parameter"
-    exit 20
+    exit 32
 fi
 
 if [ -z $gateway_address ]; then
     echo "-i address missing!"
     echo "Could not automatically determine gateway address, and it was not specified as a parameter"
-    exit 22
+    exit 34
 fi
 
 if [ -z $region ]; then
@@ -215,9 +239,9 @@ else
     case $region in
       us-east-1)
         s3_domain=s3.amazonaws.com;;
-      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+      us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
         s3_domain=s3-$region.amazonaws.com;;
-    *)
+      *)
         echo "-r $region invalid: Please specify a valid region"
         exit 51;;
     esac
@@ -240,11 +264,11 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
+    exit 58
 fi
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-templates_folder=common
+template_folder=common
 
 if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
     unset templates_bucket
@@ -297,7 +321,7 @@ fi
 ((++step))
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
-            s3://$templates_bucket/$templates_folder \\
+            s3://$templates_bucket/$template_folder \\
             --exclude '*' --include 'Common-CustomerGateway.json' --include 'Common-CustomerGateway-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
@@ -329,8 +353,8 @@ fi
 
 ((++step))
 if [ ! -z $templates_bucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templates_bucket/$templates_folder/Common-CustomerGateway.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$templates_folder/Common-CustomerGateway-StackPolicy.json"
+    template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Common-CustomerGateway.json"
+    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Common-CustomerGateway-StackPolicy.json"
 else
     template_parameter="--template-body file://$templatesdir/Common-CustomerGateway.json"
     stack_policy_parameter="--stack-policy-body file://$templatesdir/Common-CustomerGateway-StackPolicy.json"
diff --git a/common/bin/common-delete-vpnconnection-stack b/common/bin/common-delete-vpnconnection-stack
--- a/common/bin/common-delete-vpnconnection-stack
+++ b/common/bin/common-delete-vpnconnection-stack
@@ -18,7 +18,7 @@ run_default=10
 pause_default=2
 next_default=5
 delete_default=15
-delete_attempts=20
+delete_attempts=40
 
 interactive=1
 speed=100
@@ -36,7 +36,7 @@ usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
     echo "                  [-E environment]"
     echo "                  [-G gateway]"
-    echo "                  [-r region ] [-a account] [-u user]"
+    echo "                  [-r region] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -152,13 +152,31 @@ shift $(($OPTIND - 1))
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
+    exit 20
+else
+    case $environment in
+      Production)
+        ;;
+      Staging)
+        ;;
+      Testing)
+        ;;
+      Development)
+        ;;
+      Core)
+        ;;
+      Build)
+        ;;
+      *)
+        echo "-E $environment invalid! Must be Production, Staging, Testing, Development, Core or Build"
+        exit 21;;
+    esac
 fi
 
 if [ -z $gateway ]; then
     echo "-G gateway missing!"
     echo "Could not automatically determine gateway, and it was not specified as a parameter"
-    exit 18
+    exit 30
 fi
 
 if [ -z $region ]; then
@@ -169,9 +187,9 @@ else
     case $region in
       us-east-1)
         s3_domain=s3.amazonaws.com;;
-      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+      us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
         s3_domain=s3-$region.amazonaws.com;;
-    *)
+      *)
         echo "-r $region invalid: Please specify a valid region"
         exit 51;;
     esac
@@ -194,13 +212,13 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
+    exit 58
 fi
 
 if ! aws cloudformation describe-stacks --stack-name $environment-${gateway}VPNConnection \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - $environment-${gateway}VPNConnection Stack does not exist!"
-    exit 70
+    echo "Unable to delete - $environment-${gateway}VPNConnection Stack does not exist!"
+    exit 80
 fi
 
 # Prevent certain environment variables from breaking commands
diff --git a/core/bin/core-create-standardcidrfunctions-stack b/core/bin/core-create-standardcidrfunctions-stack
--- a/core/bin/core-create-standardcidrfunctions-stack
+++ b/core/bin/core-create-standardcidrfunctions-stack
@@ -10,6 +10,7 @@
 
 bindir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 templatesdir=${bindir%/*}/templates
+functionsdir=${bindir%/*}/functions
 tmpdir=/var/tmp
 
 step=0
@@ -18,12 +19,12 @@ run_default=10
 pause_default=2
 next_default=5
 create_default=15
-create_attempts=20
+create_attempts=40
 
 interactive=1
 speed=100
 verbose=0
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${CORE_NAME:-Core}
@@ -38,7 +39,7 @@ usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment]"
-    echo "                  [-r region ] [-a account] [-u user]"
+    echo "                  [-r region] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -165,18 +166,42 @@ if [ -z $company ]; then
     echo "-C company missing!"
     echo "Could not automatically determine company, and it was not specified as a parameter"
     exit 12
+else
+    case $company in
+      Travel)
+        ;;
+      *)
+        echo "-C $company invalid! Must be Travel"
+        exit 13;;
+    esac
 fi
 
 if [ -z $system ]; then
     echo "-S system missing!"
     echo "Could not automatically determine system, and it was not specified as a parameter"
     exit 14
+else
+    case $system in
+      IROPS)
+        ;;
+      *)
+        echo "-S $system invalid! Must be IROPS"
+        exit 15;;
+    esac
 fi
 
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
+    exit 20
+else
+    case $environment in
+      Core)
+        ;;
+      *)
+        echo "-E $environment invalid! Must be Core"
+        exit 21;;
+    esac
 fi
 
 if [ -z $region ]; then
@@ -187,9 +212,9 @@ else
     case $region in
       us-east-1)
         s3_domain=s3.amazonaws.com;;
-      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+      us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
         s3_domain=s3-$region.amazonaws.com;;
-    *)
+      *)
         echo "-r $region invalid: Please specify a valid region"
         exit 51;;
     esac
@@ -212,15 +237,23 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
+    exit 58
+fi
+
+if ! aws cloudformation describe-stacks --stack-name StandardTopics \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo "Stack dependency missing - StandardTopics Stack does not exist!"
     exit 60
 fi
 
-templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-templates_folder=core
-
-if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
-    unset templates_bucket
+if ! aws cloudformation describe-stacks --stack-name StandardBuckets \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo "Stack dependency missing - StandardBuckets Stack does not exist!"
+    exit 61
 fi
+
+templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
+template_folder=core
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -269,44 +302,37 @@ fi
 ((++step))
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
-            s3://$templates_bucket/$templates_folder \\
+            s3://$templates_bucket/$template_folder \\
             --exclude '*' --include 'Core-StandardCIDRFunctions.json' --include 'Core-StandardCIDRFunctions-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'}"
 
-if [ ! -z $templates_bucket ]; then
-    clear
-    echo
-    echo "============================================================"
-    echo
-    echo "$(printf '%2d' $step). Sync Template and Policy to ($templates_bucket) Bucket"
-    echo
-    echo "============================================================"
-    echo
-    echo "Commands:"
-    echo
-    echo "$statement"
+clear
+echo
+echo "============================================================"
+echo
+echo "$(printf '%2d' $step). Sync Template and Policy to ($templates_bucket) Bucket"
+echo
+echo "============================================================"
+echo
+echo "Commands:"
+echo
+echo "$statement"
 
-    next 50
+next 50
 
-    echo
-    echo "$run_statement"
-    eval "$eval_statement"
+echo
+echo "$run_statement"
+eval "$eval_statement"
 
-    next 50
-fi
+next 50
 
 
 ((++step))
-if [ ! -z $templates_bucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templates_bucket/$templates_folder/Core-StandardCIDRFunctions.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$templates_folder/Core-StandardCIDRFunctions-StackPolicy.json"
-else
-    template_parameter="--template-body file://$templatesdir/Core-StandardCIDRFunctions.json"
-    stack_policy_parameter="--stack-policy-body file://$templatesdir/Core-StandardCIDRFunctions-StackPolicy.json"
-fi
+template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Core-StandardCIDRFunctions.json"
+stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Core-StandardCIDRFunctions-StackPolicy.json"
 read -r -d '' statement << EOS
 aws cloudformation create-stack --stack-name StandardCIDRFunctions \\
                                 $template_parameter \\
diff --git a/core/bin/core-update-customidentifierfunctions-stack b/core/bin/core-update-customidentifierfunctions-stack
--- a/core/bin/core-update-customidentifierfunctions-stack
+++ b/core/bin/core-update-customidentifierfunctions-stack
@@ -19,13 +19,13 @@ run_default=10
 pause_default=2
 next_default=5
 update_default=15
-update_attempts=20
+update_attempts=40
 
 interactive=1
 speed=100
 verbose=0
 override=0
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${CORE_NAME:-Core}
@@ -40,7 +40,7 @@ usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o]"
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment]"
-    echo "                  [-r region ] [-a account] [-u user]"
+    echo "                  [-r region] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -169,18 +169,42 @@ if [ -z $company ]; then
     echo "-C company missing!"
     echo "Could not automatically determine company, and it was not specified as a parameter"
     exit 12
+else
+    case $company in
+      Travel)
+        ;;
+      *)
+        echo "-C $company invalid! Must be Travel"
+        exit 13;;
+    esac
 fi
 
 if [ -z $system ]; then
     echo "-S system missing!"
     echo "Could not automatically determine system, and it was not specified as a parameter"
     exit 14
+else
+    case $system in
+      IROPS)
+        ;;
+      *)
+        echo "-S $system invalid! Must be IROPS"
+        exit 15;;
+    esac
 fi
 
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
+    exit 20
+else
+    case $environment in
+      Core)
+        ;;
+      *)
+        echo "-E $environment invalid! Must be Core"
+        exit 21;;
+    esac
 fi
 
 if [ -z $region ]; then
@@ -191,9 +215,9 @@ else
     case $region in
       us-east-1)
         s3_domain=s3.amazonaws.com;;
-      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+      us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
         s3_domain=s3-$region.amazonaws.com;;
-    *)
+      *)
         echo "-r $region invalid: Please specify a valid region"
         exit 51;;
     esac
@@ -216,32 +240,22 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
-fi
-
-templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-template_folder=core
-
-if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
-    echo "$templates_bucket S3 bucket does not exist!"
-    exit 62
-fi
-
-functions_bucket=${AWS_FUNCTIONS_BUCKET:-functions-$region-$account}
-function_folder=identifier
-gethostname_function_object=GetHostName.zip
-getdomainname_function_object=GetDomainName.zip
-
-if ! aws s3api head-bucket --bucket $functions_bucket --profile $profile --region $region 2> /dev/null; then
-    echo "$functions_bucket S3 bucket does not exist!"
-    exit 64
+    exit 58
 fi
 
 if ! aws cloudformation describe-stacks --stack-name CustomIdentifierFunctions \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo "Unable to update - CustomIdentifierFunctions Stack does not exist!"
-    exit 70
+    exit 80
 fi
+
+templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
+template_folder=core
+
+functions_bucket=${AWS_FUNCTIONS_BUCKET:-functions-$region-$account}
+function_folder=identifier
+gethostname_function_object=GetHostName.zip
+getdomainname_function_object=GetDomainName.zip
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -368,6 +382,7 @@ aws s3 sync $functionsdir \\
             --exclude '*' \\
             --include '$gethostname_function_object' \\
             --include '$getdomainname_function_object' \\
+            --size-only \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -398,6 +413,51 @@ next 50
 
 
 ((++step))
+read -r -d '' statement << EOS
+gethostname_function_object_version=\$(aws s3api list-object-versions --bucket $functions_bucket \\
+                                                                     --prefix $function_folder/$gethostname_function_object \\
+                                                                     --query 'Versions[0].VersionId' \\
+                                                                     --profile $profile --region $region --output text)
+EOS
+run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
+eval_statement="${statement//\\$'\n'}"
+
+read -r -d '' statement2 << EOS
+getdomainname_function_object_version=\$(aws s3api list-object-versions --bucket $functions_bucket \\
+                                                                       --prefix $function_folder/$getdomainname_function_object \\
+                                                                       --query 'Versions[0].VersionId' \\
+                                                                       --profile $profile --region $region --output text)
+EOS
+run_statement2=$(echo "$statement2" | sed -e '1s/^/# /;2,$ s/^/> /')
+eval_statement2="${statement2//\\$'\n'}"
+
+clear
+echo
+echo "============================================================"
+echo
+echo "$(printf '%2d' $step). Obtain ZipFile Versions"
+echo
+echo "============================================================"
+echo
+echo "Commands:"
+echo
+echo "$statement"
+echo
+echo "$statement2"
+
+next 50
+
+echo
+echo "$run_statement"
+eval "$eval_statement"
+echo
+echo "$run_statement2"
+eval "$eval_statement2"
+
+next 50
+
+
+((++step))
 template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Core-CustomIdentifierFunctions.json"
 stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Core-CustomIdentifierFunctions-StackPolicy.json"
 if [ $override = 1 ]; then
@@ -410,7 +470,9 @@ aws cloudformation update-stack --stack-name CustomIdentifierFunctions \\
                                 --parameters ParameterKey=StandardBucketsStackName,ParameterValue=StandardBuckets \\
                                              ParameterKey=FunctionFolder,ParameterValue=$function_folder \\
                                              ParameterKey=GetHostNameFunctionObject,ParameterValue=$gethostname_function_object \\
+                                             ParameterKey=GetHostNameFunctionObjectVersion,ParameterValue=$gethostname_function_object_version \\
                                              ParameterKey=GetDomainNameFunctionObject,ParameterValue=$getdomainname_function_object \\
+                                             ParameterKey=GetDomainNameFunctionObjectVersion,ParameterValue=$getdomainname_function_object_version \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
diff --git a/core/bin/core-update-vpc-stack b/core/bin/core-update-vpc-stack
--- a/core/bin/core-update-vpc-stack
+++ b/core/bin/core-update-vpc-stack
@@ -18,13 +18,13 @@ run_default=10
 pause_default=2
 next_default=5
 update_default=15
-update_attempts=20
+update_attempts=40
 
 interactive=1
 speed=100
 verbose=0
 override=0
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${CORE_NAME:-Core}
@@ -39,8 +39,8 @@ user=${AWS_USER_NAME:-administrator}
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o]"
     echo "                  [-O owner] [-C company ] [-S system]"
-    echo "                  [-E environment] [-N network ]"
-    echo "                  [-r region ] [-a account] [-u user]"
+    echo "                  [-E environment] [-N network]"
+    echo "                  [-r region] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -171,27 +171,49 @@ if [ -z $company ]; then
     echo "-C company missing!"
     echo "Could not automatically determine company, and it was not specified as a parameter"
     exit 12
+else
+    case $company in
+      Travel)
+        ;;
+      *)
+        echo "-C $company invalid! Must be Travel"
+        exit 13;;
+    esac
 fi
 
 if [ -z $system ]; then
     echo "-S system missing!"
     echo "Could not automatically determine system, and it was not specified as a parameter"
     exit 14
+else
+    case $system in
+      IROPS)
+        ;;
+      *)
+        echo "-S $system invalid! Must be IROPS"
+        exit 15;;
+    esac
 fi
 
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
+    exit 20
 else
-    use_multi_zone_nat_gateways=false
-    use_vpn_gateway=true
+    case $environment in
+      Core)
+        use_multi_zone_nat_gateways=false
+        use_vpn_gateway=true;;
+      *)
+        echo "-E $environment invalid! Must be Core"
+        exit 21;;
+    esac
 fi
 
 if [ -z $environment_network ]; then
     echo "-N network missing!"
     echo "Could not automatically determine environment network, and it was not specified as a parameter"
-    exit 20
+    exit 22
 fi
 
 if [ -z $region ]; then
@@ -202,9 +224,9 @@ else
     case $region in
       us-east-1)
         s3_domain=s3.amazonaws.com;;
-      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+      us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
         s3_domain=s3-$region.amazonaws.com;;
-    *)
+      *)
         echo "-r $region invalid: Please specify a valid region"
         exit 51;;
     esac
@@ -227,20 +249,20 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
-fi
-
-templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-templates_folder=core
-
-if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
-    unset templates_bucket
+    exit 58
 fi
 
 if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo "Unable to update - $environment-VPC Stack does not exist!"
-    exit 70
+    exit 80
+fi
+
+templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
+template_folder=core
+
+if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
+    unset templates_bucket
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -290,7 +312,7 @@ fi
 ((++step))
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
-            s3://$templates_bucket/$templates_folder \\
+            s3://$templates_bucket/$template_folder \\
             --exclude '*' --include 'Core-VPC.json' --include 'Core-VPC-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
@@ -322,8 +344,8 @@ fi
 
 ((++step))
 if [ ! -z $templates_bucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templates_bucket/$templates_folder/Core-VPC.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$templates_folder/Core-VPC-StackPolicy.json"
+    template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Core-VPC.json"
+    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Core-VPC-StackPolicy.json"
 else
     template_parameter="--template-body file://$templatesdir/Core-VPC.json"
     stack_policy_parameter="--stack-policy-body file://$templatesdir/Core-VPC-StackPolicy.json"
diff --git a/example/bin/example-create-linuxwebserver-stack b/example/bin/example-create-linuxwebserver-stack
--- a/example/bin/example-create-linuxwebserver-stack
+++ b/example/bin/example-create-linuxwebserver-stack
@@ -24,7 +24,7 @@ interactive=1
 speed=100
 verbose=0
 dummy=0
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
@@ -54,12 +54,12 @@ key=${AWS_KEY_NAME:-example}
 
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-d]"
-    echo "                  [-O owner] [-C company ] [-S system]"
+    echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment] [-T type]"
-    echo "                  [-A application ] [-D domain] [-V version]"
-    echo "                  [-p network] [-P network ]"
-    echo "                  [-n network] [-N network ]"
-    echo "                  [-r region ] [-a account] [-u user] [-k key]"
+    echo "                  [-A application] [-D domain] [-V version]"
+    echo "                  [-p network] [-P network]"
+    echo "                  [-n network] [-N network]"
+    echo "                  [-r region] [-a account] [-u user] [-k key]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -264,8 +264,8 @@ else
         os_name="Amazon Linux"
         log_retention=0;;
       *)
-        os_name="Amazon Linux"
-        log_retention=0;;
+        echo "-E $environment invalid! Must be Production, Staging, Testing, Development, Core or Build"
+        exit 21;;
     esac
 fi
 
@@ -377,31 +377,31 @@ fi
 
 if ! aws cloudformation describe-stacks --stack-name StandardTopics \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "StandardTopics Stack does not exist!"
+    echo "Stack dependency missing - StandardTopics Stack does not exist!"
     exit 60
 fi
 
 if ! aws cloudformation describe-stacks --stack-name StandardBuckets \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "StandardBuckets Stack does not exist!"
+    echo "Stack dependency missing - StandardBuckets Stack does not exist!"
     exit 61
 fi
 
 if ! aws cloudformation describe-stacks --stack-name StandardAMIFunctions \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "StandardAMIFunctions Stack does not exist!"
+    echo "Stack dependency missing - StandardAMIFunctions Stack does not exist!"
     exit 62
 fi
 
 if ! aws cloudformation describe-stacks --stack-name CustomIdentifierFunctions \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "CustomIdentifierFunctions Stack does not exist!"
+    echo "Stack dependency missing - CustomIdentifierFunctions Stack does not exist!"
     exit 64
 fi
 
 if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "$environment-VPC Stack does not exist!"
+    echo "Stack dependency missing - $environment-VPC Stack does not exist!"
     exit 70
 fi
 
