CIDR fix, Adjustments to pre-requisite checks

diff --git a/bootstrap/bin/bootstrap-update-linuxbastion-stack b/bootstrap/bin/bootstrap-update-linuxbastion-stack
--- a/bootstrap/bin/bootstrap-update-linuxbastion-stack
+++ b/bootstrap/bin/bootstrap-update-linuxbastion-stack
@@ -8,9 +8,6 @@
 # This Bootstrap Instance should be destroyed when no longer needed, as it will not exist within
 # the formal VPC infrastructure, and may present a security risk.
 #
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
-#
 
 #  1. Initalize Environment
 
@@ -26,7 +23,7 @@ next_default=5
 update_default=15
 update_attempts=40
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
@@ -38,9 +35,7 @@ environment=Bootstrap # This exists outside Environments
 environment_type=${ENVIRONMENT_TYPE:-micro}
 utility=${UTILITY_NAME:-LinuxBastion}
 home_snapshot=
-public_user_network=${PUBLIC_USER_NETWORK:-0.0.0.0/0}
-public_user_network1=${PUBLIC_USER_NETWORK1:-}
-public_user_network2=${PUBLIC_USER_NETWORK2:-}
+user_networks=${LINUXBASTIONS_USER_NETWORKS:-0.0.0.0/0,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
 region=us-east-1 # This should run only in us-east-1
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=bootstrapadministrator
@@ -49,7 +44,7 @@ key=${AWS_KEY_NAME:-bootstrap}
 use_static_public_address=true
 use_static_home_volume=true
 log_retention=7
-log_alarm_email=mcrawford@hpe.com
+log_alarm_email=mcrawford@dxc.com
 use_local_users=true
 on_schedule="0 11 * * 1-5" # 11:00 UTC = 3:00 AM PST = 6:00 AM EST, Mon-Fri
 off_schedule="0 4 * * *" # 4:00 UTC = 8:00 PM PST = 11:00 PM EST, Mon-Fri
@@ -58,13 +53,13 @@ off_schedule="0 4 * * *" # 4:00 UTC = 8:00 PM PST = 11:00 PM EST, Mon-Fri
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m] [-o]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m] [-o]"
     echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-T type]"
     echo "                  [-U utility] [-h snapshot]"
-    echo "                  [-p network]"
+    echo "                  [-n networks]"
     echo "                  [-a account] [-u user] [-k key]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
@@ -76,7 +71,7 @@ usage () {
     echo "  -T type         Environment Type (default: $environment_type)"
     echo "  -U utility      Utility Name (default: $utility)"
     echo "  -h snapshot     Home Snapshot (default: $home_snapshot)"
-    echo "  -p network      Public User Network (default: $public_user_network)"
+    echo "  -n networks     User Networks (default: $user_networks)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
     echo "  -k key          Key (default: $key)"
@@ -161,11 +156,10 @@ next() {
 
 
 #  3. Parse command line options
-#     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvmoO:C:S:T:U:h:p:1:2:a:u:k:? arg; do
+while getopts isfvmoO:C:S:T:U:h:n:a:u:k:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
@@ -177,9 +171,7 @@ while getopts IsfvmoO:C:S:T:U:h:p:1:2:a:u:k:? arg; do
     T)  environment_type="$OPTARG";;
     U)  utility="$OPTARG";;
     h)  home_snapshot="$OPTARG";;
-    p)  public_user_network="$OPTARG";;
-    1)  public_user_network1="$OPTARG";;
-    2)  public_user_network2="$OPTARG";;
+    n)  user_networks="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
     k)  key="$OPTARG";;
@@ -234,10 +226,10 @@ if [ -z $environment_type ]; then
     exit 22
 else
     case $environment_type in
-      micro|small|medium|large|xlarge)
+      standby|micro|small|medium|large|xlarge)
         ;;
       *)
-        echo "-T $environment_type invalid! Must be micro, small, medium, large or xlarge"
+        echo "-T $environment_type invalid! Must be standby, micro, small, medium, large or xlarge"
         exit 23;;
     esac
 fi
@@ -251,14 +243,14 @@ else
       LinuxBastion*)
         ;;
       *)
-        echo "-U $utility invalid! Must be LinuxBastion*"
+        echo "-U $utility invalid! Must begin with LinuxBastion"
         exit 31;;
     esac
 fi
 
-if [ -z $public_user_network ]; then
-    echo "-p network missing!"
-    echo "Could not automatically determine public user network, and it was not specified as a parameter"
+if [ -z $user_networks ]; then
+    echo "-n networks missing!"
+    echo "Could not automatically determine user networks, and it was not specified as a parameter"
     exit 40
 fi
 
@@ -289,6 +281,19 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Expected to find: [profile $profile] in ~/.aws/config"
     exit 58
 fi
+
+echo -n "Confirming Stack pre-requisites "
+
+if ! aws cloudformation describe-stacks --stack-name $environment-$utility \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo
+    echo "Unable to update - $environment-$utility Stack does not exist!"
+    exit 98
+else
+    echo -n "."
+fi
+echo " Done"
+sleep 1
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -357,9 +362,7 @@ aws cloudformation update-stack --stack-name $environment-$utility \\
                                              ParameterKey=LogAlarmEmail,ParameterValue=$log_alarm_email \\
                                              ParameterKey=OnSchedule,ParameterValue="$on_schedule" \\
                                              ParameterKey=OffSchedule,ParameterValue="$off_schedule" \\
-                                             ParameterKey=PublicUserNetwork,ParameterValue=$public_user_network \\
-                                             ParameterKey=PublicUserNetwork1,ParameterValue=$public_user_network1 \\
-                                             ParameterKey=PublicUserNetwork2,ParameterValue=$public_user_network2 \\
+                                             ParameterKey=UserNetworks,ParameterValue=\"$user_networks\" \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
