Changes to allow update override of stack policy, add Route53, improve ExampleWebServer

diff --git a/environment/bin/environment-create-hostedzone-stack b/environment/bin/environment-create-hostedzone-stack
--- a/environment/bin/environment-create-hostedzone-stack
+++ b/environment/bin/environment-create-hostedzone-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script updates the ReviewUsers Stack in the Identity Account.
+# This script creates the Environment HostedZone Stack in an Environment Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -17,18 +17,18 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-update_default=15
-update_attempts=20
+create_default=15
+create_attempts=20
 
 interactive=1
 speed=100
 verbose=0
-override=0
 owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
-environment=${IDENTITY_NAME:-Identity}
-region=us-east-1 # This should run only in us-east-1
+environment=${ENVIRONMENT_NAME:-Production}
+environment_domain=${ENVIRONMENT_DOMAIN:-demo.iropshub.com}
+region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
 
@@ -36,19 +36,20 @@ user=${AWS_USER_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o]"
+    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
     echo "                  [-O owner] [-C company ] [-S system]"
-    echo "                  [-E environment]"
-    echo "                  [-a account] [-u user]"
+    echo "                  [-E environment] [-D domain]"
+    echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
-    echo "  -o              override StackPolicy"
     echo "  -O owner        Owner Email (default: $owner)"
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
+    echo "  -D domain       Environment Domain (default: $environment_domain)"
+    echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
 }
@@ -133,17 +134,18 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvoO:C:S:E:a:u:? arg; do
+while getopts IsfvO:C:S:E:D:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
-    o)  override=1;;
     O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
+    D)  environment_domain="$OPTARG";;
+    r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
     ?)  usage
@@ -180,7 +182,27 @@ if [ -z $environment ]; then
     exit 16
 fi
 
-s3_domain=s3.amazonaws.com
+if [ -z $environment_domain ]; then
+    echo "-D domain missing!"
+    echo "Could not automatically determine domain, and it was not specified as a parameter"
+    exit 18
+fi
+
+if [ -z $region ]; then
+    echo "-r region missing!"
+    echo "Could not automatically determine region, and it was not specified as a parameter"
+    exit 50
+else
+    case $region in
+      us-east-1)
+        s3_domain=s3.amazonaws.com;;
+      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+        s3_domain=s3-$region.amazonaws.com;;
+    *)
+        echo "-r $region invalid: Please specify a valid region"
+        exit 51;;
+    esac
+fi
 
 if [ -z $account ]; then
     echo "-a account missing!"
@@ -203,16 +225,10 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
 fi
 
 templatesbucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-templatespath=/identity
+templatespath=/environment
 
 if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region $region 2> /dev/null; then
     unset templatesbucket
-fi
-
-if ! aws cloudformation describe-stacks --stack-name ReviewUsers \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - ReviewUsers Stack does not exist!"
-    exit 70
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -263,7 +279,7 @@ fi
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
             s3://$templatesbucket$templatespath \\
-            --exclude '*' --include 'Identity-ReviewUsers.json' --include 'Identity-ReviewUsers-StackPolicy.json' \\
+            --exclude '*' --include 'Environment-HostedZone.json' --include 'Environment-HostedZone-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -294,26 +310,22 @@ fi
 
 ((++step))
 if [ ! -z $templatesbucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Identity-ReviewUsers.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Identity-ReviewUsers-StackPolicy.json"
+    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Environment-HostedZone.json"
+    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Environment-HostedZone-StackPolicy.json"
 else
-    template_parameter="--template-body file://$templatesdir/Identity-ReviewUsers.json"
-    stack_policy_parameter="--stack-policy-body file://$templatesdir/Identity-ReviewUsers-StackPolicy.json"
-fi
-if [ $override = 1 ]; then
-    stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
+    template_parameter="--template-body file://$templatesdir/Environment-HostedZone.json"
+    stack_policy_parameter="--stack-policy-body file://$templatesdir/Environment-HostedZone-StackPolicy.json"
 fi
 read -r -d '' statement << EOS
-aws cloudformation update-stack --stack-name ReviewUsers \\
+aws cloudformation create-stack --stack-name $environment-HostedZone \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\
-                                             ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\
+                                --parameters ParameterKey=Name,ParameterValue=$environment \\
+                                             ParameterKey=Domain,ParameterValue=$environment_domain \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
                                        Key=Environment,Value=$environment \\
-                                --capabilities CAPABILITY_NAMED_IAM \\
                                 --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -323,7 +335,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Update the Stack"
+echo "$(printf '%2d' $step). Create the Stack"
 echo
 echo "============================================================"
 echo
@@ -331,20 +343,31 @@ echo "Commands:"
 echo
 echo "$statement"
 
-run
-
-if [ $choice = y ]; then
+if aws cloudformation describe-stacks --stack-name $environment-HostedZone \
+                                      --profile $profile --region $region --output text &> /dev/null; then
     echo
-    echo "$run_statement"
-    eval "$eval_statement"
+    tput rev
+    echo "Already Created!"
+    tput sgr0
 
-    next
+    next 50
+
+else
+    run
+
+    if [ $choice = y ]; then
+        echo
+        echo "$run_statement"
+        eval "$eval_statement"
+
+        next
+    fi
 fi
 
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name ReviewUsers \\
+aws cloudformation describe-stacks --stack-name $environment-HostedZone \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -352,7 +375,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name ReviewUsers --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name $environment-HostedZone --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -363,7 +386,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Monitor Stack update"
+echo "$(printf '%2d' $step). Monitor Stack creation"
 echo
 echo "============================================================"
 echo
@@ -373,9 +396,9 @@ echo "$statement"
 echo
 echo "$statement2"
 
-if [ "$(aws cloudformation describe-stacks --stack-name ReviewUsers \
+if [ "$(aws cloudformation describe-stacks --stack-name $environment-HostedZone \
                                            --query 'Stacks[].StackStatus' \
-                                           --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
+                                           --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
     echo
     tput rev
     echo "Already Complete!"
@@ -392,16 +415,16 @@ else
         eval "$eval_statement"
 
         attempt=0
-        seconds=$update_default
-        while ((attempt++ <= update_attempts)); do
+        seconds=$create_default
+        while ((attempt++ <= create_attempts)); do
             echo
             echo "$run_statement2"
             eval "$eval_statement2"
 
-            status=$(aws cloudformation describe-stacks --stack-name ReviewUsers \
+            status=$(aws cloudformation describe-stacks --stack-name $environment-HostedZone \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
-            if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
+            if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
                 break
             else
                 echo
@@ -414,6 +437,7 @@ else
         next
     fi
 fi
+
 
 ((++step))
 read -r -d '' statement << EOS
@@ -450,7 +474,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stack-resources --stack-name ReviewUsers \\
+aws cloudformation describe-stack-resources --stack-name $environment-HostedZone \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
                                             --profile $profile --region $region --output table
 EOS
diff --git a/environment/bin/environment-update-hostedzone-stack b/environment/bin/environment-update-hostedzone-stack
--- a/environment/bin/environment-update-hostedzone-stack
+++ b/environment/bin/environment-update-hostedzone-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script updates the ReviewUsers Stack in the Identity Account.
+# This script updates the Environment HostedZone Stack in an Environment Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -27,8 +27,9 @@ override=0
 owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
-environment=${IDENTITY_NAME:-Identity}
-region=us-east-1 # This should run only in us-east-1
+environment=${ENVIRONMENT_NAME:-Production}
+environment_domain=${ENVIRONMENT_DOMAIN:-demo.iropshub.com}
+region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
 
@@ -39,7 +40,7 @@ usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o]"
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment]"
-    echo "                  [-a account] [-u user]"
+    echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -49,6 +50,8 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
+    echo "  -D domain       Environment Domain (default: $environment_domain)"
+    echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
 }
@@ -133,7 +136,7 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvoO:C:S:E:a:u:? arg; do
+while getopts IsfvoO:C:S:E:D:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -144,6 +147,8 @@ while getopts IsfvoO:C:S:E:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
+    D)  environment_domain="$OPTARG";;
+    r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
     ?)  usage
@@ -180,7 +185,27 @@ if [ -z $environment ]; then
     exit 16
 fi
 
-s3_domain=s3.amazonaws.com
+if [ -z $environment_domain ]; then
+    echo "-D domain missing!"
+    echo "Could not automatically determine domain, and it was not specified as a parameter"
+    exit 18
+fi
+
+if [ -z $region ]; then
+    echo "-r region missing!"
+    echo "Could not automatically determine region, and it was not specified as a parameter"
+    exit 50
+else
+    case $region in
+      us-east-1)
+        s3_domain=s3.amazonaws.com;;
+      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+        s3_domain=s3-$region.amazonaws.com;;
+    *)
+        echo "-r $region invalid: Please specify a valid region"
+        exit 51;;
+    esac
+fi
 
 if [ -z $account ]; then
     echo "-a account missing!"
@@ -203,15 +228,15 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
 fi
 
 templatesbucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-templatespath=/identity
+templatespath=/environment
 
 if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region $region 2> /dev/null; then
     unset templatesbucket
 fi
 
-if ! aws cloudformation describe-stacks --stack-name ReviewUsers \
+if ! aws cloudformation describe-stacks --stack-name $environment-HostedZone \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - ReviewUsers Stack does not exist!"
+    echo "Unable to update - $environment-HostedZone Stack does not exist!"
     exit 70
 fi
 
@@ -263,7 +288,7 @@ fi
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
             s3://$templatesbucket$templatespath \\
-            --exclude '*' --include 'Identity-ReviewUsers.json' --include 'Identity-ReviewUsers-StackPolicy.json' \\
+            --exclude '*' --include 'Environment-HostedZone.json' --include 'Environment-HostedZone-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -294,26 +319,25 @@ fi
 
 ((++step))
 if [ ! -z $templatesbucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Identity-ReviewUsers.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Identity-ReviewUsers-StackPolicy.json"
+    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Environment-HostedZone.json"
+    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Environment-HostedZone-StackPolicy.json"
 else
-    template_parameter="--template-body file://$templatesdir/Identity-ReviewUsers.json"
-    stack_policy_parameter="--stack-policy-body file://$templatesdir/Identity-ReviewUsers-StackPolicy.json"
+    template_parameter="--template-body file://$templatesdir/Environment-HostedZone.json"
+    stack_policy_parameter="--stack-policy-body file://$templatesdir/Environment-HostedZone-StackPolicy.json"
 fi
 if [ $override = 1 ]; then
     stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
 fi
 read -r -d '' statement << EOS
-aws cloudformation update-stack --stack-name ReviewUsers \\
+aws cloudformation update-stack --stack-name $environment-HostedZone \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\
-                                             ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\
+                                --parameters ParameterKey=Name,ParameterValue=$environment \\
+                                             ParameterKey=Domain,ParameterValue=$environment_domain \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
                                        Key=Environment,Value=$environment \\
-                                --capabilities CAPABILITY_NAMED_IAM \\
                                 --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -344,7 +368,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name ReviewUsers \\
+aws cloudformation describe-stacks --stack-name $environment-HostedZone \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -352,7 +376,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name ReviewUsers --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name $environment-HostedZone --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -373,7 +397,7 @@ echo "$statement"
 echo
 echo "$statement2"
 
-if [ "$(aws cloudformation describe-stacks --stack-name ReviewUsers \
+if [ "$(aws cloudformation describe-stacks --stack-name $environment-HostedZone \
                                            --query 'Stacks[].StackStatus' \
                                            --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
     echo
@@ -398,7 +422,7 @@ else
             echo "$run_statement2"
             eval "$eval_statement2"
 
-            status=$(aws cloudformation describe-stacks --stack-name ReviewUsers \
+            status=$(aws cloudformation describe-stacks --stack-name $environment-HostedZone \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
             if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
@@ -414,6 +438,7 @@ else
         next
     fi
 fi
+
 
 ((++step))
 read -r -d '' statement << EOS
@@ -450,7 +475,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stack-resources --stack-name ReviewUsers \\
+aws cloudformation describe-stack-resources --stack-name $environment-HostedZone \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
                                             --profile $profile --region $region --output table
 EOS
