Merge multiple development tasks, mainly related to Route53
* improvements to Example-WebServer application
* Changes to allow update override of stack policy, add Route53, improve ExampleWebServer
* added some simple per-region sequence driver scripts, likely temporary until something more sophisticated can be created
* added template to create a single VPNPeeringConnection between environments
* removed line which should have been removed in prior mass-update
* fixed typo; removed unnecessary capability

diff --git a/core/bin/build-create-vpc-stack b/core/bin/build-create-vpc-stack
--- a/core/bin/build-create-vpc-stack
+++ b/core/bin/build-create-vpc-stack
@@ -27,7 +27,6 @@ owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
 environment=${BUILD_NAME:-Build}
-environment_domain=${BUILD_DOMAIN:-demo.iropshub.com}
 environment_network=${BUILD_NETWORK:-10.47.0.0/16}
 environment_ha_nat_gateways=${BUILD_HA_NAT_GATEWAYS:-false}
 region=${AWS_DEFAULT_REGION:-us-west-2}
@@ -40,7 +39,7 @@ user=${AWS_USER_NAME:-administrator}
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
     echo "                  [-O owner] [-C company ] [-S system]"
-    echo "                  [-E environment] [-D domain] [-N network ]"
+    echo "                  [-E environment] [-N network ]"
     echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
@@ -50,7 +49,6 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -D domain       Environment Domain (default: $environment_domain)"
     echo "  -N network      Environment Network (default: $environment_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
@@ -137,7 +135,7 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvO:C:S:E:D:N:r:a:u:? arg; do
+while getopts IsfvO:C:S:E:N:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -147,7 +145,6 @@ while getopts IsfvO:C:S:E:D:N:r:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    D)  environment_domain="$OPTARG";;
     N)  environment_network="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
@@ -184,12 +181,6 @@ if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
     exit 16
-fi
-
-if [ -z $environment_domain ]; then
-    echo "-D domain missing!"
-    echo "Could not automatically determine environmeht domain, and it was not specified as a parameter"
-    exit 18
 fi
 
 if [ -z $environment_network ]; then
@@ -239,6 +230,12 @@ templatespath=/core
 
 if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region $region 2> /dev/null; then
     unset templatesbucket
+fi
+
+if ! aws cloudformation describe-stacks --stack-name Production-HostedZone \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo "Unable to update - Production-HostedZone Stack does not exist!"
+    exit 70
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -330,9 +327,9 @@ read -r -d '' statement << EOS
 aws cloudformation create-stack --stack-name $environment-VPC \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=Name,ParameterValue=$environment \\
+                                --parameters ParameterKey=HostedZoneStackName,ParameterValue=Production-HostedZone \\
+                                             ParameterKey=Name,ParameterValue=$environment \\
                                              ParameterKey=Network,ParameterValue=$environment_network \\
-                                             ParameterKey=Domain,ParameterValue=$environment_domain \\
                                              ParameterKey=UseMultiZoneNatGateways,ParameterValue=$environment_ha_nat_gateways \\
                                              ParameterKey=UseVPNGateway,ParameterValue=true \\
                                 --tags Key=Owner,Value=$owner \\
diff --git a/core/bin/core-create-vpcpeeringconnections-stack b/core/bin/core-create-vpcpeeringconnections-stack
--- a/core/bin/core-create-vpcpeeringconnections-stack
+++ b/core/bin/core-create-vpcpeeringconnections-stack
@@ -34,7 +34,7 @@ core_vpc_stack_name=Core-VPC
 build_vpc_stack_name=Build-VPC
 production_vpc_stack_name=Production-VPC
 staging_vpc_stack_name=Staging-VPC
-qa_vpc_stack_name=QA-VPC
+testing_vpc_stack_name=Testing-VPC
 development_vpc_stack_name=Development-VPC
 
 
@@ -243,10 +243,10 @@ if ! aws cloudformation describe-stacks --stack-name Staging-VPC \
     unset staging_vpc_stack_name
 fi
 
-if ! aws cloudformation describe-stacks --stack-name QA-VPC \
+if ! aws cloudformation describe-stacks --stack-name Testing-VPC \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Stack dependency missing - QA-VPC Stack does not exist!"
-    unset qa_vpc_stack_name
+    echo "Stack dependency missing - Testing-VPC Stack does not exist!"
+    unset testing_vpc_stack_name
 fi
 
 if ! aws cloudformation describe-stacks --stack-name Development-VPC \
@@ -349,7 +349,7 @@ aws cloudformation create-stack --stack-name Core-VPCPeeringConnections \\
                                              ParameterKey=BuildVPCStackName,ParameterValue=$build_vpc_stack_name \\
                                              ParameterKey=ProductionVPCStackName,ParameterValue=$production_vpc_stack_name \\
                                              ParameterKey=StagingVPCStackName,ParameterValue=$staging_vpc_stack_name \\
-                                             ParameterKey=QAVPCStackName,ParameterValue=$qa_vpc_stack_name \\
+                                             ParameterKey=TestingVPCStackName,ParameterValue=$testing_vpc_stack_name \\
                                              ParameterKey=DevelopmentVPCStackName,ParameterValue=$development_vpc_stack_name \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
diff --git a/core/bin/core-update-vpcpeeringconnections-stack b/core/bin/core-update-vpcpeeringconnections-stack
--- a/core/bin/core-update-vpcpeeringconnections-stack
+++ b/core/bin/core-update-vpcpeeringconnections-stack
@@ -23,6 +23,7 @@ update_attempts=20
 interactive=1
 speed=100
 verbose=0
+override=0
 owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
@@ -34,23 +35,23 @@ core_vpc_stack_name=Core-VPC
 build_vpc_stack_name=Build-VPC
 production_vpc_stack_name=Production-VPC
 staging_vpc_stack_name=Staging-VPC
-qa_vpc_stack_name=QA-VPC
+testing_vpc_stack_name=Testing-VPC
 development_vpc_stack_name=Development-VPC
 
 
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
+    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o]"
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
+    echo "  -o              override StackPolicy"
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
-    echo "  -E environment  Environment Name (default: $environment)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -136,12 +137,13 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvO:C:S:r:a:u:? arg; do
+while getopts IsfvoO:C:S:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
+    o)  override=1;;
     O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
@@ -249,10 +251,10 @@ if ! aws cloudformation describe-stacks --stack-name Staging-VPC \
     unset staging_vpc_stack_name
 fi
 
-if ! aws cloudformation describe-stacks --stack-name QA-VPC \
+if ! aws cloudformation describe-stacks --stack-name Testing-VPC \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Stack dependency missing - QA-VPC Stack does not exist!"
-    unset qa_vpc_stack_name
+    echo "Stack dependency missing - Testing-VPC Stack does not exist!"
+    unset testing_vpc_stack_name
 fi
 
 if ! aws cloudformation describe-stacks --stack-name Development-VPC \
@@ -348,6 +350,9 @@ else
     template_parameter="--template-body file://$templatesdir/Core-VPCPeeringConnections.json"
     stack_policy_parameter="--stack-policy-body file://$templatesdir/Core-VPCPeeringConnections-StackPolicy.json"
 fi
+if [ $override = 1 ]; then
+    stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
+fi
 read -r -d '' statement << EOS
 aws cloudformation update-stack --stack-name Core-VPCPeeringConnections \\
                                 $template_parameter \\
@@ -356,7 +361,7 @@ aws cloudformation update-stack --stack-name Core-VPCPeeringConnections \\
                                              ParameterKey=BuildVPCStackName,ParameterValue=$build_vpc_stack_name \\
                                              ParameterKey=ProductionVPCStackName,ParameterValue=$production_vpc_stack_name \\
                                              ParameterKey=StagingVPCStackName,ParameterValue=$staging_vpc_stack_name \\
-                                             ParameterKey=QAVPCStackName,ParameterValue=$qa_vpc_stack_name \\
+                                             ParameterKey=TestingVPCStackName,ParameterValue=$testing_vpc_stack_name \\
                                              ParameterKey=DevelopmentVPCStackName,ParameterValue=$development_vpc_stack_name \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
