fixed a couple of updates which were missed

diff --git a/core/bin/core-create-standardsubscriptions-stack b/core/bin/core-create-standardsubscriptions-stack
--- a/core/bin/core-create-standardsubscriptions-stack
+++ b/core/bin/core-create-standardsubscriptions-stack
@@ -239,17 +239,17 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 58
 fi
 
+if ! aws cloudformation describe-stacks --stack-name StandardTopics \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo "Stack dependency missing - StandardTopics Stack does not exist!"
+    exit 60
+fi
+
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
 template_folder=core
 
 if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
     unset templates_bucket
-fi
-
-if ! aws cloudformation describe-stacks --stack-name StandardTopics \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo "Stack dependency missing - StandardTopics Stack does not exist!"
-    exit 60
 fi
 
 # Prevent certain environment variables from breaking commands
