separate Billing related resources and create new scripts to run only in us-east-1

diff --git a/core/bin/core-create-billingalarms-stack b/core/bin/core-create-billingalarms-stack
--- a/core/bin/core-create-billingalarms-stack
+++ b/core/bin/core-create-billingalarms-stack
@@ -27,7 +27,7 @@ owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
 environment=${CORE_NAME:-Core}
-region=${AWS_DEFAULT_REGION:-us-west-2}
+region=us-east-1 # This must currently run only in us-east-1
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
 
@@ -41,7 +41,7 @@ usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment]"
-    echo "                  [-r region ] [-a account] [-u user]"
+    echo "                  [-a account ] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -50,7 +50,6 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
 }
@@ -135,7 +134,7 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvO:C:S:E:r:a:u:? arg; do
+while getopts IsfvO:C:S:E:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -145,7 +144,6 @@ while getopts IsfvO:C:S:E:r:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
     ?)  usage
@@ -182,21 +180,7 @@ if [ -z $environment ]; then
     exit 16
 fi
 
-if [ -z $region ]; then
-    echo "-r region missing!"
-    echo "Could not automatically determine region, and it was not specified as a parameter"
-    exit 50
-else
-    case $region in
-      us-east-1)
-        s3_domain=s3.amazonaws.com;;
-      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
-        s3_domain=s3-$region.amazonaws.com;;
-    *)
-        echo "-r $region invalid: Please specify a valid region"
-        exit 51;;
-    esac
-fi
+s3_domain=s3.amazonaws.com
 
 if [ -z $account ]; then
     echo "-a account missing!"
@@ -222,9 +206,9 @@ if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region
     unset templatesbucket
 fi
 
-if ! aws cloudformation describe-stacks --stack-name StandardTopics \
+if ! aws cloudformation describe-stacks --stack-name BillingTopics \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Stack dependency missing - StandardTopics Stack does not exist!"
+    echo "Stack dependency missing - BillingTopics Stack does not exist!"
     exit 70
 fi
 
@@ -317,7 +301,7 @@ read -r -d '' statement << EOS
 aws cloudformation create-stack --stack-name BillingAlarms \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
+                                --parameters ParameterKey=BillingTopicsStackName,ParameterValue=BillingTopics \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
diff --git a/core/bin/core-create-billingsubscriptions-stack b/core/bin/core-create-billingsubscriptions-stack
--- a/core/bin/core-create-billingsubscriptions-stack
+++ b/core/bin/core-create-billingsubscriptions-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script updates the BillingAlarms Stack in the Core Account.
+# This script creates the BillingSubscriptions Stack in the Core Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -17,8 +17,8 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-update_default=15
-update_attempts=20
+create_default=15
+create_attempts=20
 
 interactive=1
 speed=100
@@ -206,9 +206,9 @@ if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region
     unset templatesbucket
 fi
 
-if ! aws cloudformation describe-stacks --stack-name BillingAlarms \
+if ! aws cloudformation describe-stacks --stack-name StandardTopics \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - BillingAlarms Stack does not exist!"
+    echo "Stack dependency missing - StandardTopics Stack does not exist!"
     exit 70
 fi
 
@@ -260,7 +260,7 @@ fi
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
             s3://$templatesbucket$templatespath \\
-            --exclude '*' --include 'Core-BillingAlarms.json' --include 'Core-BillingAlarms-StackPolicy.json' \\
+            --exclude '*' --include 'Core-BillingSubscriptions.json' --include 'Core-BillingSubscriptions-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -291,17 +291,17 @@ fi
 
 ((++step))
 if [ ! -z $templatesbucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingAlarms.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingAlarms-StackPolicy.json"
+    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingSubscriptions.json"
+    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingSubscriptions-StackPolicy.json"
 else
-    template_parameter="--template-body file://$templatesdir/Core-BillingAlarms.json"
-    stack_policy_parameter="--stack-policy-body file://$templatesdir/Core-BillingAlarms-StackPolicy.json"
+    template_parameter="--template-body file://$templatesdir/Core-BillingSubscriptions.json"
+    stack_policy_parameter="--stack-policy-body file://$templatesdir/Core-BillingSubscriptions-StackPolicy.json"
 fi
 read -r -d '' statement << EOS
-aws cloudformation update-stack --stack-name BillingAlarms \\
+aws cloudformation create-stack --stack-name BillingSubscriptions \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=BillingTopicsStackName,ParameterValue=BillingTopics \\
+                                --parameters ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
@@ -315,7 +315,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Update the Stack"
+echo "$(printf '%2d' $step). Create the Stack"
 echo
 echo "============================================================"
 echo
@@ -323,20 +323,31 @@ echo "Commands:"
 echo
 echo "$statement"
 
-run
-
-if [ $choice = y ]; then
+if aws cloudformation describe-stacks --stack-name BillingSubscriptions \
+                                      --profile $profile --region $region --output text &> /dev/null; then
     echo
-    echo "$run_statement"
-    eval "$eval_statement"
+    tput rev
+    echo "Already Created!"
+    tput sgr0
 
-    next
+    next 50
+
+else
+    run
+
+    if [ $choice = y ]; then
+        echo
+        echo "$run_statement"
+        eval "$eval_statement"
+
+        next
+    fi
 fi
 
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name BillingAlarms \\
+aws cloudformation describe-stacks --stack-name BillingSubscriptions \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -344,7 +355,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name BillingAlarms --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name BillingSubscriptions --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -355,7 +366,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Monitor Stack update"
+echo "$(printf '%2d' $step). Monitor Stack creation"
 echo
 echo "============================================================"
 echo
@@ -365,9 +376,9 @@ echo "$statement"
 echo
 echo "$statement2"
 
-if [ "$(aws cloudformation describe-stacks --stack-name BillingAlarms \
+if [ "$(aws cloudformation describe-stacks --stack-name BillingSubscriptions \
                                            --query 'Stacks[].StackStatus' \
-                                           --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
+                                           --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
     echo
     tput rev
     echo "Already Complete!"
@@ -384,16 +395,16 @@ else
         eval "$eval_statement"
 
         attempt=0
-        seconds=$update_default
-        while ((attempt++ <= update_attempts)); do
+        seconds=$create_default
+        while ((attempt++ <= create_attempts)); do
             echo
             echo "$run_statement2"
             eval "$eval_statement2"
 
-            status=$(aws cloudformation describe-stacks --stack-name BillingAlarms \
+            status=$(aws cloudformation describe-stacks --stack-name BillingSubscriptions \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
-            if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
+            if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
                 break
             else
                 echo
@@ -443,7 +454,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stack-resources --stack-name BillingAlarms \\
+aws cloudformation describe-stack-resources --stack-name BillingSubscriptions \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
                                             --profile $profile --region $region --output table
 EOS
diff --git a/core/bin/core-delete-billingtopics-stack b/core/bin/core-delete-billingtopics-stack
--- a/core/bin/core-delete-billingtopics-stack
+++ b/core/bin/core-delete-billingtopics-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script updates the BillingAlarms Stack in the Core Account.
+# This script deletes the BillingTopics Stack in the Core Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -17,41 +17,28 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-update_default=15
-update_attempts=20
+delete_default=15
+delete_attempts=20
 
 interactive=1
 speed=100
 verbose=0
-owner=${OWNER_EMAIL:-$USER@hpe.com}
-company=${COMPANY_NAME:-Demo}
-system=${SYSTEM_NAME:-IROPS}
-environment=${CORE_NAME:-Core}
 region=us-east-1 # This must currently run only in us-east-1
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
-
-templatesbucket=${AWS_TEMPLATES_BUCKET:-templates-$account}
-templatespath=/core
 
 
 #  2. Define functions
 
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
-    echo "                  [-O owner] [-C company ] [-S system]"
-    echo "                  [-E environment]"
-    echo "                  [-a account] [-u user]"
-    echo "  -I              non-interactive"
-    echo "  -s              slower: increase pauses by 25%"
-    echo "  -f              faster: reduce pauses by 25%"
-    echo "  -v              verbose"
-    echo "  -O owner        Owner Email (default: $owner)"
-    echo "  -C company      Company Name (default: $company)"
-    echo "  -S system       System Name (default: $system)"
-    echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -a account      Account (default: $account)"
-    echo "  -u user         User (default: $user)"
+    echo "              [-a account] [-u user]"
+    echo "  -I          non-interactive"
+    echo "  -s          slower: increase pauses by 25%"
+    echo "  -f          faster: reduce pauses by 25%"
+    echo "  -v          verbose"
+    echo "  -a account  Account (default: $account)"
+    echo "  -u user     User (default: $user)"
 }
 
 run() {
@@ -134,16 +121,12 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvO:C:S:E:a:u:? arg; do
+while getopts Isfva:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
-    O)  owner="$OPTARG";;
-    C)  company="$OPTARG";;
-    S)  system="$OPTARG";;
-    E)  environment="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
     ?)  usage
@@ -155,30 +138,6 @@ shift $(($OPTIND - 1))
 
 
 #  4. Validate environment
-
-if [ -z $owner ]; then
-    echo "-O owner missing!"
-    echo "Could not automatically determine owner, and it was not specified as a parameter"
-    exit 10
-fi
-
-if [ -z $company ]; then
-    echo "-C company missing!"
-    echo "Could not automatically determine company, and it was not specified as a parameter"
-    exit 12
-fi
-
-if [ -z $system ]; then
-    echo "-S system missing!"
-    echo "Could not automatically determine system, and it was not specified as a parameter"
-    exit 14
-fi
-
-if [ -z $environment ]; then
-    echo "-E environment missing!"
-    echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
-fi
 
 s3_domain=s3.amazonaws.com
 
@@ -202,13 +161,9 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 60
 fi
 
-if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region $region 2> /dev/null; then
-    unset templatesbucket
-fi
-
-if ! aws cloudformation describe-stacks --stack-name BillingAlarms \
+if ! aws cloudformation describe-stacks --stack-name BillingTopics \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - BillingAlarms Stack does not exist!"
+    echo "Unable to delete - BillingTopics Stack does not exist!"
     exit 70
 fi
 
@@ -258,64 +213,17 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws s3 sync $templatesdir \\
-            s3://$templatesbucket$templatespath \\
-            --exclude '*' --include 'Core-BillingAlarms.json' --include 'Core-BillingAlarms-StackPolicy.json' \\
-            --profile $profile --region $region --output table
-EOS
-run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'}"
-
-if [ ! -z $templatesbucket ]; then
-    clear
-    echo
-    echo "============================================================"
-    echo
-    echo "$(printf '%2d' $step). Sync Template and Policy to ($templatesbucket) Bucket"
-    echo
-    echo "============================================================"
-    echo
-    echo "Commands:"
-    echo
-    echo "$statement"
-
-    next 50
-
-    echo
-    echo "$run_statement"
-    eval "$eval_statement"
-
-    next 50
-fi
-
-
-((++step))
-if [ ! -z $templatesbucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingAlarms.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingAlarms-StackPolicy.json"
-else
-    template_parameter="--template-body file://$templatesdir/Core-BillingAlarms.json"
-    stack_policy_parameter="--stack-policy-body file://$templatesdir/Core-BillingAlarms-StackPolicy.json"
-fi
-read -r -d '' statement << EOS
-aws cloudformation update-stack --stack-name BillingAlarms \\
-                                $template_parameter \\
-                                $stack_policy_parameter \\
-                                --parameters ParameterKey=BillingTopicsStackName,ParameterValue=BillingTopics \\
-                                --tags Key=Owner,Value=$owner \\
-                                       Key=Company,Value=$company \\
-                                       Key=System,Value=$system \\
-                                       Key=Environment,Value=$environment \\
+aws cloudformation delete-stack --stack-name BillingTopics \\
                                 --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'}"
+eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Update the Stack"
+echo "$(printf '%2d' $step). Delete the Stack"
 echo
 echo "============================================================"
 echo
@@ -323,20 +231,31 @@ echo "Commands:"
 echo
 echo "$statement"
 
-run
-
-if [ $choice = y ]; then
+if ! aws cloudformation describe-stacks --stack-name BillingTopics \
+                                        --profile $profile --region $region --output text &> /dev/null; then
     echo
-    echo "$run_statement"
-    eval "$eval_statement"
+    tput rev
+    echo "Already Deleted!"
+    tput sgr0
 
-    next
+    next 50
+
+else
+    run
+
+    if [ $choice = y ]; then
+        echo
+        echo "$run_statement"
+        eval "$eval_statement"
+
+        next
+    fi
 fi
 
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name BillingAlarms \\
+aws cloudformation describe-stacks --stack-name BillingTopics \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -344,7 +263,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name BillingAlarms --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name BillingTopics --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -355,7 +274,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Monitor Stack update"
+echo "$(printf '%2d' $step). Monitor Stack deletion"
 echo
 echo "============================================================"
 echo
@@ -365,12 +284,11 @@ echo "$statement"
 echo
 echo "$statement2"
 
-if [ "$(aws cloudformation describe-stacks --stack-name BillingAlarms \
-                                           --query 'Stacks[].StackStatus' \
-                                           --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
+if ! aws cloudformation describe-stacks --stack-name BillingTopics \
+                                        --profile $profile --region $region &> /dev/null; then
     echo
     tput rev
-    echo "Already Complete!"
+    echo "Already Deleted!"
     tput sgr0
 
     next 50
@@ -384,16 +302,16 @@ else
         eval "$eval_statement"
 
         attempt=0
-        seconds=$update_default
-        while ((attempt++ <= update_attempts)); do
+        seconds=$delete_default
+        while ((attempt++ <= delete_attempts)); do
             echo
             echo "$run_statement2"
             eval "$eval_statement2"
 
-            status=$(aws cloudformation describe-stacks --stack-name BillingAlarms \
+            status=$(aws cloudformation describe-stacks --stack-name BillingTopics \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
-            if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
+            if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
                 break
             else
                 echo
@@ -422,40 +340,6 @@ if [ $verbose = 1 ]; then
     echo "============================================================"
     echo
     echo "$(printf '%2d' $step). List Resulting Stacks"
-    echo
-    echo "============================================================"
-    echo
-    echo "Commands:"
-    echo
-    echo "$statement"
-
-    run 50
-
-    if [ $choice = y ]; then
-        echo
-        echo "$run_statement"
-        eval "$eval_statement"
-
-        next
-    fi
-fi
-
-
-((++step))
-read -r -d '' statement << EOS
-aws cloudformation describe-stack-resources --stack-name BillingAlarms \\
-                                            --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
-                                            --profile $profile --region $region --output table
-EOS
-run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'} 2> /dev/null"
-
-if [ $verbose = 1 ]; then
-    clear
-    echo
-    echo "============================================================"
-    echo
-    echo "$(printf '%2d' $step). List Resulting Stack Resources"
     echo
     echo "============================================================"
     echo
diff --git a/core/bin/core-update-billingtopics-stack b/core/bin/core-update-billingtopics-stack
--- a/core/bin/core-update-billingtopics-stack
+++ b/core/bin/core-update-billingtopics-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script updates the BillingAlarms Stack in the Core Account.
+# This script updates the BillingTopics Stack in the Core Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -206,9 +206,9 @@ if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region
     unset templatesbucket
 fi
 
-if ! aws cloudformation describe-stacks --stack-name BillingAlarms \
+if ! aws cloudformation describe-stacks --stack-name BillingTopics \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - BillingAlarms Stack does not exist!"
+    echo "Unable to update - BillingTopics Stack does not exist!"
     exit 70
 fi
 
@@ -260,7 +260,7 @@ fi
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
             s3://$templatesbucket$templatespath \\
-            --exclude '*' --include 'Core-BillingAlarms.json' --include 'Core-BillingAlarms-StackPolicy.json' \\
+            --exclude '*' --include 'Core-BillingTopics.json' --include 'Core-BillingTopics-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -291,17 +291,16 @@ fi
 
 ((++step))
 if [ ! -z $templatesbucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingAlarms.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingAlarms-StackPolicy.json"
+    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingTopics.json"
+    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Core-BillingTopics-StackPolicy.json"
 else
-    template_parameter="--template-body file://$templatesdir/Core-BillingAlarms.json"
-    stack_policy_parameter="--stack-policy-body file://$templatesdir/Core-BillingAlarms-StackPolicy.json"
+    template_parameter="--template-body file://$templatesdir/Core-BillingTopics.json"
+    stack_policy_parameter="--stack-policy-body file://$templatesdir/Core-BillingTopics-StackPolicy.json"
 fi
 read -r -d '' statement << EOS
-aws cloudformation update-stack --stack-name BillingAlarms \\
+aws cloudformation update-stack --stack-name BillingTopics \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=BillingTopicsStackName,ParameterValue=BillingTopics \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
@@ -336,7 +335,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name BillingAlarms \\
+aws cloudformation describe-stacks --stack-name BillingTopics \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -344,7 +343,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name BillingAlarms --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name BillingTopics --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -365,7 +364,7 @@ echo "$statement"
 echo
 echo "$statement2"
 
-if [ "$(aws cloudformation describe-stacks --stack-name BillingAlarms \
+if [ "$(aws cloudformation describe-stacks --stack-name BillingTopics \
                                            --query 'Stacks[].StackStatus' \
                                            --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
     echo
@@ -390,7 +389,7 @@ else
             echo "$run_statement2"
             eval "$eval_statement2"
 
-            status=$(aws cloudformation describe-stacks --stack-name BillingAlarms \
+            status=$(aws cloudformation describe-stacks --stack-name BillingTopics \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
             if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
@@ -443,7 +442,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stack-resources --stack-name BillingAlarms \\
+aws cloudformation describe-stack-resources --stack-name BillingTopics \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
                                             --profile $profile --region $region --output table
 EOS
