changes to WebSphereMQ - adjust instancetypes, change to use of EnvironmentType and EnvironmentZones

diff --git a/application/bin/application-update-webspheremq-stack b/application/bin/application-update-webspheremq-stack
--- a/application/bin/application-update-webspheremq-stack
+++ b/application/bin/application-update-webspheremq-stack
@@ -28,10 +28,9 @@ owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
-environment_size=${ENVIRONMENT_SIZE:-medium}
+environment_type=${ENVIRONMENT_TYPE:-large}
 application=${APPLICATION_NAME:-WebSphereMQ}
 application_version=${APPLICATION_VERSION:-1.0.0}
-key=${AWS_KEY_NAME:-user}
 private_user_network=${PRIVATE_USER_NETWORK:-10.0.0.0/16}
 private_user_network1=${PRIVATE_USER_NETWORK1:-}
 private_user_network2=${PRIVATE_USER_NETWORK2:-}
@@ -41,6 +40,7 @@ private_administrator_network2=${PRIVATE_ADMINISTRATOR_NETWORK2:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
+key=${AWS_KEY_NAME:-user}
 
 
 #  2. Define functions
@@ -48,11 +48,10 @@ user=${AWS_USER_NAME:-administrator}
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o]"
     echo "                  [-O owner] [-C company ] [-S system]"
-    echo "                  [-E environment] [-Z size]"
+    echo "                  [-E environment] [-T type]"
     echo "                  [-A application ] [-V version]"
-    echo "                  [-k key]"
     echo "                  [-n network] [-N network ]"
-    echo "                  [-r region ] [-a account] [-u user]"
+    echo "                  [-r region ] [-a account] [-u user] [-k key]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -62,15 +61,15 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -Z size         Environment Size (default: $environment_size)"
+    echo "  -T type         Environment Type (default: $environment_type)"
     echo "  -A application  Application Name (default: $application)"
     echo "  -V version      Application Version (default: $application_version)"
-    echo "  -k key          Key (default: $key)"
     echo "  -n network      Private User Network (default: $private_user_network)"
     echo "  -N network      Private Administrator Network (default: $private_administrator_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
+    echo "  -k key          Key (default: $key)"
 }
 
 run() {
@@ -154,7 +153,7 @@ next() {
 #  3. Parse command line options
 #     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvoO:C:S:E:Z:A:V:k:n:5:6:N:7:8:r:a:u:? arg; do
+while getopts IsfvO:C:S:E:T:A:V:n:5:6:N:7:8:r:a:u:k:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -165,10 +164,9 @@ while getopts IsfvoO:C:S:E:Z:A:V:k:n:5:6:N:7:8:r:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    Z)  environment_size="$OPTARG";;
+    T)  environment_type="$OPTARG";;
     A)  application="$OPTARG";;
     V)  application_version="$OPTARG";;
-    k)  key="$OPTARG";;
     n)  private_user_network="$OPTARG";;
     5)  private_user_network1="$OPTARG";;
     6)  private_user_network2="$OPTARG";;
@@ -178,6 +176,7 @@ while getopts IsfvoO:C:S:E:Z:A:V:k:n:5:6:N:7:8:r:a:u:? arg; do
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
+    k)  key="$OPTARG";;
     ?)  usage
         exit 1;;
     esac
@@ -225,7 +224,7 @@ fi
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
+    exit 20
 else
     case $environment in
       Production)
@@ -260,49 +259,44 @@ else
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       *)
         echo "-E $environment invalid! Must be Production, Staging, Testing, Development or Core"
-        exit 17;;
+        exit 21;;
     esac
 fi
 
-if [ -z $environment_size ]; then
-    echo "-Z size missing!"
-    echo "Could not automatically determine size, and it was not specified as a parameter"
-    exit 18
+if [ -z $environment_type ]; then
+    echo "-T type missing!"
+    echo "Could not automatically determine environment type, and it was not specified as a parameter"
+    exit 22
 else
-    case $environment_size in
+    case $environment_type in
       small|medium|large|xlarge)
         ;;
       *)
-        echo "-Z $environment_size invalid! Must be small, medium, large or xlarge"
-        exit 19;;
+        echo "-T $environment_type invalid! Must be small, medium, large or xlarge"
+        exit 23;;
     esac
 fi
 
 if [ -z $application ]; then
     echo "-A application missing!"
     echo "Could not automatically determine application, and it was not specified as a parameter"
-    exit 20
+    exit 30
 else
     case $application in
       WebSphereMQ)
         ;;
       *)
         echo "-A $application invalid! Must be WebSphereMQ"
-        exit 21;;
+        exit 31;;
     esac
 fi
 
 if [ -z $application_version ]; then
     echo "-V version missing!"
     echo "Could not automatically determine version, and it was not specified as a parameter"
-    exit 24
+    exit 34
 fi
 
-if [ -z $key ]; then
-    echo "-k key missing!"
-    echo "Could not automatically determine key, and it was not specified as a parameter"
-    exit 30
-fi
 
 if [ -z $private_user_network ]; then
     echo "-n network missing!"
@@ -344,45 +338,36 @@ if [ -z $user ]; then
     exit 54
 fi
 
+if [ -z $key ]; then
+    echo "-k key missing!"
+    echo "Could not automatically determine key, and it was not specified as a parameter"
+    exit 56
+fi
+
 profile=$account-$user
 
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
-fi
-
-templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-template_folder=application
-
-if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
-    echo "$templates_bucket S3 bucket does not exist!"
-    exit 62
-fi
-
-products_bucket=${AWS_PRODUCTS_BUCKET:-products-$region-$account}
-product_folder=WebSphereMQ
-product_object=WS_MQ_V8.0.0.4_LINUX_ON_X86_64_IM.tar.gz
-
-if ! aws s3api head-bucket --bucket $products_bucket --profile $profile --region $region 2> /dev/null; then
-    echo "$products_bucket S3 bucket does not exist!"
-    exit 64
-fi
-
-configurations_bucket=${AWS_CONFIGURATIONS_BUCKET:-configurations-$region-$account}
-configuration_folder=WebSphereMQ
-configuration_object=$environment-WebSphereMQ-etc-wmq.tgz
-
-if ! aws s3api head-bucket --bucket $configurations_bucket --profile $profile --region $region 2> /dev/null; then
-    echo "$configurations_bucket S3 bucket does not exist!"
-    exit 66
+    exit 58
 fi
 
 if ! aws cloudformation describe-stacks --stack-name $environment-$application \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo "Unable to update - $environment-$application Stack does not exist!"
-    exit 70
+    exit 80
 fi
+
+templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
+template_folder=application
+
+products_bucket=${AWS_PRODUCTS_BUCKET:-products-$region-$account}
+product_folder=WebSphereMQ
+product_object=WS_MQ_V8.0.0.4_LINUX_ON_X86_64_IM.tar.gz
+
+configurations_bucket=${AWS_CONFIGURATIONS_BUCKET:-configurations-$region-$account}
+configuration_folder=WebSphereMQ
+configuration_object=$environment-WebSphereMQ-etc-wmq.tgz
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -465,11 +450,6 @@ next 50
 
 
 ((++step))
-if [ $dummy = 1 ]; then
-    # unset download location, which triggers creation of dummy application page within the template
-    unset applications_bucket
-fi
-
 template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Application-WebSphereMQ.json"
 stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Application-WebSphereMQ-StackPolicy.json"
 if [ $override = 1 ]; then
@@ -485,18 +465,16 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                              ParameterKey=CustomIdentifierFunctionsStackName,ParameterValue=CustomIdentifierFunctions \\
                                              ParameterKey=StandardCIDRFunctionsStackName,ParameterValue=StandardCIDRFunctions \\
                                              ParameterKey=StandardAMIFunctionsStackName,ParameterValue=StandardAMIFunctions \\
+                                             ParameterKey=StandardBucketsStackName,ParameterValue=StandardBuckets \\
                                              ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
-                                             ParameterKey=TemplatesBucket,ParameterValue=$templates_bucket \\
                                              ParameterKey=TemplateFolder,ParameterValue=$template_folder \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
-                                             ParameterKey=EnvironmentSize,ParameterValue=$environment_size \\
+                                             ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
                                              ParameterKey=OSName,ParameterValue="$os_name" \\
-                                             ParameterKey=ProductsBucket,ParameterValue=$products_bucket \\
                                              ParameterKey=ProductFolder,ParameterValue=$product_folder \\
                                              ParameterKey=ProductObject,ParameterValue=$product_object \\
-                                             ParameterKey=ConfigurationsBucket,ParameterValue=$configurations_bucket \\
                                              ParameterKey=ConfigurationFolder,ParameterValue=$configuration_folder \\
                                              ParameterKey=ConfigurationObject,ParameterValue=$configuration_object \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
