switch to new network env vars; add code to install SSM

diff --git a/application/bin/application-update-webspheremq-stack b/application/bin/application-update-webspheremq-stack
--- a/application/bin/application-update-webspheremq-stack
+++ b/application/bin/application-update-webspheremq-stack
@@ -35,7 +35,9 @@ key=${AWS_KEY_NAME:-user}
 private_user_network=${PRIVATE_USER_NETWORK:-10.0.0.0/16}
 private_user_network1=${PRIVATE_USER_NETWORK1:-}
 private_user_network2=${PRIVATE_USER_NETWORK2:-}
-private_user_network3=${PRIVATE_USER_NETWORK3:-}
+private_administrator_network=${PRIVATE_ADMINISTRATOR_NETWORK:-10.0.0.0/16}
+private_administrator_network1=${PRIVATE_ADMINISTRATOR_NETWORK1:-}
+private_administrator_network2=${PRIVATE_ADMINISTRATOR_NETWORK2:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -49,7 +51,7 @@ usage () {
     echo "                  [-E environment] [-Z size]"
     echo "                  [-A application ] [-V version]"
     echo "                  [-k key]"
-    echo "                  [-P network ]"
+    echo "                  [-n network] [-N network ]"
     echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
@@ -64,7 +66,8 @@ usage () {
     echo "  -A application  Application Name (default: $application)"
     echo "  -V version      Application Version (default: $application_version)"
     echo "  -k key          Key (default: $key)"
-    echo "  -P network      Private User Network (default: $private_user_network)"
+    echo "  -n network      Private User Network (default: $private_user_network)"
+    echo "  -N network      Private Administrator Network (default: $private_administrator_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -149,9 +152,9 @@ next() {
 
 
 #  3. Parse command line options
-#     - Note, using options 1-9 as hidden options to set additional network ranges
+#     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvoO:C:S:E:Z:A:V:k:P:7:8:9:r:a:u:? arg; do
+while getopts IsfvoO:C:S:E:Z:A:V:k:n:5:6:N:7:8:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -166,10 +169,12 @@ while getopts IsfvoO:C:S:E:Z:A:V:k:P:7:8:9:r:a:u:? arg; do
     A)  application="$OPTARG";;
     V)  application_version="$OPTARG";;
     k)  key="$OPTARG";;
-    P)  private_user_network="$OPTARG";;
-    7)  private_user_network1="$OPTARG";;
-    8)  private_user_network2="$OPTARG";;
-    9)  private_user_network3="$OPTARG";;
+    n)  private_user_network="$OPTARG";;
+    5)  private_user_network1="$OPTARG";;
+    6)  private_user_network2="$OPTARG";;
+    N)  private_administrator_network="$OPTARG";;
+    7)  private_administrator_network1="$OPTARG";;
+    8)  private_administrator_network2="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -224,7 +229,7 @@ if [ -z $environment ]; then
 else
     case $environment in
       Production)
-        instance_os=AMZN
+        instance_os=RHEL
         use_static_address=true
         use_filesystem_monitoring=true
         use_log_monitoring=true
@@ -240,18 +245,18 @@ else
         on_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         off_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       Testing)
-        instance_os=RHEL
-        use_static_address=true
+        instance_os=AMZN
+        use_static_address=false
         use_filesystem_monitoring=false
-        use_log_monitoring=false
+        use_log_monitoring=true
         use_schedule=false
         on_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         off_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       Development)
-        instance_os=RHEL
-        use_static_address=true
+        instance_os=AMZN
+        use_static_address=fakse
         use_filesystem_monitoring=false
-        use_log_monitoring=false
+        use_log_monitoring=true
         use_schedule=false
         on_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         off_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
@@ -300,7 +305,7 @@ fi
 if [ -z $application_version ]; then
     echo "-V version missing!"
     echo "Could not automatically determine version, and it was not specified as a parameter"
-    exit 22
+    exit 24
 fi
 
 if [ -z $key ]; then
@@ -310,9 +315,15 @@ if [ -z $key ]; then
 fi
 
 if [ -z $private_user_network ]; then
-    echo "-P network missing!"
+    echo "-n network missing!"
     echo "Could not automatically determine private user network, and it was not specified as a parameter"
-    exit 36
+    exit 44
+fi
+
+if [ -z $private_administrator_network ]; then
+    echo "-N network missing!"
+    echo "Could not automatically determine private administrator network, and it was not specified as a parameter"
+    exit 46
 fi
 
 if [ -z $region ]; then
@@ -326,7 +337,7 @@ else
       us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
         s3_domain=s3-$region.amazonaws.com;;
       *)
-        echo "-r $region invalid: Must be a valid region"
+        echo "-r $region invalid: Please specify a valid region"
         exit 51;;
     esac
 fi
@@ -508,7 +519,9 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                              ParameterKey=PrivateUserNetwork,ParameterValue=$private_user_network \\
                                              ParameterKey=PrivateUserNetwork1,ParameterValue=$private_user_network1 \\
                                              ParameterKey=PrivateUserNetwork2,ParameterValue=$private_user_network2 \\
-                                             ParameterKey=PrivateUserNetwork3,ParameterValue=$private_user_network3 \\
+                                             ParameterKey=PrivateAdministratorNetwork,ParameterValue=$private_administrator_network \\
+                                             ParameterKey=PrivateAdministratorNetwork1,ParameterValue=$private_administrator_network1 \\
+                                             ParameterKey=PrivateAdministratorNetwork2,ParameterValue=$private_administrator_network2 \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
