Major refactoring to add ActiveDirectory for private DNS, change how network parameters are passed, and more (#11)
* refactor CIDR Networks Parameter logic

* refactor CIDR Networks Parameter logic

* refactor CIDR Networks Parameter logic

* add scripts bucket

* add GetSpecificWindowsImageId Lambda function

* add default and specific date logic to AMI lookup lambda functions

* initial working version of ActiveDirectory Utility

* changed public domain env var to include the word public

* adjust env vars related to Domains to prepare for private ActiveDirectory domains

* fix OSDate to be numeric only

* prevent line endings from switching formats

* update OSDate format to be numeric-only

* remove DHCPOptions and it's association from VPC Templates

* fix typo in env var name

* increase ActiveDirectory Utility timeouts

* increase maximum domain length

* add Identity subnets to Build VPC

* fix a couple typos in help

* add config line to write hostname to /etc/hostname

* switch driver scripts to run non-interactively by default

* switch driver scripts to run non-interactively by default

* switch driver scripts to run non-interactively by default

* switch driver scripts to run non-interactively by default

* switch driver scripts to run non-interactively by default

* change flags used for some options to prevent conflict

* switch driver scripts to run non-interactively by default

* switch driver scripts to run non-interactively by default

* added more application networks; removed old network variables

* reduce size of ComponentCode due to NetBIOS name limit of 15

* move domain logic to VPC template, support public/private/NetBIOS domains, and addition of ActiveDirectory

* ActiveDirectory refinements

* OpenVPN refinements; integrate with ActiveDirectory

* LinuxBastions refinements; integrate with ActiveDirectory

* Add WindowsBastions with RDGW integrated with ActiveDirectory

* WebSphereMQ refinements

* RabbitMQ refinements

* MongoDB refinements

* Octopus Deploy refinements; integration with ActiveDirectory

* Engine Web refinements; integration with ActiveDirectory

* fix a few missed changes

* Engine Calculation refinements; integration with ActiveDirectory

* Engine DataStaging refinements; integration with ActiveDirectory

* Fix a couple of spacing errors

* Engine Publishing refinements; integration with ActiveDirectory; adjustments to pre-requisites check

* Engine Monitoring refinements; integration with ActiveDirectory; adjustments to pre-requisites check

* Add missing stack dependencies; adjustments to pre-requisites check

* Adjustments to stack dependencies and pre-requisite checks

* Adjustments to pre-requisite checks

* Adjustments to pre-requisite checks

* Adjustments to pre-requisite checks

* Adjustments to pre-requisite checks

* Adjustments to pre-requisite checks

* Adjustments to pre-requisite checks

* Adjustments to pre-requisite checks

* CIDR fix, Adjustments to pre-requisite checks

* CIDR fix, Adjustments to pre-requisite checks

* CIDR fix, Adjustments to pre-requisite checks

* CIDR fix, Adjustments to pre-requisite checks

* adjustments to sequence scripts to add ActiveDirectory, adjust interactive flag meaning, many other changes

* remove Integration stack related files, no longer used

diff --git a/application/bin/application-update-engine-web-stack b/application/bin/application-update-engine-web-stack
--- a/application/bin/application-update-engine-web-stack
+++ b/application/bin/application-update-engine-web-stack
@@ -2,9 +2,6 @@
 #
 # This script updates the Application Engine Component Web Stack in an Environment Account.
 #
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
-#
 
 #  1. Initalize Environment
 
@@ -20,7 +17,7 @@ next_default=5
 update_default=15
 update_attempts=40
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
@@ -35,15 +32,11 @@ application=${APPLICATION_NAME:-Engine}
 application_domain=${APPLICATION_DOMAIN:-engine}
 application_version=${APPLICATION_VERSION:-1.0.0}
 component=${COMPONENT_NAME:-Web}
-public_user_network=${PUBLIC_USER_NETWORK:-0.0.0.0/0}
-public_user_network1=${PUBLIC_USER_NETWORK1:-}
-public_user_network2=${PUBLIC_USER_NETWORK2:-}
-private_user_network=${PRIVATE_USER_NETWORK:-10.0.0.0/16}
-private_user_network1=${PRIVATE_USER_NETWORK1:-}
-private_user_network2=${PRIVATE_USER_NETWORK2:-}
-private_administrator_network=${PRIVATE_ADMINISTRATOR_NETWORK:-10.0.0.0/16}
-private_administrator_network1=${PRIVATE_ADMINISTRATOR_NETWORK1:-}
-private_administrator_network2=${PRIVATE_ADMINISTRATOR_NETWORK2:-}
+user_networks=${ENGINE_USER_NETWORKS:-NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
+administrator_networks=${ENGINE_ADMINISTRATOR_NETWORKS:-NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
+integration_networks=${ENGINE_INTEGRATION_NETWORKS:-NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
+domainadmin_user=${DOMAINADMIN_USER:-StackAdmin}
+domainadmin_password=${DOMAINADMIN_PASSWORD:-} # This should have no default value
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -53,15 +46,15 @@ key=${AWS_KEY_NAME:-user}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m] [-o]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m] [-o]"
     echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment] [-T type] [-Z zones]"
     echo "                  [-A application] [-D domain] [-V version]"
     echo "                  [-c component]"
-    echo "                  [-p network]"
-    echo "                  [-n network] [-N network]"
+    echo "                  [-n networks] [-N networks] [-I networks]"
+    echo "                  [-U user] [-P password]"
     echo "                  [-r region] [-a account] [-u user] [-k key]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
@@ -77,9 +70,11 @@ usage () {
     echo "  -D domain       Application Domain (default: $application_domain)"
     echo "  -V version      Application Version (default: $application_version)"
     echo "  -c component    Component Name (default: $component)"
-    echo "  -p network      Public User Network (default: $public_user_network)"
-    echo "  -n network      Private User Network (default: $private_user_network)"
-    echo "  -N network      Private Administrator Network (default: $private_administrator_network)"
+    echo "  -n networks     User Networks (default: $user_networks)"
+    echo "  -N networks     Administrator Networks (default: $administrator_networks)"
+    echo "  -I networks     Integration Networks (default: $integration_networks)"
+    echo "  -U user         DomainAdmin User (default: $domainadmin_user)"
+    echo "  -P password     DomainAdmin Password (default: $domainadmin_password)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -165,11 +160,10 @@ next() {
 
 
 #  3. Parse command line options
-#     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvmoO:C:S:E:T:Z:A:V:c:n:5:6:N:7:8:r:a:u:k:? arg; do
+while getopts isfvmoO:C:S:E:T:Z:A:D:V:c:n:N:I:U:P:r:a:u:k:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
@@ -185,15 +179,11 @@ while getopts IsfvmoO:C:S:E:T:Z:A:V:c:n:5:6:N:7:8:r:a:u:k:? arg; do
     D)  application_domain="$OPTARG";;
     V)  application_version="$OPTARG";;
     c)  component="$OPTARG";;
-    p)  public_user_network="$OPTARG";;
-    1)  public_user_network1="$OPTARG";;
-    2)  public_user_network2="$OPTARG";;
-    n)  private_user_network="$OPTARG";;
-    5)  private_user_network1="$OPTARG";;
-    6)  private_user_network2="$OPTARG";;
-    N)  private_administrator_network="$OPTARG";;
-    7)  private_administrator_network1="$OPTARG";;
-    8)  private_administrator_network2="$OPTARG";;
+    n)  user_networks="$OPTARG";;
+    N)  administrator_networks="$OPTARG";;
+    I)  integration_networks="$OPTARG";;
+    U)  domainadmin_user="$OPTARG";;
+    P)  domainadmin_password="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -251,24 +241,28 @@ else
     case $environment in
       Production)
         os_name="Windows Server 2012 R2"
+        os_date="20170614"
         use_static_address=false
         log_retention=30
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Staging)
         os_name="Windows Server 2012 R2"
+        os_date="20170614"
         use_static_address=false
         log_retention=7
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Testing)
         os_name="Windows Server 2012 R2"
+        os_date="20170614"
         use_static_address=false
-        log_retention=7
+        log_retention=3
         schedule="13:00-2:00";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       Development)
         os_name="Windows Server 2012 R2"
+        os_date="20170614"
         use_static_address=false
-        log_retention=14
-        schedule="";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
+        log_retention=3
+        schedule="13:00-2:00";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       *)
         echo "-E $environment invalid! Must be Production, Staging, Testing or Development"
         exit 21;;
@@ -332,33 +326,53 @@ fi
 if [ -z $component ]; then
     echo "-c component missing!"
     echo "Could not automatically determine component, and it was not specified as a parameter"
-    exit 36
+    exit 38
 else
     case $component in
       Web)
         ;;
       *)
         echo "-c $component invalid! Must be Web"
-        exit 37;;
+        exit 39;;
     esac
 fi
 
-if [ -z $public_user_network ]; then
-    echo "-p network missing!"
-    echo "Could not automatically determine public user network, and it was not specified as a parameter"
+if [ -z $user_networks ]; then
+    echo "-n networks missing!"
+    echo "Could not automatically determine user networks, and it was not specified as a parameter"
     exit 40
 fi
 
-if [ -z $private_user_network ]; then
-    echo "-n network missing!"
-    echo "Could not automatically determine private user network, and it was not specified as a parameter"
+if [ -z $administrator_networks ]; then
+    echo "-N networks missing!"
+    echo "Could not automatically determine administrator networks, and it was not specified as a parameter"
+    exit 42
+fi
+
+if [ -z $integration_networks ]; then
+    echo "-I networks missing!"
+    echo "Could not automatically determine integration networks, and it was not specified as a parameter"
     exit 44
 fi
 
-if [ -z $private_administrator_network ]; then
-    echo "-N network missing!"
-    echo "Could not automatically determine private administrator network, and it was not specified as a parameter"
+if [ -z $domainadmin_user ]; then
+    echo "-U user missing!"
+    echo "Could not automatically determine DomainAdmin user, and it was not specified as a parameter"
     exit 46
+else
+    case $domainadmin_user in
+      StackAdmin)
+        ;;
+      *)
+        echo "-U $domainadmin_user invalid! Must be StackAdmin"
+        exit 47;;
+    esac
+fi
+
+if [ -z $domainadmin_password ]; then
+    echo "-P password missing!"
+    echo "Could not automatically determine DomainAdmin password, and it was not specified as a parameter"
+    exit 48
 fi
 
 if [ -z $region ]; then
@@ -403,24 +417,39 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 58
 fi
 
+echo -n "Confirming Stack pre-requisites "
+
 if ! aws cloudformation describe-stacks --stack-name $environment-$application-$component \
                                         --profile $profile --region $region --output text &> /dev/null; then
+    echo
     echo "Unable to update - $environment-$application-$component Stack does not exist!"
-    exit 80
+    exit 98
+else
+    echo -n "."
 fi
+echo " Done"
+sleep 1
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
 template_folder=application
 
+scripts_bucket=${AWS_SCRIPTS_BUCKET:-scripts-$region-$account}
+shared_script_folder=Windows
+script_folder=Engine
+
 products_bucket=${AWS_PRODUCTS_BUCKET:-products-$region-$account}
+shared_product_folder=Windows
 product_folder=Engine
+atom_product_object="AtomSetup-x64.msi"
 product_object=""
 
 configurations_bucket=${AWS_CONFIGURATIONS_BUCKET:-configurations-$region-$account}
+shared_configuration_folder=Windows
 configuration_folder=Engine
 configuration_object=""
 
 applications_bucket=${AWS_APPLICATIONS_BUCKET:-applications-$region-$account}
+shared_application_folder=Windows
 application_folder=Engine
 application_object=""
 
@@ -509,7 +538,14 @@ read -r -d '' statement << EOS
 aws cloudformation update-stack --stack-name $environment-$application-$component \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=VPNStackName,ParameterValue=$environment-OpenVPNAS \\
+                                --parameters ParameterKey=EngineMonitoringStackName,ParameterValue=$environment-Engine-Monitoring \\
+                                             ParameterKey=FederatedSecuritySecurityServerStackName,ParameterValue= \\
+                                             ParameterKey=MongoDBStackName,ParameterValue=$environment-MongoDB \\
+                                             ParameterKey=RabbitMQStackName,ParameterValue=$environment-RabbitMQ \\
+                                             ParameterKey=WebSphereMQStackName,ParameterValue=$environment-WebSphereMQ \\
+                                             ParameterKey=OctopusDeployStackName,ParameterValue=$environment-Octopus-Deploy \\
+                                             ParameterKey=VPNStackName,ParameterValue=$environment-OpenVPNAS \\
+                                             ParameterKey=ActiveDirectoryStackName,ParameterValue=$environment-ActiveDirectory \\
                                              ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
                                              ParameterKey=CustomIdentifierFunctionsStackName,ParameterValue=CustomIdentifierFunctions \\
                                              ParameterKey=StandardCIDRFunctionsStackName,ParameterValue=StandardCIDRFunctions \\
@@ -522,10 +558,17 @@ aws cloudformation update-stack --stack-name $environment-$application-$componen
                                              ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
                                              ParameterKey=EnvironmentZones,ParameterValue=$environment_zones \\
                                              ParameterKey=OSName,ParameterValue="$os_name" \\
+                                             ParameterKey=OSDate,ParameterValue="$os_date" \\
+                                             ParameterKey=SharedScriptFolder,ParameterValue=$shared_script_folder \\
+                                             ParameterKey=ScriptFolder,ParameterValue=$script_folder \\
+                                             ParameterKey=SharedProductFolder,ParameterValue=$shared_product_folder \\
                                              ParameterKey=ProductFolder,ParameterValue=$product_folder \\
+                                             ParameterKey=AtomProductObject,ParameterValue=$atom_product_object \\
                                              ParameterKey=ProductObject,ParameterValue=$product_object \\
+                                             ParameterKey=SharedConfigurationFolder,ParameterValue=$shared_configuration_folder \\
                                              ParameterKey=ConfigurationFolder,ParameterValue=$configuration_folder \\
                                              ParameterKey=ConfigurationObject,ParameterValue=$configuration_object \\
+                                             ParameterKey=SharedApplicationFolder,ParameterValue=$shared_application_folder \\
                                              ParameterKey=ApplicationFolder,ParameterValue=$application_folder \\
                                              ParameterKey=ApplicationObject,ParameterValue=$application_object \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
@@ -535,15 +578,11 @@ aws cloudformation update-stack --stack-name $environment-$application-$componen
                                              ParameterKey=UseStaticAddress,ParameterValue=$use_static_address \\
                                              ParameterKey=LogRetention,ParameterValue=$log_retention \\
                                              ParameterKey=Schedule,ParameterValue=$schedule \\
-                                             ParameterKey=PublicUserNetwork,ParameterValue=$public_user_network \\
-                                             ParameterKey=PublicUserNetwork1,ParameterValue=$public_user_network1 \\
-                                             ParameterKey=PublicUserNetwork2,ParameterValue=$public_user_network2 \\
-                                             ParameterKey=PrivateUserNetwork,ParameterValue=$private_user_network \\
-                                             ParameterKey=PrivateUserNetwork1,ParameterValue=$private_user_network1 \\
-                                             ParameterKey=PrivateUserNetwork2,ParameterValue=$private_user_network2 \\
-                                             ParameterKey=PrivateAdministratorNetwork,ParameterValue=$private_administrator_network \\
-                                             ParameterKey=PrivateAdministratorNetwork1,ParameterValue=$private_administrator_network1 \\
-                                             ParameterKey=PrivateAdministratorNetwork2,ParameterValue=$private_administrator_network2 \\
+                                             ParameterKey=UserNetworks,ParameterValue=\"$user_networks\" \\
+                                             ParameterKey=AdministratorNetworks,ParameterValue=\"$administrator_networks\" \\
+                                             ParameterKey=IntegrationNetworks,ParameterValue=\"$integration_networks\" \\
+                                             ParameterKey=DomainAdminUser,ParameterValue="$domainadmin_user" \\
+                                             ParameterKey=DomainAdminPassword,ParameterValue="$domainadmin_password" \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
diff --git a/application/bin/application-update-webspheremq-stack b/application/bin/application-update-webspheremq-stack
--- a/application/bin/application-update-webspheremq-stack
+++ b/application/bin/application-update-webspheremq-stack
@@ -2,9 +2,6 @@
 #
 # This script updates the Application WebSphereMQ Stack in an Environment Account.
 #
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
-#
 
 #  1. Initalize Environment
 
@@ -20,7 +17,7 @@ next_default=5
 update_default=15
 update_attempts=40
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
@@ -32,12 +29,8 @@ environment=${ENVIRONMENT_NAME:-Production}
 environment_type=${ENVIRONMENT_TYPE:-large}
 application=${APPLICATION_NAME:-WebSphereMQ}
 application_version=${APPLICATION_VERSION:-1.0.0}
-private_user_network=${PRIVATE_USER_NETWORK:-10.0.0.0/16}
-private_user_network1=${PRIVATE_USER_NETWORK1:-}
-private_user_network2=${PRIVATE_USER_NETWORK2:-}
-private_administrator_network=${PRIVATE_ADMINISTRATOR_NETWORK:-10.0.0.0/16}
-private_administrator_network1=${PRIVATE_ADMINISTRATOR_NETWORK1:-}
-private_administrator_network2=${PRIVATE_ADMINISTRATOR_NETWORK2:-}
+administrator_networks=${WEBSPHEREMQ_ADMINISTRATOR_NETWORKS:-NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
+integration_networks=${WEBSPHEREMQ_INTEGRATION_NETWORKS:-NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -47,13 +40,13 @@ key=${AWS_KEY_NAME:-user}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m] [-o]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m] [-o]"
     echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment] [-T type]"
     echo "                  [-A application] [-V version]"
-    echo "                  [-n network] [-N network]"
+    echo "                  [-N networks] [-I networks]"
     echo "                  [-r region] [-a account] [-u user] [-k key]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
@@ -66,8 +59,8 @@ usage () {
     echo "  -T type         Environment Type (default: $environment_type)"
     echo "  -A application  Application Name (default: $application)"
     echo "  -V version      Application Version (default: $application_version)"
-    echo "  -n network      Private User Network (default: $private_user_network)"
-    echo "  -N network      Private Administrator Network (default: $private_administrator_network)"
+    echo "  -N networks     Administrator Networks (default: $administrator_networks)"
+    echo "  -I networks     Integration Networks (default: $integration_networks)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -153,11 +146,10 @@ next() {
 
 
 #  3. Parse command line options
-#     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvmoO:C:S:E:T:A:V:n:5:6:N:7:8:r:a:u:k:? arg; do
+while getopts isfvmoO:C:S:E:T:A:V:N:I:r:a:u:k:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
@@ -170,12 +162,8 @@ while getopts IsfvmoO:C:S:E:T:A:V:n:5:6:N:7:8:r:a:u:k:? arg; do
     T)  environment_type="$OPTARG";;
     A)  application="$OPTARG";;
     V)  application_version="$OPTARG";;
-    n)  private_user_network="$OPTARG";;
-    5)  private_user_network1="$OPTARG";;
-    6)  private_user_network2="$OPTARG";;
-    N)  private_administrator_network="$OPTARG";;
-    7)  private_administrator_network1="$OPTARG";;
-    8)  private_administrator_network2="$OPTARG";;
+    N)  administrator_networks="$OPTARG";;
+    I)  integration_networks="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -233,30 +221,35 @@ else
     case $environment in
       Production)
         os_name="RHEL 7.3"
+        os_date="20161026"
         use_static_address=false
         use_filesystem_monitoring=true
         log_retention=30
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Staging)
         os_name="RHEL 7.3"
+        os_date="20161026"
         use_static_address=false
         use_filesystem_monitoring=true
         log_retention=7
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Testing)
         os_name="RHEL 7.3"
+        os_date="20161026"
         use_static_address=false
         use_filesystem_monitoring=false
         log_retention=0
         schedule="13:00-2:00";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       Development)
         os_name="RHEL 7.3"
+        os_date="20161026"
         use_static_address=false
         use_filesystem_monitoring=false
         log_retention=0
         schedule="";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       Core)
         os_name="RHEL 7.3"
+        os_date="20161026"
         use_static_address=false
         use_filesystem_monitoring=true
         log_retention=14
@@ -301,17 +294,16 @@ if [ -z $application_version ]; then
     exit 34
 fi
 
-
-if [ -z $private_user_network ]; then
-    echo "-n network missing!"
-    echo "Could not automatically determine private user network, and it was not specified as a parameter"
-    exit 44
+if [ -z $administrator_networks ]; then
+    echo "-N networks missing!"
+    echo "Could not automatically determine administrator networks, and it was not specified as a parameter"
+    exit 42
 fi
 
-if [ -z $private_administrator_network ]; then
-    echo "-N network missing!"
-    echo "Could not automatically determine private administrator network, and it was not specified as a parameter"
-    exit 46
+if [ -z $integration_networks ]; then
+    echo "-I networks missing!"
+    echo "Could not automatically determine integration networks, and it was not specified as a parameter"
+    exit 44
 fi
 
 if [ -z $region ]; then
@@ -356,22 +348,36 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 58
 fi
 
+echo -n "Confirming Stack pre-requisites "
+
 if ! aws cloudformation describe-stacks --stack-name $environment-$application \
                                         --profile $profile --region $region --output text &> /dev/null; then
+    echo
     echo "Unable to update - $environment-$application Stack does not exist!"
-    exit 80
+    exit 98
+else
+    echo -n "."
 fi
+echo " Done"
+sleep 1
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
 template_folder=application
 
+scripts_bucket=${AWS_SCRIPTS_BUCKET:-scripts-$region-$account}
+shared_script_folder=Linux
+script_folder=WebSphereMQ
+
 products_bucket=${AWS_PRODUCTS_BUCKET:-products-$region-$account}
+shared_product_folder=Linux
 product_folder=WebSphereMQ
-product_object=WS_MQ_V8.0.0.4_LINUX_ON_X86_64_IM.tar.gz
+webspheremq_product_object=WS_MQ_V8.0.0.4_LINUX_ON_X86_64_IM.tar.gz
 
 configurations_bucket=${AWS_CONFIGURATIONS_BUCKET:-configurations-$region-$account}
+shared_configuration_folder=Linux
 configuration_folder=WebSphereMQ
-configuration_object=$environment-WebSphereMQ-etc-wmq.tgz
+#webspheremq_configuration_object=$environment-WebSphereMQ-etc-wmq.tgz
+webspheremq_configuration_object=""
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -470,21 +476,22 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
                                              ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
                                              ParameterKey=OSName,ParameterValue="$os_name" \\
+                                             ParameterKey=OSDate,ParameterValue="$os_date" \\
+                                             ParameterKey=SharedScriptFolder,ParameterValue=$shared_script_folder \\
+                                             ParameterKey=ScriptFolder,ParameterValue=$script_folder \\
+                                             ParameterKey=SharedProductFolder,ParameterValue=$shared_product_folder \\
                                              ParameterKey=ProductFolder,ParameterValue=$product_folder \\
-                                             ParameterKey=ProductObject,ParameterValue=$product_object \\
+                                             ParameterKey=WebSphereMQProductObject,ParameterValue=$webspheremq_product_object \\
+                                             ParameterKey=SharedConfigurationFolder,ParameterValue=$shared_configuration_folder \\
                                              ParameterKey=ConfigurationFolder,ParameterValue=$configuration_folder \\
-                                             ParameterKey=ConfigurationObject,ParameterValue=$configuration_object \\
+                                             ParameterKey=WebSphereMQConfigurationObject,ParameterValue=$webspheremq_configuration_object \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
                                              ParameterKey=UseStaticAddress,ParameterValue=$use_static_address \\
                                              ParameterKey=UseFileSystemMonitoring,ParameterValue=$use_filesystem_monitoring \\
                                              ParameterKey=LogRetention,ParameterValue=$log_retention \\
                                              ParameterKey=Schedule,ParameterValue=$schedule \\
-                                             ParameterKey=PrivateUserNetwork,ParameterValue=$private_user_network \\
-                                             ParameterKey=PrivateUserNetwork1,ParameterValue=$private_user_network1 \\
-                                             ParameterKey=PrivateUserNetwork2,ParameterValue=$private_user_network2 \\
-                                             ParameterKey=PrivateAdministratorNetwork,ParameterValue=$private_administrator_network \\
-                                             ParameterKey=PrivateAdministratorNetwork1,ParameterValue=$private_administrator_network1 \\
-                                             ParameterKey=PrivateAdministratorNetwork2,ParameterValue=$private_administrator_network2 \\
+                                             ParameterKey=AdministratorNetworks,ParameterValue=\"$administrator_networks\" \\
+                                             ParameterKey=IntegrationNetworks,ParameterValue=\"$integration_networks\" \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
diff --git a/bootstrap/bin/bootstrap-delete-linuxbastion-stack b/bootstrap/bin/bootstrap-delete-linuxbastion-stack
--- a/bootstrap/bin/bootstrap-delete-linuxbastion-stack
+++ b/bootstrap/bin/bootstrap-delete-linuxbastion-stack
@@ -8,9 +8,6 @@
 # This Bootstrap Instance should be destroyed when no longer needed, as it will not exist within
 # the formal VPC infrastructure, and may present a security risk.
 #
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
-#
 
 #  1. Initalize Environment
 
@@ -26,7 +23,7 @@ next_default=5
 delete_default=15
 delete_attempts=40
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
@@ -40,10 +37,10 @@ user=bootstrapadministrator
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m]"
     echo "                  [-U utility]"
     echo "                  [-a account] [-u user]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
@@ -133,9 +130,9 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvmU:a:u:? arg; do
+while getopts isfvmU:a:u:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
@@ -160,10 +157,10 @@ if [ -z $utility ]; then
     exit 30
 else
     case $utility in
-      LinuxBastion)
+      LinuxBastion*)
         ;;
       *)
-        echo "-U $utility invalid! Must be LinuxBastion"
+        echo "-U $utility invalid! Must begin with LinuxBastion"
         exit 31;;
     esac
 fi
@@ -189,6 +186,19 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Expected to find: [profile $profile] in ~/.aws/config"
     exit 58
 fi
+
+echo -n "Confirming Stack pre-requisites "
+
+if ! aws cloudformation describe-stacks --stack-name $environment-$utility \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo
+    echo "Unable to delete - $environment-$utility Stack does not exist!"
+    exit 99
+else
+    echo -n "."
+fi
+echo " Done"
+sleep 1
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
diff --git a/common/bin/common-update-hostedzone-stack b/common/bin/common-update-hostedzone-stack
--- a/common/bin/common-update-hostedzone-stack
+++ b/common/bin/common-update-hostedzone-stack
@@ -2,9 +2,6 @@
 #
 # This script updates the Environment HostedZone Stack in an Environment or Core Account.
 #
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
-#
 
 #  1. Initalize Environment
 
@@ -20,7 +17,7 @@ next_default=5
 update_default=15
 update_attempts=40
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
@@ -29,7 +26,7 @@ owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
-environment_domain=${ENVIRONMENT_DOMAIN:-us-west-2.tvl.iropshub.com}
+environment_public_domain=${ENVIRONMENT_PUBLIC_DOMAIN:-us-west-2.tvl.iropshub.com}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -38,11 +35,11 @@ user=${AWS_USER_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m] [-o]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m] [-o]"
     echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment] [-D domain]"
     echo "                  [-r region] [-a account] [-u user]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
@@ -52,7 +49,7 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -D domain       Environment Domain (default: $environment_domain)"
+    echo "  -D domain       Environment Public Domain (default: $environment_public_domain)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -138,9 +135,9 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvmoO:C:S:E:D:r:a:u:? arg; do
+while getopts isfvmoO:C:S:E:D:r:a:u:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
@@ -150,7 +147,7 @@ while getopts IsfvmoO:C:S:E:D:r:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    D)  environment_domain="$OPTARG";;
+    D)  environment_public_domain="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -223,9 +220,9 @@ else
     esac
 fi
 
-if [ -z $environment_domain ]; then
+if [ -z $environment_public_domain ]; then
     echo "-D domain missing!"
-    echo "Could not automatically determine domain, and it was not specified as a parameter"
+    echo "Could not automatically determine public domain, and it was not specified as a parameter"
     exit 32
 fi
 
@@ -265,14 +262,21 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 58
 fi
 
+echo -n "Confirming Stack pre-requisites "
+
 if ! aws cloudformation describe-stacks --stack-name $environment-HostedZone \
                                         --profile $profile --region $region --output text &> /dev/null; then
+    echo
     echo "Unable to update - $environment-HostedZone Stack does not exist!"
-    exit 80
+    exit 98
+else
+    echo -n "."
 fi
+echo " Done"
+sleep 1
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-template_folder=environment
+template_folder=common
 
 if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
     unset templates_bucket
@@ -371,7 +375,7 @@ aws cloudformation update-stack --stack-name $environment-HostedZone \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
                                 --parameters ParameterKey=Name,ParameterValue=$environment \\
-                                             ParameterKey=Domain,ParameterValue=$environment_domain \\
+                                             ParameterKey=Domain,ParameterValue=$environment_public_domain \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
diff --git a/core/bin/core-create-vpc-stack b/core/bin/core-create-vpc-stack
--- a/core/bin/core-create-vpc-stack
+++ b/core/bin/core-create-vpc-stack
@@ -2,9 +2,6 @@
 #
 # This script creates the Core VPC Stack in the Core Account.
 #
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
-#
 
 #  1. Initalize Environment
 
@@ -20,7 +17,7 @@ next_default=5
 create_default=15
 create_attempts=40
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
@@ -29,6 +26,9 @@ company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${CORE_NAME:-Core}
 environment_network=${CORE_NETWORK:-172.21.56.0/22}
+environment_public_domain=${CORE_PUBLIC_DOMAIN:-c.us-west-2.tvl.iropshub.com}
+environment_private_domain=${CORE_PRIVATE_DOMAIN:-iropscmc.travel.svcs.entsvcs.com}
+environment_netbios_domain=${CORE_NETBIOS_DOMAIN:-iropscmc}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -37,12 +37,12 @@ user=${AWS_USER_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m]"
     echo "                  [-O owner] [-C company] [-S system]"
-    echo "                  [-E environment]"
-    echo "                  [-N network]"
+    echo "                  [-E environment] [-N network]"
+    echo "                  [-D domain] [-d domain] [-b domain]"
     echo "                  [-r region] [-a account] [-u user]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
@@ -52,6 +52,9 @@ usage () {
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
     echo "  -N network      Environment Network (default: $environment_network)"
+    echo "  -D domain       Environment Public Domain (default: $environment_public_domain)"
+    echo "  -d domain       Environment Private Domain (default: $environment_private_domain)"
+    echo "  -b domain       Environment NetBIOS Domain (default: $environment_netbios_domain)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -137,9 +140,9 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvmO:C:S:E:N:r:a:u:? arg; do
+while getopts isfvmO:C:S:E:N:D:d:b:r:a:u:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
@@ -149,6 +152,9 @@ while getopts IsfvmO:C:S:E:N:r:a:u:? arg; do
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
     N)  environment_network="$OPTARG";;
+    D)  environment_public_domain="$OPTARG";;
+    d)  environment_private_domain="$OPTARG";;
+    b)  environment_netbios_domain="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -204,6 +210,11 @@ if [ -z $environment ]; then
 else
     case $environment in
       Core)
+        addresses_per_subnet=32
+        subnets_per_availability_zone=16
+        availability_zones_per_vpc=2
+        use_public_hostedzone=true
+        use_private_hostedzone=false
         use_multi_zone_nat_gateways=false
         use_vpn_gateway=true;;
       *)
@@ -216,6 +227,24 @@ if [ -z $environment_network ]; then
     echo "-N network missing!"
     echo "Could not automatically determine environment network, and it was not specified as a parameter"
     exit 22
+fi
+
+if [ -z $environment_public_domain ]; then
+    echo "-D domain missing!"
+    echo "Could not automatically determine public domain, and it was not specified as a parameter"
+    exit 24
+fi
+
+if [ -z $environment_private_domain ]; then
+    echo "-d domain missing!"
+    echo "Could not automatically determine private domain, and it was not specified as a parameter"
+    exit 26
+fi
+
+if [ -z $environment_netbios_domain ]; then
+    echo "-b domain missing!"
+    echo "Could not automatically determine NetBIOS domain, and it was not specified as a parameter"
+    exit 28
 fi
 
 if [ -z $region ]; then
@@ -252,12 +281,6 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
     exit 58
-fi
-
-if ! aws cloudformation describe-stacks --stack-name $environment-HostedZone \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo "Stack dependency missing - $environment-HostedZone Stack does not exist!"
-    exit 60
 fi
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
@@ -356,9 +379,16 @@ read -r -d '' statement << EOS
 aws cloudformation create-stack --stack-name $environment-VPC \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=HostedZoneStackName,ParameterValue=$environment-HostedZone \\
-                                             ParameterKey=Name,ParameterValue=$environment \\
+                                --parameters ParameterKey=Name,ParameterValue=$environment \\
                                              ParameterKey=Network,ParameterValue=$environment_network \\
+                                             ParameterKey=AddressesPerSubnet,ParameterValue=$addresses_per_subnet \\
+                                             ParameterKey=SubnetsPerAvailabilityZone,ParameterValue=$subnets_per_availability_zone \\
+                                             ParameterKey=AvailabilityZonesPerVPC,ParameterValue=$availability_zones_per_vpc \\
+                                             ParameterKey=PublicDomain,ParameterValue=$environment_public_domain \\
+                                             ParameterKey=PrivateDomain,ParameterValue=$environment_private_domain \\
+                                             ParameterKey=NetBIOSDomain,ParameterValue=$environment_netbios_domain \\
+                                             ParameterKey=UsePublicHostedZone,ParameterValue=$use_public_hostedzone \\
+                                             ParameterKey=UsePrivateHostedZone,ParameterValue=$use_private_hostedzone \\
                                              ParameterKey=UseMultiZoneNatGateways,ParameterValue=$use_multi_zone_nat_gateways \\
                                              ParameterKey=UseVPNGateway,ParameterValue=$use_vpn_gateway \\
                                 --tags Key=Owner,Value=$owner \\
diff --git a/identity/bin/identity-update-vpc-stack b/identity/bin/identity-update-vpc-stack
--- a/identity/bin/identity-update-vpc-stack
+++ b/identity/bin/identity-update-vpc-stack
@@ -2,9 +2,6 @@
 #
 # This script updates the Identity VPC Stack in the Identity Account.
 #
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
-#
 
 #  1. Initalize Environment
 
@@ -20,7 +17,7 @@ next_default=5
 update_default=15
 update_attempts=40
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
@@ -30,6 +27,9 @@ company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${IDENTITY_NAME:-Identity}
 environment_network=${IDENTITY_NETWORK:-172.21.62.0/23}
+environment_public_domain=${IDENTITY_PUBLIC_DOMAIN:-i.us-west-2.tvl.iropshub.com}
+environment_private_domain=${IDENTITY_PRIVATE_DOMAIN:-iropscmi.travel.svcs.entsvcs.com}
+environment_netbios_domain=${IDENTITY_NETBIOS_DOMAIN:-iropscmi}
 region=us-east-1 # This should run only in us-east-1
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -38,12 +38,12 @@ user=${AWS_USER_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m] [-o]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m] [-o]"
     echo "                  [-O owner] [-C company] [-S system]"
-    echo "                  [-E environment]"
-    echo "                  [-N network]"
+    echo "                  [-E environment] [-N network]"
+    echo "                  [-D domain] [-d domain] [-b domain]"
     echo "                  [-a account] [-u user]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
@@ -54,6 +54,9 @@ usage () {
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
     echo "  -N network      Environment Network (default: $environment_network)"
+    echo "  -D domain       Environment Public Domain (default: $environment_public_domain)"
+    echo "  -d domain       Environment Private Domain (default: $environment_private_domain)"
+    echo "  -b domain       Environment NetBIOS Domain (default: $environment_netbios_domain)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
 }
@@ -138,9 +141,9 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvmoO:C:S:E:N:a:u:? arg; do
+while getopts isfvmoO:C:S:E:N:D:d:b:a:u:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
@@ -151,6 +154,9 @@ while getopts IsfvmoO:C:S:E:N:a:u:? arg; do
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
     N)  environment_network="$OPTARG";;
+    D)  environment_public_domain="$OPTARG";;
+    d)  environment_private_domain="$OPTARG";;
+    b)  environment_netbios_domain="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
     ?)  usage
@@ -205,6 +211,11 @@ if [ -z $environment ]; then
 else
     case $environment in
       Identity)
+        addresses_per_subnet=32
+        subnets_per_availability_zone=8
+        availability_zones_per_vpc=2
+        use_public_hostedzone=true
+        use_private_hostedzone=false
         use_multi_zone_nat_gateways=false
         use_vpn_gateway=false;;
       *)
@@ -217,6 +228,24 @@ if [ -z $environment_network ]; then
     echo "-N network missing!"
     echo "Could not automatically determine environment network, and it was not specified as a parameter"
     exit 22
+fi
+
+if [ -z $environment_public_domain ]; then
+    echo "-D domain missing!"
+    echo "Could not automatically determine public domain, and it was not specified as a parameter"
+    exit 24
+fi
+
+if [ -z $environment_private_domain ]; then
+    echo "-d domain missing!"
+    echo "Could not automatically determine private domain, and it was not specified as a parameter"
+    exit 26
+fi
+
+if [ -z $environment_netbios_domain ]; then
+    echo "-b domain missing!"
+    echo "Could not automatically determine NetBIOS domain, and it was not specified as a parameter"
+    exit 28
 fi
 
 s3_domain=s3.amazonaws.com
@@ -241,11 +270,18 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 58
 fi
 
+echo -n "Confirming Stack pre-requisites "
+
 if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
                                         --profile $profile --region $region --output text &> /dev/null; then
+    echo
     echo "Unable to update - $environment-VPC Stack does not exist!"
-    exit 80
+    exit 98
+else
+    echo -n "."
 fi
+echo " Done"
+sleep 1
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
 template_folder=identity
@@ -346,9 +382,16 @@ read -r -d '' statement << EOS
 aws cloudformation update-stack --stack-name $environment-VPC \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=HostedZoneStackName,ParameterValue=$environment-HostedZone \\
-                                             ParameterKey=Name,ParameterValue=$environment \\
+                                --parameters ParameterKey=Name,ParameterValue=$environment \\
                                              ParameterKey=Network,ParameterValue=$environment_network \\
+                                             ParameterKey=AddressesPerSubnet,ParameterValue=$addresses_per_subnet \\
+                                             ParameterKey=SubnetsPerAvailabilityZone,ParameterValue=$subnets_per_availability_zone \\
+                                             ParameterKey=AvailabilityZonesPerVPC,ParameterValue=$availability_zones_per_vpc \\
+                                             ParameterKey=PublicDomain,ParameterValue=$environment_public_domain \\
+                                             ParameterKey=PrivateDomain,ParameterValue=$environment_private_domain \\
+                                             ParameterKey=NetBIOSDomain,ParameterValue=$environment_netbios_domain \\
+                                             ParameterKey=UsePublicHostedZone,ParameterValue=$use_public_hostedzone \\
+                                             ParameterKey=UsePrivateHostedZone,ParameterValue=$use_private_hostedzone \\
                                              ParameterKey=UseMultiZoneNatGateways,ParameterValue=$use_multi_zone_nat_gateways \\
                                              ParameterKey=UseVPNGateway,ParameterValue=$use_vpn_gateway \\
                                 --tags Key=Owner,Value=$owner \\
diff --git a/utility/bin/utility-delete-activedirectory-stack b/utility/bin/utility-delete-activedirectory-stack
--- a/utility/bin/utility-delete-activedirectory-stack
+++ b/utility/bin/utility-delete-activedirectory-stack
@@ -1,9 +1,6 @@
 #!/bin/bash
 #
-# This script deletes the Application Integration Stack in an Environment Account.
-#
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
+# This script deletes the Utility ActiveDirectory Stack in an Environment, Core, Build or Identity VPC.
 #
 
 #  1. Initalize Environment
@@ -17,15 +14,15 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-delete_default=15
-delete_attempts=40
+delete_default=60
+delete_attempts=60
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
 environment=${ENVIRONMENT_NAME:-Production}
-application=${APPLICATION_NAME:-Integration}
+utility=${UTILITY_NAME:-ActiveDirectory}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -34,17 +31,17 @@ user=${AWS_USER_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m]"
     echo "                  [-E environment]"
-    echo "                  [-A application]"
+    echo "                  [-U utility]"
     echo "                  [-r region] [-a account] [-u user]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
     echo "  -m              monitor"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -A application  Application Name (default: $application)"
+    echo "  -U utility      Utility Name (default: $utility)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -130,15 +127,15 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvmE:A:r:a:u:? arg; do
+while getopts isfvmE:U:r:a:u:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
     m)  monitor=1;;
     E)  environment="$OPTARG";;
-    A)  application="$OPTARG";;
+    U)  utility="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -167,22 +164,28 @@ else
         ;;
       Development)
         ;;
+      Core)
+        ;;
+      Build)
+        ;;
+      Identity)
+        ;;
       *)
-        echo "-E $environment invalid! Must be Production, Staging, Testing or Development"
+        echo "-E $environment invalid! Must be Production, Staging, Testing, Development, Core, Build or Identity"
         exit 21;;
     esac
 fi
 
-if [ -z $application ]; then
-    echo "-A application missing!"
-    echo "Could not automatically determine application, and it was not specified as a parameter"
+if [ -z $utility ]; then
+    echo "-U utility missing!"
+    echo "Could not automatically determine utility, and it was not specified as a parameter"
     exit 30
 else
-    case $application in
-      Integration)
+    case $utility in
+      ActiveDirectory)
         ;;
       *)
-        echo "-A $application invalid! Must be Integration"
+        echo "-U $utility invalid! Must be ActiveDirectory"
         exit 31;;
     esac
 fi
@@ -223,11 +226,18 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 58
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
+echo -n "Confirming Stack pre-requisites "
+
+if ! aws cloudformation describe-stacks --stack-name $environment-$utility \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to delete - $environment-$application Stack does not exist!"
-    exit 80
+    echo
+    echo "Unable to delete - $environment-$utility Stack does not exist!"
+    exit 99
+else
+    echo -n "."
 fi
+echo " Done"
+sleep 1
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -275,7 +285,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation delete-stack --stack-name $environment-$application \\
+aws cloudformation delete-stack --stack-name $environment-$utility \\
                                 --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -293,7 +303,7 @@ echo "Commands:"
 echo
 echo "$statement"
 
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
+if ! aws cloudformation describe-stacks --stack-name $environment-$utility \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo
     tput rev
@@ -317,7 +327,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name $environment-$application \\
+aws cloudformation describe-stacks --stack-name $environment-$utility \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -325,7 +335,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name $environment-$application --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name $environment-$utility --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -347,7 +357,7 @@ if [ $monitor = 1 ]; then
     echo
     echo "$statement2"
 
-    if ! aws cloudformation describe-stacks --stack-name $environment-$application \
+    if ! aws cloudformation describe-stacks --stack-name $environment-$utility \
                                             --profile $profile --region $region &> /dev/null; then
         echo
         tput rev
@@ -371,7 +381,7 @@ if [ $monitor = 1 ]; then
                 echo "$run_statement2"
                 eval "$eval_statement2"
 
-                status=$(aws cloudformation describe-stacks --stack-name $environment-$application \
+                status=$(aws cloudformation describe-stacks --stack-name $environment-$utility \
                                                             --query 'Stacks[].StackStatus' \
                                                             --profile $profile --region $region --output text 2> /dev/null)
                 if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
diff --git a/utility/bin/utility-update-activedirectory-stack b/utility/bin/utility-update-activedirectory-stack
--- a/utility/bin/utility-update-activedirectory-stack
+++ b/utility/bin/utility-update-activedirectory-stack
@@ -1,9 +1,6 @@
 #!/bin/bash
 #
-# This script updates the Application Integration Stack in an Environment Account.
-#
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
+# This script updates the Utility ActiveDirectory Stack in an Environment, Core, Build or Identity VPC.
 #
 
 #  1. Initalize Environment
@@ -17,10 +14,10 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-update_default=15
-update_attempts=40
+update_default=60
+update_attempts=60
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
@@ -29,21 +26,30 @@ owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
-application=${APPLICATION_NAME:-Integration}
+environment_type=${ENVIRONMENT_TYPE:-large}
+environment_zones=${ENVIRONMENT_ZONES:-2}
+utility=${UTILITY_NAME:-ActiveDirectory}
+utility_restore_mode_password=${ACTIVEDIRECTORY_RESTORE_MODE_PASSWORD:-} # This should have no default value
+administrator_networks=${ACTIVEDIRECTORY_ADMINISTRATOR_NETWORKS:-NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
+domainadmin_user=${DOMAINADMIN_USER:-StackAdmin}
+domainadmin_password=${DOMAINADMIN_PASSWORD:-} # This should have no default value
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
+key=${AWS_KEY_NAME:-administrator}
 
 
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m] [-o]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m] [-o]"
     echo "                  [-O owner] [-C company] [-S system]"
-    echo "                  [-E environment]"
-    echo "                  [-A application]"
-    echo "                  [-r region] [-a account] [-u user]"
-    echo "  -I              non-interactive"
+    echo "                  [-E environment] [-T type] [-Z zones]"
+    echo "                  [-U utility] [-R password]"
+    echo "                  [-N networks]"
+    echo "                  [-A user] [-P password]"
+    echo "                  [-r region] [-a account] [-u user] [-k key]"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
@@ -53,10 +59,17 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -A application  Application Name (default: $application)"
+    echo "  -T type         Environment Type (default: $environment_type)"
+    echo "  -Z zones        Environment Zones (default: $environment_zones)"
+    echo "  -U utility      Utility Name (default: $utility)"
+    echo "  -R password     Utility Restore Mode Password (default: $utility_restore_mode_password)"
+    echo "  -N networks     Administrator Networks (default: $administrator_networks)"
+    echo "  -A user         DomainAdmin User (default: $domainadmin_user)"
+    echo "  -P password     DomainAdmin Password (default: $domainadmin_password)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
+    echo "  -k key          Key (default: $key)"
 }
 
 run() {
@@ -138,11 +151,10 @@ next() {
 
 
 #  3. Parse command line options
-#     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvmoO:C:S:E:A:r:a:u:? arg; do
+while getopts isfvmoO:C:S:E:T:Z:U:R:N:A:P:r:a:u:k:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
@@ -152,10 +164,17 @@ while getopts IsfvmoO:C:S:E:A:r:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    A)  application="$OPTARG";;
+    T)  environment_type="$OPTARG";;
+    Z)  environment_zones="$OPTARG";;
+    U)  utility="$OPTARG";;
+    R)  utility_restore_mode_password="$OPTARG";;
+    N)  administrator_networks="$OPTARG";;
+    A)  domainadmin_user="$OPTARG";;
+    P)  domainadmin_password="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
+    k)  key="$OPTARG";;
     ?)  usage
         exit 1;;
     esac
@@ -208,43 +227,118 @@ if [ -z $environment ]; then
 else
     case $environment in
       Production)
-        octopus_deploy_environment=Production
-        mongodb_environment=Production
-        rabbitmq_environment=Production
-        webspheremq_environment=Production;;
+        os_name="Windows Server 2012 R2"
+        os_date="20170510"
+        use_static_address=true
+        log_retention=30;;
       Staging)
-        octopus_deploy_environment=Core
-        mongodb_environment=Staging
-        rabbitmq_environment=Staging
-        webspheremq_environment=Core;;
+        os_name="Windows Server 2012 R2"
+        os_date="20170510"
+        use_static_address=true
+        log_retention=7;;
       Testing)
-        octopus_deploy_environment=Core
-        mongodb_environment=Testing
-        rabbitmq_environment=Testing
-        webspheremq_environment=Core;;
+        os_name="Windows Server 2012 R2"
+        os_date="20170510"
+        use_static_address=true
+        log_retention=7;;
       Development)
-        octopus_deploy_environment=Core
-        mongodb_environment=Development
-        rabbitmq_environment=Development
-        webspheremq_environment=Core;;
+        os_name="Windows Server 2012 R2"
+        os_date="20170510"
+        use_static_address=true
+        log_retention=14;;
+      Core)
+        os_name="Windows Server 2012 R2"
+        os_date="20170510"
+        use_static_address=true
+        log_retention=30;;
+      Build)
+        os_name="Windows Server 2012 R2"
+        os_date="20170510"
+        use_static_address=true
+        log_retention=7;;
+      Identity)
+        os_name="Windows Server 2012 R2"
+        os_date="20170510"
+        use_static_address=true
+        log_retention=30;;
       *)
-        echo "-E $environment invalid! Must be Production, Staging, Testing or Development"
+        echo "-E $environment invalid! Must be Production, Staging, Testing, Development, Core, Build or Identity"
         exit 21;;
     esac
 fi
 
-if [ -z $application ]; then
-    echo "-A application missing!"
-    echo "Could not automatically determine application, and it was not specified as a parameter"
-    exit 30
+if [ -z $environment_type ]; then
+    echo "-T type missing!"
+    echo "Could not automatically determine environment type, and it was not specified as a parameter"
+    exit 22
 else
-    case $application in
-      Integration)
+    case $environment_type in
+      micro|small|medium|large|xlarge)
         ;;
       *)
-        echo "-A $application invalid! Must be Integration"
+        echo "-T $environment_type invalid! Must be micro, small, medium, large or xlarge"
+        exit 23;;
+    esac
+fi
+
+if [ -z $environment_zones ]; then
+    echo "-Z zones missing!"
+    echo "Could not automatically determine environment zones, and it was not specified as a parameter"
+    exit 24
+else
+    case $environment_zones in
+      1|2)
+        ;;
+      *)
+        echo "-Z $environment_zones invalid! Must be 1 or 2"
+        exit 25;;
+    esac
+fi
+
+if [ -z $utility ]; then
+    echo "-U utility missing!"
+    echo "Could not automatically determine utility, and it was not specified as a parameter"
+    exit 30
+else
+    case $utility in
+      ActiveDirectory)
+        ;;
+      *)
+        echo "-U $utility invalid! Must be ActiveDirectory"
         exit 31;;
     esac
+fi
+
+if [ -z $utility_restore_mode_password ]; then
+    echo "-R password missing!"
+    echo "Could not automatically determine utility restore mode password, and it was not specified as a parameter"
+    exit 36
+fi
+
+if [ -z $administrator_networks ]; then
+    echo "-N networks missing!"
+    echo "Could not automatically determine administrator networks, and it was not specified as a parameter"
+    exit 42
+fi
+
+if [ -z $domainadmin_user ]; then
+    echo "-A user missing!"
+    echo "Could not automatically determine DomainAdmin user, and it was not specified as a parameter"
+    exit 46
+else
+    case $domainadmin_user in
+      StackAdmin)
+        ;;
+      *)
+        echo "-A $domainadmin_user invalid! Must be StackAdmin"
+        exit 47;;
+    esac
+fi
+
+if [ -z $domainadmin_password ]; then
+    echo "-P password missing!"
+    echo "Could not automatically determine DomainAdmin password, and it was not specified as a parameter"
+    exit 48
 fi
 
 if [ -z $region ]; then
@@ -275,6 +369,12 @@ if [ -z $user ]; then
     exit 54
 fi
 
+if [ -z $key ]; then
+    echo "-k key missing!"
+    echo "Could not automatically determine key, and it was not specified as a parameter"
+    exit 56
+fi
+
 profile=$account-$user
 
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
@@ -283,14 +383,29 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 58
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
+echo -n "Confirming Stack pre-requisites "
+
+if ! aws cloudformation describe-stacks --stack-name $environment-$utility \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - $environment-$application Stack does not exist!"
-    exit 80
+    echo
+    echo "Unable to update - $environment-$utility Stack does not exist!"
+    exit 98
+else
+    echo -n "."
 fi
+echo " Done"
+sleep 1
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-template_folder=application
+template_folder=utility
+
+scripts_bucket=${AWS_SCRIPTS_BUCKET:-scripts-$region-$account}
+shared_script_folder=Windows
+script_folder=ActiveDirectory
+
+configurations_bucket=${AWS_CONFIGURATIONS_BUCKET:-configurations-$region-$account}
+shared_configuration_folder=Windows
+configuration_folder=ActiveDirectory
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -340,7 +455,7 @@ fi
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
             s3://$templates_bucket/$template_folder \\
-            --exclude '*' --include 'Application-Integration.json' --include 'Application-Integration-StackPolicy.json' \\
+            --exclude '*' --include 'Utility-ActiveDirectory.json' --include 'Utility-ActiveDirectory-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -368,30 +483,44 @@ next 50
 
 
 ((++step))
-template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Application-Integration.json"
-stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Application-Integration-StackPolicy.json"
+template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Utility-ActiveDirectory.json"
+stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Utility-ActiveDirectory-StackPolicy.json"
 if [ $override = 1 ]; then
     stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
 fi
 read -r -d '' statement << EOS
-aws cloudformation update-stack --stack-name $environment-$application \\
+aws cloudformation update-stack --stack-name $environment-$utility \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=EngineWebStackName,ParameterValue=$environment-Engine-Web \\
-                                             ParameterKey=EngineCalculationStackName,ParameterValue=$environment-Engine-Calculation \\
-                                             ParameterKey=EngineDataStagingStackName,ParameterValue=$environment-Engine-DataStaging \\
-                                             ParameterKey=EnginePublishingStackName,ParameterValue=$environment-Engine-Publishing \\
-                                             ParameterKey=EngineMonitoringStackName,ParameterValue=$environment-Engine-Monitoring \\
-                                             ParameterKey=OctopusDeployStackName,ParameterValue=$octopus_deploy_environment-Octopus-Deploy \\
-                                             ParameterKey=MongoDBStackName,ParameterValue=$mongodb_environment-MongoDB \\
-                                             ParameterKey=RabbitMQStackName,ParameterValue=$rabbitmq_environment-RabbitMQ \\
-                                             ParameterKey=WebSphereMQStackName,ParameterValue=$webspheremq_environment-WebSphereMQ \\
-                                             ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
+                                --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
+                                             ParameterKey=CustomIdentifierFunctionsStackName,ParameterValue=CustomIdentifierFunctions \\
+                                             ParameterKey=StandardCIDRFunctionsStackName,ParameterValue=StandardCIDRFunctions \\
+                                             ParameterKey=StandardAMIFunctionsStackName,ParameterValue=StandardAMIFunctions \\
+                                             ParameterKey=StandardBucketsStackName,ParameterValue=StandardBuckets \\
+                                             ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
+                                             ParameterKey=KeyName,ParameterValue=$key \\
+                                             ParameterKey=CompanyName,ParameterValue=$company \\
+                                             ParameterKey=SystemName,ParameterValue=$system \\
+                                             ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
+                                             ParameterKey=EnvironmentZones,ParameterValue=$environment_zones \\
+                                             ParameterKey=OSName,ParameterValue="$os_name" \\
+                                             ParameterKey=OSDate,ParameterValue="$os_date" \\
+                                             ParameterKey=SharedScriptFolder,ParameterValue=$shared_script_folder \\
+                                             ParameterKey=ScriptFolder,ParameterValue=$script_folder \\
+                                             ParameterKey=SharedConfigurationFolder,ParameterValue=$shared_configuration_folder \\
+                                             ParameterKey=ScriptFolder,ParameterValue=$configuration_folder \\
+                                             ParameterKey=UtilityName,ParameterValue=$utility \\
+                                             ParameterKey=RestoreModePassword,ParameterValue="$utility_restore_mode_password" \\
+                                             ParameterKey=UseStaticAddress,ParameterValue=$use_static_address \\
+                                             ParameterKey=LogRetention,ParameterValue=$log_retention \\
+                                             ParameterKey=AdministratorNetworks,ParameterValue=\"$administrator_networks\" \\
+                                             ParameterKey=DomainAdminUser,ParameterValue="$domainadmin_user" \\
+                                             ParameterKey=DomainAdminPassword,ParameterValue="$domainadmin_password" \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
                                        Key=Environment,Value=$environment \\
-                                       Key=Application,Value=$application \\
+                                       Key=Utility,Value=$utility \\
                                 --capabilities CAPABILITY_IAM \\
                                 --profile $profile --region $region --output table
 EOS
@@ -423,7 +552,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name $environment-$application \\
+aws cloudformation describe-stacks --stack-name $environment-$utility \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -431,7 +560,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name $environment-$application --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name $environment-$utility --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -453,7 +582,7 @@ if [ $monitor = 1 ]; then
     echo
     echo "$statement2"
 
-    if [ "$(aws cloudformation describe-stacks --stack-name $environment-$application \
+    if [ "$(aws cloudformation describe-stacks --stack-name $environment-$utility \
                                                --query 'Stacks[].StackStatus' \
                                                --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
         echo
@@ -478,7 +607,7 @@ if [ $monitor = 1 ]; then
                 echo "$run_statement2"
                 eval "$eval_statement2"
 
-                status=$(aws cloudformation describe-stacks --stack-name $environment-$application \
+                status=$(aws cloudformation describe-stacks --stack-name $environment-$utility \
                                                             --query 'Stacks[].StackStatus' \
                                                             --profile $profile --region $region --output text 2> /dev/null)
                 if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
@@ -503,7 +632,7 @@ aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'} 2> /dev/null"
+eval_statement="${statement//\\$'\n'}"
 
 if [ $verbose = 1 ]; then
     clear
@@ -532,7 +661,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stack-resources --stack-name $environment-$application \\
+aws cloudformation describe-stack-resources --stack-name $environment-$utility \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
                                             --profile $profile --region $region --output table
 EOS
diff --git a/utility/bin/utility-update-linuxbastions-stack b/utility/bin/utility-update-linuxbastions-stack
--- a/utility/bin/utility-update-linuxbastions-stack
+++ b/utility/bin/utility-update-linuxbastions-stack
@@ -2,9 +2,6 @@
 #
 # This script updates the Utility LinuxBastions Stack in an Environment, Core or Build VPC.
 #
-# This script is written in a format suitable for interactive demos,
-# but can be run non-Iteractively and more quickly with the "-I" flag.
-#
 
 #  1. Initalize Environment
 
@@ -20,7 +17,7 @@ next_default=5
 update_default=15
 update_attempts=40
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
@@ -33,12 +30,7 @@ environment_type=standby  # By default, these run in standby mode
 environment_zones=${ENVIRONMENT_ZONES:-1}
 utility=${UTILITY_NAME:-LinuxBastions}
 utility_domain=${UTILITY_DOMAIN:-lbastion}
-public_user_network=${PUBLIC_USER_NETWORK:-0.0.0.0/0}
-public_user_network1=${PUBLIC_USER_NETWORK1:-}
-public_user_network2=${PUBLIC_USER_NETWORK2:-}
-private_user_network=${PRIVATE_USER_NETWORK:-10.0.0.0/16}
-private_user_network1=${PRIVATE_USER_NETWORK1:-}
-private_user_network2=${PRIVATE_USER_NETWORK2:-}
+user_networks=${LINUXBASTIONS_USER_NETWORKS:-0.0.0.0/0,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -48,14 +40,13 @@ key=${AWS_KEY_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m] [-o]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m] [-o]"
     echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment] [-T type] [-Z zones]"
     echo "                  [-U utility] [-D domain]"
-    echo "                  [-p network]"
-    echo "                  [-n network]"
+    echo "                  [-n networks]"
     echo "                  [-r region] [-a account] [-u user] [-k key]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
@@ -69,8 +60,7 @@ usage () {
     echo "  -Z zones        Environment Zones (default: $environment_zones)"
     echo "  -U utility      Utility Name (default: $utility)"
     echo "  -D domain       Utility Domain (default: $utility_domain)"
-    echo "  -p network      Public User Network (default: $public_user_network)"
-    echo "  -n network      Private User Network (default: $private_user_network)"
+    echo "  -n networks     User Networks (default: $user_networks)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -156,11 +146,10 @@ next() {
 
 
 #  3. Parse command line options
-#     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvmoO:C:S:E:T:Z:U:D:p:1:2:n:5:6:r:a:u:k:? arg; do
+while getopts isfvmoO:C:S:E:T:Z:U:D:n:r:a:u:k:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
@@ -174,12 +163,7 @@ while getopts IsfvmoO:C:S:E:T:Z:U:D:p:1:2:n:5:6:r:a:u:k:? arg; do
     Z)  environment_zones="$OPTARG";;
     U)  utility="$OPTARG";;
     D)  utility_domain="$OPTARG";;
-    p)  public_user_network="$OPTARG";;
-    1)  public_user_network1="$OPTARG";;
-    2)  public_user_network2="$OPTARG";;
-    n)  private_user_network="$OPTARG";;
-    5)  private_user_network1="$OPTARG";;
-    6)  private_user_network2="$OPTARG";;
+    n)  user_networks="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -337,16 +321,10 @@ if [ -z $utility_domain ]; then
     exit 32
 fi
 
-if [ -z $public_user_network ]; then
-    echo "-p network missing!"
-    echo "Could not automatically determine public user network, and it was not specified as a parameter"
+if [ -z $user_networks ]; then
+    echo "-n networks missing!"
+    echo "Could not automatically determine user networks, and it was not specified as a parameter"
     exit 40
-fi
-
-if [ -z $private_user_network ]; then
-    echo "-n network missing!"
-    echo "Could not automatically determine private user network, and it was not specified as a parameter"
-    exit 44
 fi
 
 if [ -z $region ]; then
@@ -391,18 +369,31 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 58
 fi
 
+echo -n "Confirming Stack pre-requisites "
+
 if ! aws cloudformation describe-stacks --stack-name $environment-$utility \
                                         --profile $profile --region $region --output text &> /dev/null; then
+    echo
     echo "Unable to update - $environment-$utility Stack does not exist!"
-    exit 80
+    exit 98
+else
+    echo -n "."
 fi
+echo " Done"
+sleep 1
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
 template_folder=utility
 
+scripts_bucket=${AWS_SCRIPTS_BUCKET:-scripts-$region-$account}
+shared_script_folder=Linux
+script_folder=LinuxBastions
+
 configurations_bucket=${AWS_CONFIGURATIONS_BUCKET:-configurations-$region-$account}
-configuration_folder=$utility
-configuration_object=$environment-$utility-etc-hosts
+shared_configuration_folder=Linux
+configuration_folder=LinuxBastions
+#hosts_configuration_object=$environment-etc-hosts
+hosts_configuration_object=""
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -500,8 +491,11 @@ aws cloudformation update-stack --stack-name $environment-$utility \\
                                              ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
                                              ParameterKey=EnvironmentZones,ParameterValue=$environment_zones \\
                                              ParameterKey=OSName,ParameterValue="$os_name" \\
+                                             ParameterKey=SharedScriptFolder,ParameterValue=$shared_script_folder \\
+                                             ParameterKey=ScriptFolder,ParameterValue=$script_folder \\
+                                             ParameterKey=SharedConfigurationFolder,ParameterValue=$shared_configuration_folder \\
                                              ParameterKey=ConfigurationFolder,ParameterValue=$configuration_folder \\
-                                             ParameterKey=ConfigurationObject,ParameterValue=$configuration_object \\
+                                             ParameterKey=HostsConfigurationObject,ParameterValue=$hosts_configuration_object \\
                                              ParameterKey=UtilityName,ParameterValue=$utility \\
                                              ParameterKey=UtilityDomain,ParameterValue=$utility_domain \\
                                              ParameterKey=UseStaticPublicAddress,ParameterValue=$use_static_public_address \\
@@ -510,12 +504,7 @@ aws cloudformation update-stack --stack-name $environment-$utility \\
                                              ParameterKey=LogRetention,ParameterValue=$log_retention \\
                                              ParameterKey=OnSchedule,ParameterValue="$on_schedule" \\
                                              ParameterKey=OffSchedule,ParameterValue="$off_schedule" \\
-                                             ParameterKey=PublicUserNetwork,ParameterValue=$public_user_network \\
-                                             ParameterKey=PublicUserNetwork1,ParameterValue=$public_user_network1 \\
-                                             ParameterKey=PublicUserNetwork2,ParameterValue=$public_user_network2 \\
-                                             ParameterKey=PrivateUserNetwork,ParameterValue=$private_user_network \\
-                                             ParameterKey=PrivateUserNetwork1,ParameterValue=$private_user_network1 \\
-                                             ParameterKey=PrivateUserNetwork2,ParameterValue=$private_user_network2 \\
+                                             ParameterKey=UserNetworks,ParameterValue=\"$user_networks\" \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
