refactor WebSphereMQ application to use VPN server for access, add missing features needed for WebSphereMQ

diff --git a/application/bin/application-update-webspheremq-stack b/application/bin/application-update-webspheremq-stack
--- a/application/bin/application-update-webspheremq-stack
+++ b/application/bin/application-update-webspheremq-stack
@@ -31,17 +31,14 @@ system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
 environment_size=${ENVIRONMENT_SIZE:-medium}
 application=${APPLICATION_NAME:-WebSphereMQ}
-application_domain=${APPLICATION_DOMAIN:-wmq}
+application_domain=${APPLICATION_DOMAIN:-tvluw2pwmq01}
+application_domain_override=0
 application_version=${APPLICATION_VERSION:-1.0.0}
 key=${AWS_KEY_NAME:-user}
-network=${ADMINISTRATOR_NETWORK:-0.0.0.0/0}
-network1=${ADMINISTRATOR_NETWORK1:-}
-network2=${ADMINISTRATOR_NETWORK2:-}
-network3=${ADMINISTRATOR_NETWORK3:-}
-private_network=${PRIVATE_NETWORK:-10.0.0.0/16}
-private_network1=${PRIVATE_NETWORK1:-}
-private_network2=${PRIVATE_NETWORK2:-}
-private_network3=${PRIVATE_NETWORK3:-}
+private_user_network=${PRIVATE_USER_NETWORK:-10.0.0.0/16}
+private_user_network1=${PRIVATE_USER_NETWORK1:-}
+private_user_network2=${PRIVATE_USER_NETWORK2:-}
+private_user_network3=${PRIVATE_USER_NETWORK3:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -72,8 +69,7 @@ usage () {
     echo "  -D domain       Application Domain (default: $application_domain)"
     echo "  -V version      Application Version (default: $application_version)"
     echo "  -k key          Key (default: $key)"
-    echo "  -n network      Administrator Network (default: $network)"
-    echo "  -P network      Private Network (default: $private_network)"
+    echo "  -P network      Private User Network (default: $private_user_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -174,17 +170,14 @@ while getopts IsfvodO:C:S:E:Z:A:D:V:k:n:1:2:3:P:7:8:9:r:a:u:? arg; do
     E)  environment="$OPTARG";;
     Z)  environment_size="$OPTARG";;
     A)  application="$OPTARG";;
-    D)  application_domain="$OPTARG";;
+    D)  application_domain="$OPTARG"
+        application_domain_override=1;;
     V)  application_version="$OPTARG";;
     k)  key="$OPTARG";;
-    n)  network="$OPTARG";;
-    1)  network1="$OPTARG";;
-    2)  network2="$OPTARG";;
-    3)  network3="$OPTARG";;
-    P)  private_network="$OPTARG";;
-    7)  private_network1="$OPTARG";;
-    8)  private_network2="$OPTARG";;
-    9)  private_network3="$OPTARG";;
+    P)  private_user_network="$OPTARG";;
+    7)  private_user_network1="$OPTARG";;
+    8)  private_user_network2="$OPTARG";;
+    9)  private_user_network3="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -208,12 +201,28 @@ if [ -z $company ]; then
     echo "-C company missing!"
     echo "Could not automatically determine company, and it was not specified as a parameter"
     exit 12
+else
+    case $company in
+      Travel)
+        company_code=tvl;;
+      *)
+        echo "-C $company invalid! Must be Travel"
+        exit 13;;
+    esac
 fi
 
 if [ -z $system ]; then
     echo "-S system missing!"
     echo "Could not automatically determine system, and it was not specified as a parameter"
     exit 14
+else
+    case $system in
+      IROPS)
+        system_code=irops;;
+      *)
+        echo "-S $system invalid! Must be IROPS"
+        exit 15;;
+    esac
 fi
 
 if [ -z $environment ]; then
@@ -223,40 +232,44 @@ if [ -z $environment ]; then
 else
     case $environment in
       Production)
+        environment_code=p
         instance_os=AMZN
+        use_static_address=true
         use_filesystem_monitoring=true
         use_log_monitoring=true
         use_schedule=false
         on_schedule="0 11 * * 1-5" # 11:00 UTC = 3:00 AM PST = 6:00 AM EST, Mon-Fri
         off_schedule="0 4 * * *";; # 4:00 UTC = 8:00 PM PST = 11:00 PM EST, Mon-Fri
       Staging)
-        instance_os=AMZN
+        environment_code=s
+        instance_os=RHEL
+        use_static_address=true
         use_filesystem_monitoring=true
         use_log_monitoring=true
-        use_schedule=true
+        use_schedule=false
         on_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         off_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       Testing)
-        instance_os=AMZN
+        environment_code=t
+        instance_os=RHEL
+        use_static_address=true
         use_filesystem_monitoring=false
         use_log_monitoring=false
-        use_schedule=true
+        use_schedule=false
         on_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         off_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       Development)
-        instance_os=AMZN
+        environment_code=d
+        instance_os=RHEL
+        use_static_address=true
         use_filesystem_monitoring=false
         use_log_monitoring=false
-        use_schedule=true
+        use_schedule=false
         on_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         off_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       *)
-        instance_os=AMZN
-        use_filesystem_monitoring=false
-        use_log_monitoring=false
-        use_schedule=true
-        on_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
-        off_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
+        echo "-E $environment invalid! Must be Production, Staging, Testing or Development"
+        exit 17;;
     esac
 fi
 
@@ -264,12 +277,34 @@ if [ -z $environment_size ]; then
     echo "-Z size missing!"
     echo "Could not automatically determine size, and it was not specified as a parameter"
     exit 18
+else
+    case $environment_size in
+      small)
+        environment_size_code=s;;
+      medium)
+        environment_size_code=m;;
+      large)
+        environment_size_code=l;;
+      xlarge)
+        environment_size_code=xl;;
+      *)
+        echo "-Z $environment_size invalid! Must be small, medium, large or xlarge"
+        exit 19;;
+    esac
 fi
 
 if [ -z $application ]; then
     echo "-A application missing!"
     echo "Could not automatically determine application, and it was not specified as a parameter"
     exit 20
+else
+    case $application in
+      WebSphereMQ)
+        application_code=wmq;;
+      *)
+        echo "-A $application invalid! Must be WebSphereMQ"
+        exit 21;;
+    esac
 fi
 
 if [ -z $application_domain ]; then
@@ -290,15 +325,9 @@ if [ -z $key ]; then
     exit 30
 fi
 
-if [ -z $network ]; then
-    echo "-n network missing!"
-    echo "Could not automatically determine network, and it was not specified as a parameter"
-    exit 32
-fi
-
-if [ -z $private_network ]; then
+if [ -z $private_user_network ]; then
     echo "-P network missing!"
-    echo "Could not automatically determine private network, and it was not specified as a parameter"
+    echo "Could not automatically determine private user network, and it was not specified as a parameter"
     exit 36
 fi
 
@@ -309,11 +338,34 @@ if [ -z $region ]; then
 else
     case $region in
       us-east-1)
+        location_code=ue1
         s3_domain=s3.amazonaws.com;;
-      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+      us-east-2)
+        location_code=ue2
         s3_domain=s3-$region.amazonaws.com;;
-    *)
-        echo "-r $region invalid: Please specify a valid region"
+      us-west-1)
+        location_code=uw1
+        s3_domain=s3-$region.amazonaws.com;;
+      us-west-2)
+        location_code=uw2
+        s3_domain=s3-$region.amazonaws.com;;
+      ca-central-1)
+        location_code=cc1
+        s3_domain=s3-$region.amazonaws.com;;
+      eu-west-1)
+        location_code=ew1
+        s3_domain=s3-$region.amazonaws.com;;
+      eu-central-1)
+        location_code=ec1
+        s3_domain=s3-$region.amazonaws.com;;
+      eu-west-2)
+        location_code=ew2
+        s3_domain=s3-$region.amazonaws.com;;
+      ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
+        location_code=aws
+        s3_domain=s3-$region.amazonaws.com;;
+      *)
+        echo "-r $region invalid: Must be a valid region"
         exit 51;;
     esac
 fi
@@ -328,6 +380,11 @@ if [ -z $user ]; then
     echo "-u user missing!"
     echo "Could not automatically determine user, and it was not specified as a parameter"
     exit 54
+fi
+
+if [ $application_domain_override = 0 ]; then
+    # If not explicitly overridden, reconstruct application_domain in case any parts which make up the name have changed
+    application_domain=${company_code}${location_code}${environment_code}${application_code}01
 fi
 
 profile=$account-$user
@@ -423,7 +480,7 @@ aws s3 sync $templatesdir \\
             --include 'Application-WebSphereMQ-Logs.json' \\
             --include 'Application-WebSphereMQ-SecurityGroups.json' \\
             --include 'Application-WebSphereMQ-FileSystem.json' \\
-            --include 'Application-WebSphereMQ-Instances.json' \\
+            --include 'Application-WebSphereMQ-QueueInstances.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -465,8 +522,11 @@ read -r -d '' statement << EOS
 aws cloudformation update-stack --stack-name $environment-$application \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
+                                --parameters ParameterKey=VPNStackName,ParameterValue=$environment-OpenVPNAS \\
                                              ParameterKey=LinuxBastionsStackName,ParameterValue=$environment-LinuxBastions \\
+                                             ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
+                                             ParameterKey=StandardCIDRFunctionsStackName,ParameterValue=StandardCIDRFunctions \\
+                                             ParameterKey=StandardAMIFunctionsStackName,ParameterValue=StandardAMIFunctions \\
                                              ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
                                              ParameterKey=TemplatesBucket,ParameterValue=$templates_bucket \\
@@ -483,20 +543,16 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                              ParameterKey=ConfigurationWebSphereMQObject,ParameterValue=$configurations_wmq_object \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
                                              ParameterKey=ApplicationDomain,ParameterValue=$application_domain \\
-                                             ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
+                                             ParameterKey=UseStaticAddress,ParameterValue=$use_static_address \\
                                              ParameterKey=UseFileSystemMonitoring,ParameterValue=$use_filesystem_monitoring \\
                                              ParameterKey=UseLogMonitoring,ParameterValue=$use_log_monitoring \\
                                              ParameterKey=UseSchedule,ParameterValue=$use_schedule \\
                                              ParameterKey=OnSchedule,ParameterValue="$on_schedule" \\
                                              ParameterKey=OffSchedule,ParameterValue="$off_schedule" \\
-                                             ParameterKey=AdministratorNetwork,ParameterValue=$network \\
-                                             ParameterKey=AdministratorNetwork1,ParameterValue=$network1 \\
-                                             ParameterKey=AdministratorNetwork2,ParameterValue=$network2 \\
-                                             ParameterKey=AdministratorNetwork3,ParameterValue=$network3 \\
-                                             ParameterKey=PrivateNetwork,ParameterValue=$private_network \\
-                                             ParameterKey=PrivateNetwork1,ParameterValue=$private_network1 \\
-                                             ParameterKey=PrivateNetwork2,ParameterValue=$private_network2 \\
-                                             ParameterKey=PrivateNetwork3,ParameterValue=$private_network3 \\
+                                             ParameterKey=PrivateUserNetwork,ParameterValue=$private_user_network \\
+                                             ParameterKey=PrivateUserNetwork1,ParameterValue=$private_user_network1 \\
+                                             ParameterKey=PrivateUserNetwork2,ParameterValue=$private_user_network2 \\
+                                             ParameterKey=PrivateUserNetwork3,ParameterValue=$private_user_network3 \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
