Refactor Octopus-Deploy into a single-stack design

diff --git a/application/bin/application-create-octopus-deploy-stack b/application/bin/application-create-octopus-deploy-stack
--- a/application/bin/application-create-octopus-deploy-stack
+++ b/application/bin/application-create-octopus-deploy-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script creates the Application OctopusDeploy Stack in an Environment Account.
+# This script creates the Application Octopus Component Deploy Stack in an Environment Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -23,13 +23,14 @@ create_attempts=40
 interactive=1
 speed=100
 verbose=0
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
 environment_type=${ENVIRONMENT_TYPE:-large}
-application=${APPLICATION_NAME:-OctopusDeploy}
+application=${APPLICATION_NAME:-Octopus}
 application_version=${APPLICATION_VERSION:-3.12.0}
+component=${COMPONENT_NAME:-Deploy}
 private_user_network=${PRIVATE_USER_NETWORK:-10.0.0.0/16}
 private_user_network1=${PRIVATE_USER_NETWORK1:-}
 private_user_network2=${PRIVATE_USER_NETWORK2:-}
@@ -48,9 +49,10 @@ usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment] [-T type]"
-    echo "                  [-A application ] [-V version]"
-    echo "                  [-n network] [-N network ]"
-    echo "                  [-r region ] [-a account] [-u user] [-k key]"
+    echo "                  [-A application] [-V version]"
+    echo "                  [-c component]"
+    echo "                  [-n network] [-N network]"
+    echo "                  [-r region] [-a account] [-u user] [-k key]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -62,6 +64,7 @@ usage () {
     echo "  -T type         Environment Type (default: $environment_type)"
     echo "  -A application  Application Name (default: $application)"
     echo "  -V version      Application Version (default: $application_version)"
+    echo "  -c component    Component Name (default: $component)"
     echo "  -n network      Private User Network (default: $private_user_network)"
     echo "  -N network      Private Administrator Network (default: $private_administrator_network)"
     echo "  -r region       Region (default: $region)"
@@ -151,7 +154,7 @@ next() {
 #  3. Parse command line options
 #     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvO:C:S:E:T:A:V:n:5:6:N:7:8:r:a:u:k:? arg; do
+while getopts IsfvO:C:S:E:T:A:V:c:n:5:6:N:7:8:r:a:u:k:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -164,6 +167,7 @@ while getopts IsfvO:C:S:E:T:A:V:n:5:6:N:7:8:r:a:u:k:? arg; do
     T)  environment_type="$OPTARG";;
     A)  application="$OPTARG";;
     V)  application_version="$OPTARG";;
+    c)  component="$OPTARG";;
     n)  private_user_network="$OPTARG";;
     5)  private_user_network1="$OPTARG";;
     6)  private_user_network2="$OPTARG";;
@@ -280,10 +284,10 @@ if [ -z $application ]; then
     exit 30
 else
     case $application in
-      OctopusDeploy)
+      Octopus)
         ;;
       *)
-        echo "-A $application invalid! Must be OctopusDeploy"
+        echo "-A $application invalid! Must be Octopus"
         exit 31;;
     esac
 fi
@@ -294,6 +298,19 @@ if [ -z $application_version ]; then
     exit 34
 fi
 
+if [ -z $component ]; then
+    echo "-c component missing!"
+    echo "Could not automatically determine component, and it was not specified as a parameter"
+    exit 36
+else
+    case $component in
+      Deploy)
+        ;;
+      *)
+        echo "-c $component invalid! Must be Deploy"
+        exit 37;;
+    esac
+fi
 
 if [ -z $private_user_network ]; then
     echo "-n network missing!"
@@ -395,12 +412,12 @@ templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
 template_folder=application
 
 products_bucket=${AWS_PRODUCTS_BUCKET:-products-$region-$account}
-product_folder=OctopusDeploy
+product_folder=Octopus
 product_object="Octopus.$application_version-x64.msi"
 tentacle_product_object="Octopus.Tentacle.$application_version-x64.msi"
 
 configurations_bucket=${AWS_CONFIGURATIONS_BUCKET:-configurations-$region-$account}
-configuration_folder=OctopusDeploy
+configuration_folder=Octopus
 configuration_object=""
 
 # Prevent certain environment variables from breaking commands
@@ -451,11 +468,7 @@ fi
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
             s3://$templates_bucket/$template_folder \\
-            --exclude '*' --include 'Application-OctopusDeploy.json' --include 'Application-OctopusDeploy-StackPolicy.json' \\
-            --include 'Application-OctopusDeploy-Roles.json' \\
-            --include 'Application-OctopusDeploy-Logs.json' \\
-            --include 'Application-OctopusDeploy-SecurityGroups.json' \\
-            --include 'Application-OctopusDeploy-DeployInstances.json' \\
+            --exclude '*' --include 'Application-Octopus-Deploy.json' --include 'Application-Octopus-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -483,10 +496,10 @@ next 50
 
 
 ((++step))
-template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Application-OctopusDeploy.json"
-stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Application-OctopusDeploy-StackPolicy.json"
+template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Application-Octopus-Deploy.json"
+stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Application-Octopus-StackPolicy.json"
 read -r -d '' statement << EOS
-aws cloudformation create-stack --stack-name $environment-$application \\
+aws cloudformation create-stack --stack-name $environment-$application-$component \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
                                 --parameters ParameterKey=VPNStackName,ParameterValue=$environment-OpenVPNAS \\
@@ -497,7 +510,6 @@ aws cloudformation create-stack --stack-name $environment-$application \\
                                              ParameterKey=StandardBucketsStackName,ParameterValue=StandardBuckets \\
                                              ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
-                                             ParameterKey=TemplateFolder,ParameterValue=$template_folder \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
                                              ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
@@ -507,6 +519,7 @@ aws cloudformation create-stack --stack-name $environment-$application \\
                                              ParameterKey=ConfigurationFolder,ParameterValue=$configuration_folder \\
                                              ParameterKey=ConfigurationObject,ParameterValue=$configuration_object \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
+                                             ParameterKey=ComponentName,ParameterValue=$component \\
                                              ParameterKey=UseStaticAddress,ParameterValue=$use_static_address \\
                                              ParameterKey=LogRetention,ParameterValue=$log_retention \\
                                              ParameterKey=Schedule,ParameterValue=$schedule \\
@@ -521,6 +534,7 @@ aws cloudformation create-stack --stack-name $environment-$application \\
                                        Key=System,Value=$system \\
                                        Key=Environment,Value=$environment \\
                                        Key=Application,Value=$application \\
+                                       Key=Component,Value=$component \\
                                 --capabilities CAPABILITY_IAM \\
                                 --disable-rollback \\
                                 --profile $profile --region $region --output table
@@ -540,7 +554,7 @@ echo "Commands:"
 echo
 echo "$statement"
 
-if aws cloudformation describe-stacks --stack-name $environment-$application \
+if aws cloudformation describe-stacks --stack-name $environment-$application-$component \
                                       --profile $profile --region $region --output text &> /dev/null; then
     echo
     tput rev
@@ -564,7 +578,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name $environment-$application \\
+aws cloudformation describe-stacks --stack-name $environment-$application-$component \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -572,7 +586,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name $environment-$application --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name $environment-$application-$component --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -593,7 +607,7 @@ echo "$statement"
 echo
 echo "$statement2"
 
-if [ "$(aws cloudformation describe-stacks --stack-name $environment-$application \
+if [ "$(aws cloudformation describe-stacks --stack-name $environment-$application-$component \
                                            --query 'Stacks[].StackStatus' \
                                            --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
     echo
@@ -618,7 +632,7 @@ else
             echo "$run_statement2"
             eval "$eval_statement2"
 
-            status=$(aws cloudformation describe-stacks --stack-name $environment-$application \
+            status=$(aws cloudformation describe-stacks --stack-name $environment-$application-$component \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
             if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
@@ -671,7 +685,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stack-resources --stack-name $environment-$application \\
+aws cloudformation describe-stack-resources --stack-name $environment-$application-$component \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
                                             --profile $profile --region $region --output table
 EOS
diff --git a/application/bin/application-delete-octopus-deploy-stack b/application/bin/application-delete-octopus-deploy-stack
--- a/application/bin/application-delete-octopus-deploy-stack
+++ b/application/bin/application-delete-octopus-deploy-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script deletes the Application OctopusDeploy Stack in an Environment Account.
+# This script deletes the Application Octopus Component Deploy Stack in an Environment Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -24,7 +24,8 @@ interactive=1
 speed=100
 verbose=0
 environment=${ENVIRONMENT_NAME:-Production}
-application=${APPLICATION_NAME:-OctopusDeploy}
+application=${APPLICATION_NAME:-Octopus}
+component=${COMPONENT_NAME:-Deploy}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -34,14 +35,17 @@ user=${AWS_USER_NAME:-administrator}
 
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
-    echo "                  [-E environment] [-A application ]"
-    echo "                  [-r region ] [-a account] [-u user]"
+    echo "                  [-E environment]"
+    echo "                  [-A application]"
+    echo "                  [-c component]"
+    echo "                  [-r region] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
     echo "  -E environment  Environment Name (default: $environment)"
     echo "  -A application  Application Name (default: $application)"
+    echo "  -c component    Component Name (default: $component)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -127,7 +131,7 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvE:A:r:a:u:? arg; do
+while getopts IsfvE:A:c:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -135,6 +139,7 @@ while getopts IsfvE:A:r:a:u:? arg; do
     v)  verbose=1;;
     E)  environment="$OPTARG";;
     A)  application="$OPTARG";;
+    c)  component="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -151,13 +156,53 @@ shift $(($OPTIND - 1))
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
+    exit 20
+else
+    case $environment in
+      Production)
+        ;;
+      Staging)
+        ;;
+      Testing)
+        ;;
+      Development)
+        ;;
+      Core)
+        ;;
+      Build)
+        ;;
+      *)
+        echo "-E $environment invalid! Must be Production, Staging, Testing, Development, Core or Build"
+        exit 21;;
+    esac
 fi
 
 if [ -z $application ]; then
     echo "-A application missing!"
     echo "Could not automatically determine application, and it was not specified as a parameter"
-    exit 20
+    exit 30
+else
+    case $application in
+      Octopus)
+        ;;
+      *)
+        echo "-A $application invalid! Must be Octopus"
+        exit 31;;
+    esac
+fi
+
+if [ -z $component ]; then
+    echo "-c component missing!"
+    echo "Could not automatically determine component, and it was not specified as a parameter"
+    exit 36
+else
+    case $component in
+      Deploy)
+        ;;
+      *)
+        echo "-c $component invalid! Must be Deploy"
+        exit 37;;
+    esac
 fi
 
 if [ -z $region ]; then
@@ -168,9 +213,9 @@ else
     case $region in
       us-east-1)
         s3_domain=s3.amazonaws.com;;
-      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+      us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
         s3_domain=s3-$region.amazonaws.com;;
-    *)
+      *)
         echo "-r $region invalid: Please specify a valid region"
         exit 51;;
     esac
@@ -193,13 +238,13 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
+    exit 58
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
+if ! aws cloudformation describe-stacks --stack-name $environment-$application-$component \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to delete - $environment-$application Stack does not exist!"
-    exit 70
+    echo "Unable to delete - $environment-$application-$component Stack does not exist!"
+    exit 80
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -248,7 +293,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation delete-stack --stack-name $environment-$application \\
+aws cloudformation delete-stack --stack-name $environment-$application-$component \\
                                 --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -266,7 +311,7 @@ echo "Commands:"
 echo
 echo "$statement"
 
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
+if ! aws cloudformation describe-stacks --stack-name $environment-$application-$component \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo
     tput rev
@@ -290,7 +335,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name $environment-$application \\
+aws cloudformation describe-stacks --stack-name $environment-$application-$component \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -298,7 +343,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name $environment-$application --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name $environment-$application-$component --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -319,7 +364,7 @@ echo "$statement"
 echo
 echo "$statement2"
 
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
+if ! aws cloudformation describe-stacks --stack-name $environment-$application-$component \
                                         --profile $profile --region $region &> /dev/null; then
     echo
     tput rev
@@ -343,7 +388,7 @@ else
             echo "$run_statement2"
             eval "$eval_statement2"
 
-            status=$(aws cloudformation describe-stacks --stack-name $environment-$application \
+            status=$(aws cloudformation describe-stacks --stack-name $environment-$application-$component \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
             if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
