adjustments to use client WebSphere Stack, fix some small bugs

diff --git a/application/bin/application-create-engine-calculation-stack b/application/bin/application-create-engine-calculation-stack
--- a/application/bin/application-create-engine-calculation-stack
+++ b/application/bin/application-create-engine-calculation-stack
@@ -474,13 +474,15 @@ else
     echo -n "."
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $octopus_deploy_stack_name \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo
-    echo "Stack dependency missing - $octopus_deploy_stack_name Stack does not exist!"
-    exit 79
-else
-    echo -n "."
+if [ -n "$octopus_deploy_stack_name" ]; then
+    if ! aws cloudformation describe-stacks --stack-name $octopus_deploy_stack_name \
+                                            --profile $profile --region $region --output text &> /dev/null; then
+        echo
+        echo "Stack dependency missing - $octopus_deploy_stack_name Stack does not exist!"
+        exit 79
+    else
+        echo -n "."
+    fi
 fi
 
 if ! aws cloudformation describe-stacks --stack-name $environment-RabbitMQ \
diff --git a/application/bin/application-create-engine-datastaging-stack b/application/bin/application-create-engine-datastaging-stack
--- a/application/bin/application-create-engine-datastaging-stack
+++ b/application/bin/application-create-engine-datastaging-stack
@@ -231,8 +231,9 @@ if [ -z $environment ]; then
 else
     case $environment in
       Production)
-        datatransfer_sftp_stack_name=$environment-DataTransfer-SFTP
-        webspheremq_stack_name=$environment-WebSphereMQ
+        # TODO: Currently, the DataTransfer Application has not yet been implemented
+        #datatransfer_sftp_stack_name=$environment-DataTransfer-SFTP
+        unset datatransfer_sftp_stack_name
         octopus_deploy_stack_name=$environment-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
@@ -240,8 +241,9 @@ else
         log_retention=30
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Staging)
-        datatransfer_sftp_stack_name=Core-DataTransfer-SFTP
-        webspheremq_stack_name=Core-WebSphereMQ
+        # TODO: Currently, the DataTransfer Application has not yet been implemented
+        #datatransfer_sftp_stack_name=Core-DataTransfer-SFTP
+        unset datatransfer_sftp_stack_name
         octopus_deploy_stack_name=$environment-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
@@ -250,7 +252,6 @@ else
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Testing)
         unset datatransfer_sftp_stack_name
-        webspheremq_stack_name=Core-WebSphereMQ
         octopus_deploy_stack_name=Core-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
@@ -259,7 +260,6 @@ else
         schedule="13:00-2:00";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       Development)
         unset datatransfer_sftp_stack_name
-        webspheremq_stack_name=Core-WebSphereMQ
         octopus_deploy_stack_name=Core-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
@@ -482,19 +482,21 @@ else
     echo -n "."
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $octopus_deploy_stack_name \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo
-    echo "Stack dependency missing - $octopus_deploy_stack_name Stack does not exist!"
-    exit 79
-else
-    echo -n "."
+if [ -n "$octopus_deploy_stack_name" ]; then
+    if ! aws cloudformation describe-stacks --stack-name $octopus_deploy_stack_name \
+                                            --profile $profile --region $region --output text &> /dev/null; then
+        echo
+        echo "Stack dependency missing - $octopus_deploy_stack_name Stack does not exist!"
+        exit 79
+    else
+        echo -n "."
+    fi
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $webspheremq_stack_name \
+if ! aws cloudformation describe-stacks --stack-name $environment-WebSphereMQ \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo
-    echo "Stack dependency missing - $webspheremq_stack_name Stack does not exist!"
+    echo "Stack dependency missing - $environment-WebSphereMQ Stack does not exist!"
     exit 80
 else
     echo -n "."
@@ -518,13 +520,12 @@ else
     echo -n "."
 fi
 
-if [ -n $datatransfer_sftp_stack_name ]; then
+if [ -n "$datatransfer_sftp_stack_name" ]; then
     if ! aws cloudformation describe-stacks --stack-name $datatransfer_sftp_stack_name \
                                             --profile $profile --region $region --output text &> /dev/null; then
         echo
         echo "Stack dependency missing - $datatransfer_sftp_stack_name Stack does not exist!"
-        #exit 83
-        echo "TODO: This needs to be added later and integrated with this Stack"
+        exit 83
     else
         echo -n "."
     fi
@@ -650,7 +651,7 @@ aws cloudformation create-stack --stack-name $environment-$application-$componen
                                              ParameterKey=DataTransferSFTPStackName,ParameterValue=$datatransfer_sftp_stack_name \\
                                              ParameterKey=MongoDBStackName,ParameterValue=$environment-MongoDB \\
                                              ParameterKey=RabbitMQStackName,ParameterValue=$environment-RabbitMQ \\
-                                             ParameterKey=WebSphereMQStackName,ParameterValue=$webspheremq_stack_name \\
+                                             ParameterKey=WebSphereMQStackName,ParameterValue=$environment-WebSphereMQ \\
                                              ParameterKey=OctopusDeployStackName,ParameterValue=$octopus_deploy_stack_name \\
                                              ParameterKey=VPNStackName,ParameterValue=$environment-OpenVPNAS \\
                                              ParameterKey=ActiveDirectoryStackName,ParameterValue=$environment-ActiveDirectory \\
diff --git a/application/bin/application-create-engine-publishing-stack b/application/bin/application-create-engine-publishing-stack
--- a/application/bin/application-create-engine-publishing-stack
+++ b/application/bin/application-create-engine-publishing-stack
@@ -231,7 +231,6 @@ if [ -z $environment ]; then
 else
     case $environment in
       Production)
-        webspheremq_stack_name=$environment-WebSphereMQ
         octopus_deploy_stack_name=$environment-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
@@ -239,7 +238,6 @@ else
         log_retention=30
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Staging)
-        webspheremq_stack_name=Core-WebSphereMQ
         octopus_deploy_stack_name=$environment-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
@@ -247,7 +245,6 @@ else
         log_retention=7
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Testing)
-        webspheremq_stack_name=Core-WebSphereMQ
         octopus_deploy_stack_name=Core-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
@@ -255,7 +252,6 @@ else
         log_retention=3
         schedule="13:00-2:00";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       Development)
-        webspheremq_stack_name=Core-WebSphereMQ
         octopus_deploy_stack_name=Core-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
@@ -478,19 +474,21 @@ else
     echo -n "."
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $octopus_deploy_stack_name \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo
-    echo "Stack dependency missing - $octopus_deploy_stack_name Stack does not exist!"
-    exit 79
-else
-    echo -n "."
+if [ -n "$octopus_deploy_stack_name" ]; then
+    if ! aws cloudformation describe-stacks --stack-name $octopus_deploy_stack_name \
+                                            --profile $profile --region $region --output text &> /dev/null; then
+        echo
+        echo "Stack dependency missing - $octopus_deploy_stack_name Stack does not exist!"
+        exit 79
+    else
+        echo -n "."
+    fi
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $webspheremq_stack_name \
+if ! aws cloudformation describe-stacks --stack-name $environment-WebSphereMQ \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo
-    echo "Stack dependency missing - $webspheremq_stack_name Stack does not exist!"
+    echo "Stack dependency missing - $environment-WebSphereMQ Stack does not exist!"
     exit 80
 else
     echo -n "."
@@ -633,7 +631,7 @@ aws cloudformation create-stack --stack-name $environment-$application-$componen
                                 --parameters ParameterKey=EngineMonitoringStackName,ParameterValue=$environment-Engine-Monitoring \\
                                              ParameterKey=MongoDBStackName,ParameterValue=$environment-MongoDB \\
                                              ParameterKey=RabbitMQStackName,ParameterValue=$environment-RabbitMQ \\
-                                             ParameterKey=WebSphereMQStackName,ParameterValue=$webspheremq_stack_name \\
+                                             ParameterKey=WebSphereMQStackName,ParameterValue=$environment-WebSphereMQ \\
                                              ParameterKey=OctopusDeployStackName,ParameterValue=$octopus_deploy_stack_name \\
                                              ParameterKey=VPNStackName,ParameterValue=$environment-OpenVPNAS \\
                                              ParameterKey=ActiveDirectoryStackName,ParameterValue=$environment-ActiveDirectory \\
