refactor CIDR Networks Parameter logic

diff --git a/application/bin/application-create-webspheremq-stack b/application/bin/application-create-webspheremq-stack
--- a/application/bin/application-create-webspheremq-stack
+++ b/application/bin/application-create-webspheremq-stack
@@ -20,7 +20,7 @@ next_default=5
 create_default=15
 create_attempts=40
 
-interactive=1
+interactive=0
 speed=100
 verbose=0
 monitor=0
@@ -31,12 +31,8 @@ environment=${ENVIRONMENT_NAME:-Production}
 environment_type=${ENVIRONMENT_TYPE:-large}
 application=${APPLICATION_NAME:-WebSphereMQ}
 application_version=${APPLICATION_VERSION:-1.0.0}
-private_user_network=${PRIVATE_USER_NETWORK:-10.0.0.0/16}
-private_user_network1=${PRIVATE_USER_NETWORK1:-}
-private_user_network2=${PRIVATE_USER_NETWORK2:-}
-private_administrator_network=${PRIVATE_ADMINISTRATOR_NETWORK:-10.0.0.0/16}
-private_administrator_network1=${PRIVATE_ADMINISTRATOR_NETWORK1:-}
-private_administrator_network2=${PRIVATE_ADMINISTRATOR_NETWORK2:-}
+administrator_networks=${WEBSPHEREMQ_ADMINISTRATOR_NETWORKS:-NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
+integration_networks=${WEBSPHEREMQ_INTEGRATION_NETWORKS:-NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -46,13 +42,13 @@ key=${AWS_KEY_NAME:-user}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-m]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m]"
     echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment] [-T type]"
     echo "                  [-A application] [-V version]"
-    echo "                  [-n network] [-N network]"
+    echo "                  [-N networks] [-I networks]"
     echo "                  [-r region] [-a account] [-u user] [-k key]"
-    echo "  -I              non-interactive"
+    echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
@@ -64,8 +60,8 @@ usage () {
     echo "  -T type         Environment Type (default: $environment_type)"
     echo "  -A application  Application Name (default: $application)"
     echo "  -V version      Application Version (default: $application_version)"
-    echo "  -n network      Private User Network (default: $private_user_network)"
-    echo "  -N network      Private Administrator Network (default: $private_administrator_network)"
+    echo "  -N networks     Administrator Networks (default: $administrator_networks)"
+    echo "  -I networks     Integration Networks (default: $integration_networks)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -151,11 +147,10 @@ next() {
 
 
 #  3. Parse command line options
-#     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvmO:C:S:E:T:A:V:n:5:6:N:7:8:r:a:u:k:? arg; do
+while getopts isfvmO:C:S:E:T:A:V:N:I:r:a:u:k:? arg; do
     case $arg in
-    I)  interactive=0;;
+    i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
@@ -167,12 +162,8 @@ while getopts IsfvmO:C:S:E:T:A:V:n:5:6:N:7:8:r:a:u:k:? arg; do
     T)  environment_type="$OPTARG";;
     A)  application="$OPTARG";;
     V)  application_version="$OPTARG";;
-    n)  private_user_network="$OPTARG";;
-    5)  private_user_network1="$OPTARG";;
-    6)  private_user_network2="$OPTARG";;
-    N)  private_administrator_network="$OPTARG";;
-    7)  private_administrator_network1="$OPTARG";;
-    8)  private_administrator_network2="$OPTARG";;
+    N)  administrator_networks="$OPTARG";;
+    I)  integration_networks="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -298,17 +289,16 @@ if [ -z $application_version ]; then
     exit 34
 fi
 
-
-if [ -z $private_user_network ]; then
-    echo "-n network missing!"
-    echo "Could not automatically determine private user network, and it was not specified as a parameter"
-    exit 44
+if [ -z $administrator_networks ]; then
+    echo "-N networks missing!"
+    echo "Could not automatically determine administrator networks, and it was not specified as a parameter"
+    exit 42
 fi
 
-if [ -z $private_administrator_network ]; then
-    echo "-N network missing!"
-    echo "Could not automatically determine private administrator network, and it was not specified as a parameter"
-    exit 46
+if [ -z $integration_networks ]; then
+    echo "-I networks missing!"
+    echo "Could not automatically determine integration networks, and it was not specified as a parameter"
+    exit 44
 fi
 
 if [ -z $region ]; then
@@ -509,12 +499,8 @@ aws cloudformation create-stack --stack-name $environment-$application \\
                                              ParameterKey=UseFileSystemMonitoring,ParameterValue=$use_filesystem_monitoring \\
                                              ParameterKey=LogRetention,ParameterValue=$log_retention \\
                                              ParameterKey=Schedule,ParameterValue=$schedule \\
-                                             ParameterKey=PrivateUserNetwork,ParameterValue=$private_user_network \\
-                                             ParameterKey=PrivateUserNetwork1,ParameterValue=$private_user_network1 \\
-                                             ParameterKey=PrivateUserNetwork2,ParameterValue=$private_user_network2 \\
-                                             ParameterKey=PrivateAdministratorNetwork,ParameterValue=$private_administrator_network \\
-                                             ParameterKey=PrivateAdministratorNetwork1,ParameterValue=$private_administrator_network1 \\
-                                             ParameterKey=PrivateAdministratorNetwork2,ParameterValue=$private_administrator_network2 \\
+                                             ParameterKey=AdministratorNetworks,ParameterValue=\"$administrator_networks\" \\
+                                             ParameterKey=IntegrationNetworks,ParameterValue=\"$integration_networks\" \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
