changes to Engine - remove Deploy, adjust instancetypes, change to use of EnvironmentType and EnvironmentZones

diff --git a/application/bin/application-update-engine-stack b/application/bin/application-update-engine-stack
--- a/application/bin/application-update-engine-stack
+++ b/application/bin/application-update-engine-stack
@@ -24,16 +24,15 @@ interactive=1
 speed=100
 verbose=0
 override=0
-dummy=0
 owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
-environment_size=${ENVIRONMENT_SIZE:-medium}
+environment_type=${ENVIRONMENT_TYPE:-large}
+environment_zones=${ENVIRONMENT_ZONES:-2}
 application=${APPLICATION_NAME:-Engine}
 application_domain=${APPLICATION_DOMAIN:-engine}
 application_version=${APPLICATION_VERSION:-1.0.0}
-key=${AWS_KEY_NAME:-user}
 public_user_network=${PUBLIC_USER_NETWORK:-0.0.0.0/0}
 public_user_network1=${PUBLIC_USER_NETWORK1:-}
 public_user_network2=${PUBLIC_USER_NETWORK2:-}
@@ -46,6 +45,7 @@ private_administrator_network2=${PRIVATE_ADMINISTRATOR_NETWORK2:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
+key=${AWS_KEY_NAME:-user}
 
 
 #  2. Define functions
@@ -53,12 +53,11 @@ user=${AWS_USER_NAME:-administrator}
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o]"
     echo "                  [-O owner] [-C company ] [-S system]"
-    echo "                  [-E environment] [-Z size]"
+    echo "                  [-E environment] [-T type] [-Z zones]"
     echo "                  [-A application ] [-D domain] [-V version]"
-    echo "                  [-k key]"
     echo "                  [-p network]"
     echo "                  [-n network] [-N network ]"
-    echo "                  [-r region ] [-a account] [-u user]"
+    echo "                  [-r region ] [-a account] [-u user] [-k key]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -68,17 +67,18 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -Z size         Environment Size (default: $environment_size)"
+    echo "  -T type         Environment Type (default: $environment_type)"
+    echo "  -Z zones        Environment Zones (default: $environment_zones)"
     echo "  -A application  Application Name (default: $application)"
     echo "  -D domain       Application Domain (default: $application_domain)"
     echo "  -V version      Application Version (default: $application_version)"
-    echo "  -k key          Key (default: $key)"
     echo "  -p network      Public User Network (default: $public_user_network)"
     echo "  -n network      Private User Network (default: $private_user_network)"
     echo "  -N network      Private Administrator Network (default: $private_administrator_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
+    echo "  -k key          Key (default: $key)"
 }
 
 run() {
@@ -162,7 +162,7 @@ next() {
 #  3. Parse command line options
 #     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvO:C:S:E:Z:A:D:V:k:p:1:2:n:5:6:N:7:8:r:a:u:? arg; do
+while getopts IsfvoO:C:S:E:Z:A:D:T:V:p:1:2:n:5:6:N:7:8:r:a:u:k:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -173,11 +173,11 @@ while getopts IsfvO:C:S:E:Z:A:D:V:k:p:1:2:n:5:6:N:7:8:r:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    Z)  environment_size="$OPTARG";;
+    T)  environment_type="$OPTARG";;
+    Z)  environment_zones="$OPTARG";;
     A)  application="$OPTARG";;
     D)  application_domain="$OPTARG";;
     V)  application_version="$OPTARG";;
-    k)  key="$OPTARG";;
     p)  public_user_network="$OPTARG";;
     1)  public_user_network1="$OPTARG";;
     2)  public_user_network2="$OPTARG";;
@@ -190,6 +190,7 @@ while getopts IsfvO:C:S:E:Z:A:D:V:k:p:1:2:n:5:6:N:7:8:r:a:u:? arg; do
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
+    k)  key="$OPTARG";;
     ?)  usage
         exit 1;;
     esac
@@ -237,7 +238,7 @@ fi
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
+    exit 20
 else
     case $environment in
       Production)
@@ -266,54 +267,62 @@ else
         schedule="";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       *)
         echo "-E $environment invalid! Must be Production, Staging, Testing or Development"
-        exit 17;;
+        exit 21;;
     esac
 fi
 
-if [ -z $environment_size ]; then
-    echo "-Z size missing!"
-    echo "Could not automatically determine size, and it was not specified as a parameter"
-    exit 18
+if [ -z $environment_type ]; then
+    echo "-T type missing!"
+    echo "Could not automatically determine environment type, and it was not specified as a parameter"
+    exit 22
 else
-    case $environment_size in
+    case $environment_type in
       small|medium|large|xlarge)
         ;;
       *)
-        echo "-Z $environment_size invalid! Must be small, medium, large or xlarge"
-        exit 19;;
+        echo "-T $environment_type invalid! Must be small, medium, large or xlarge"
+        exit 23;;
+    esac
+fi
+
+if [ -z $environment_zones ]; then
+    echo "-Z zones missing!"
+    echo "Could not automatically determine environment zones, and it was not specified as a parameter"
+    exit 24
+else
+    case $environment_zones in
+      1|2)
+        ;;
+      *)
+        echo "-Z $environment_zones invalid! Must be 1 or 2"
+        exit 25;;
     esac
 fi
 
 if [ -z $application ]; then
     echo "-A application missing!"
     echo "Could not automatically determine application, and it was not specified as a parameter"
-    exit 20
+    exit 30
 else
     case $application in
       Engine)
         ;;
       *)
         echo "-A $application invalid! Must be Engine"
-        exit 21;;
+        exit 31;;
     esac
 fi
 
 if [ -z $application_domain ]; then
     echo "-D domain missing!"
     echo "Could not automatically determine domain, and it was not specified as a parameter"
-    exit 22
+    exit 32
 fi
 
 if [ -z $application_version ]; then
     echo "-V version missing!"
     echo "Could not automatically determine version, and it was not specified as a parameter"
-    exit 24
-fi
-
-if [ -z $key ]; then
-    echo "-k key missing!"
-    echo "Could not automatically determine key, and it was not specified as a parameter"
-    exit 30
+    exit 34
 fi
 
 if [ -z $public_user_network ]; then
@@ -362,21 +371,28 @@ if [ -z $user ]; then
     exit 54
 fi
 
+if [ -z $key ]; then
+    echo "-k key missing!"
+    echo "Could not automatically determine key, and it was not specified as a parameter"
+    exit 56
+fi
+
 profile=$account-$user
 
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
+    exit 58
+fi
+
+if ! aws cloudformation describe-stacks --stack-name $environment-$application \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo "Unable to update - $environment-$application Stack does not exist!"
+    exit 80
 fi
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
 template_folder=application
-
-if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
-    echo "$templates_bucket S3 bucket does not exist!"
-    exit 62
-fi
 
 # Not sure how this will work yet, so leaving as placeholder
 products_bucket=${AWS_PRODUCTS_BUCKET:-products-$region-$account}
@@ -386,20 +402,13 @@ product_folder=Engine
 #rabbitmq_product_object=Engine-RabbitMQ-Unknown.zip
 #datastaging_product_object=Engine-DataStaging-Unknown.zip
 #logging_product_object=Engine-Logging-Unknown.zip
-#deployment_product_object=Engine-Deployment-Unknown.zip
-#publish_product_object=Engine-Publish-Unknown.zip
+#publishing_product_object=Engine-Publishing-Unknown.zip
 calculation_product_object=""
 mongodb_product_object=""
 rabbitmq_product_object=""
 datastaging_product_object=""
 logging_product_object=""
-deployment_product_object=""
-publish_product_object=""
-
-if ! aws s3api head-bucket --bucket $products_bucket --profile $profile --region $region 2> /dev/null; then
-    echo "$products_bucket S3 bucket does not exist!"
-    exit 64
-fi
+publishing_product_object=""
 
 # Not sure how this will work yet, so leaving as placeholder
 configurations_bucket=${AWS_CONFIGURATIONS_BUCKET:-configurations-$region-$account}
@@ -410,21 +419,14 @@ configuration_folder=Engine
 #rabbitmq_configuration_object=$environment-Engine-RabbitMQ.zip
 #datastaging_configuration_object=$environment-Engine-DataStaging.zip
 #logging_configuration_object=$environment-Engine-Logging.zip
-#deplpyment_configuration_object=$environment-Engine-Deployment.zip
-#publish_configuration_object=$environment-Engine-Publish.zip
+#publishing_configuration_object=$environment-Engine-Publishing.zip
 web_configuration_object=""
 calculation_configuration_object=""
 mongodb_configuration_object=""
 rabbitmq_configuration_object=""
 datastaging_configuration_object=""
 logging_configuration_object=""
-deplpyment_configuration_object=""
-publish_configuration_object=""
-
-if ! aws s3api head-bucket --bucket $configurations_bucket --profile $profile --region $region 2> /dev/null; then
-    echo "$configurations_bucket S3 bucket does not exist!"
-    exit 66
-fi
+publishing_configuration_object=""
 
 # Not sure how this will work yet, so leaving as placeholder
 applications_bucket=${AWS_APPLICATIONS_BUCKET:-applications-$region-$account}
@@ -435,27 +437,14 @@ application_folder=Engine
 #rabbitmq_application_object=Engine-RabbitMQ-$application_version.zip
 #datastaging_application_object=Engine-DataStaging-$application_version.zip
 #logging_application_object=Engine-Logging-$application_version.zip
-#deployment_application_object=Engine-Deployment-$application_version.zip
-#publish_application_object=Engine-Publish-$application_version.zip
+#publishing_application_object=Engine-Publishing-$application_version.zip
 web_application_object=""
 calculation_application_object=""
 mongodb_application_object=""
 rabbitmq_application_object=""
 datastaging_application_object=""
 logging_application_object=""
-deployment_application_object=""
-publish_application_object=""
-
-if ! aws s3api head-bucket --bucket $applications_bucket --profile $profile --region $region 2> /dev/null; then
-    echo "$applications_bucket S3 bucket does not exist!"
-    exit 68
-fi
-
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - $environment-$application Stack does not exist!"
-    exit 70
-fi
+publishing_application_object=""
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -516,8 +505,7 @@ aws s3 sync $templatesdir \\
             --include 'Application-Engine-RabbitMQInstances.json' \\
             --include 'Application-Engine-DataStagingInstances.json' \\
             --include 'Application-Engine-LoggingInstances.json' \\
-            --include 'Application-Engine-DeploymentInstances.json' \\
-            --include 'Application-Engine-PublishInstances.json' \\
+            --include 'Application-Engine-PublishingInstances.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -545,11 +533,6 @@ next 50
 
 
 ((++step))
-if [ $dummy = 1 ]; then
-    # unset download location, which triggers creation of dummy application page within the template
-    unset applications_bucket
-fi
-
 template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Application-Engine.json"
 stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Application-Engine-StackPolicy.json"
 if [ $override = 1 ]; then
@@ -564,25 +547,23 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                              ParameterKey=CustomIdentifierFunctionsStackName,ParameterValue=CustomIdentifierFunctions \\
                                              ParameterKey=StandardCIDRFunctionsStackName,ParameterValue=StandardCIDRFunctions \\
                                              ParameterKey=StandardAMIFunctionsStackName,ParameterValue=StandardAMIFunctions \\
+                                             ParameterKey=StandardBucketsStackName,ParameterValue=StandardBuckets \\
                                              ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
-                                             ParameterKey=TemplatesBucket,ParameterValue=$templates_bucket \\
                                              ParameterKey=TemplateFolder,ParameterValue=$template_folder \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
-                                             ParameterKey=EnvironmentSize,ParameterValue=$environment_size \\
+                                             ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
+                                             ParameterKey=EnvironmentZones,ParameterValue=$environment_zones \\
                                              ParameterKey=LinuxOSName,ParameterValue="$linux_os_name" \\
                                              ParameterKey=WindowsOSName,ParameterValue="$windows_os_name" \\
-                                             ParameterKey=ProductsBucket,ParameterValue=$products_bucket \\
                                              ParameterKey=ProductFolder,ParameterValue=$product_folder \\
                                              ParameterKey=CalculationProductObject,ParameterValue=$calculation_product_object \\
                                              ParameterKey=MongoDBProductObject,ParameterValue=$mongodb_product_object \\
                                              ParameterKey=RabbitMQProductObject,ParameterValue=$rabbitmq_product_object \\
                                              ParameterKey=DataStagingProductObject,ParameterValue=$datastaging_product_object \\
                                              ParameterKey=LoggingProductObject,ParameterValue=$logging_product_object \\
-                                             ParameterKey=DeploymentProductObject,ParameterValue=$deployment_product_object \\
-                                             ParameterKey=PublishProductObject,ParameterValue=$publish_product_object \\
-                                             ParameterKey=ConfigurationsBucket,ParameterValue=$configurations_bucket \\
+                                             ParameterKey=PublishingProductObject,ParameterValue=$publishing_product_object \\
                                              ParameterKey=ConfigurationFolder,ParameterValue=$configuration_folder \\
                                              ParameterKey=WebConfigurationObject,ParameterValue=$web_configuration_object \\
                                              ParameterKey=CalculationConfigurationObject,ParameterValue=$calculation_configuration_object \\
@@ -590,9 +571,7 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                              ParameterKey=RabbitMQConfigurationObject,ParameterValue=$rabbitmq_configuration_object \\
                                              ParameterKey=DataStagingConfigurationObject,ParameterValue=$datastaging_configuration_object \\
                                              ParameterKey=LoggingConfigurationObject,ParameterValue=$logging_configuration_object \\
-                                             ParameterKey=DeploymentConfigurationObject,ParameterValue=$deployment_configuration_object \\
-                                             ParameterKey=PublishConfigurationObject,ParameterValue=$publish_configuration_object \\
-                                             ParameterKey=ApplicationsBucket,ParameterValue=$applications_bucket \\
+                                             ParameterKey=PublishingConfigurationObject,ParameterValue=$publishing_configuration_object \\
                                              ParameterKey=ApplicationFolder,ParameterValue=$application_folder \\
                                              ParameterKey=WebApplicationObject,ParameterValue=$eng_web_application_object \\
                                              ParameterKey=CalculationApplicationObject,ParameterValue=$calculation_application_object \\
@@ -600,8 +579,7 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                              ParameterKey=RabbitMQApplicationObject,ParameterValue=$rabbitmq_application_object \\
                                              ParameterKey=DataStagingApplicationObject,ParameterValue=$datastaging_application_object \\
                                              ParameterKey=LoggingApplicationObject,ParameterValue=$logging_application_object \\
-                                             ParameterKey=DeploymentApplicationObject,ParameterValue=$deployment_application_object \\
-                                             ParameterKey=PublishApplicationObject,ParameterValue=$publish_application_object \\
+                                             ParameterKey=PublishingApplicationObject,ParameterValue=$publish_application_object \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
                                              ParameterKey=ApplicationDomain,ParameterValue=$application_domain \\
                                              ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
