Final improvements and bug fixes prior to handover release (#13)
* fix cross-environment / optional stack dependencies
* replace Production/Staging FederatedSecurity Stack dependency with null and TODO to restore later, as this Application will not be implemented soon
* add logic to create a client-only variant of WebSphereMQ, needed to handle shared use of a Core-based Application
* adjustments to use client WebSphere Stack, fix some small bugs
* remove unnecessary reference to WebSphereMQ Stack; fix small bugs in stack check
* add new changes to how WebSphereMQ client-only stacks work, reserve space for upcoming DataStaging Stacks
* update sequence scripts to add new WebSphereMQ-Client Stacks, reserve space for future DataStaging
* update GetHostName Lambda to make CompanyCode optional

diff --git a/application/bin/application-create-engine-datastaging-stack b/application/bin/application-create-engine-datastaging-stack
--- a/application/bin/application-create-engine-datastaging-stack
+++ b/application/bin/application-create-engine-datastaging-stack
@@ -231,24 +231,36 @@ if [ -z $environment ]; then
 else
     case $environment in
       Production)
+        # TODO: Currently, the DataTransfer Application has not yet been implemented
+        #datatransfer_sftp_stack_name=$environment-DataTransfer-SFTP
+        unset datatransfer_sftp_stack_name
+        octopus_deploy_stack_name=$environment-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
         use_static_address=false
         log_retention=30
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Staging)
+        # TODO: Currently, the DataTransfer Application has not yet been implemented
+        #datatransfer_sftp_stack_name=Core-DataTransfer-SFTP
+        unset datatransfer_sftp_stack_name
+        octopus_deploy_stack_name=$environment-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
         use_static_address=false
         log_retention=7
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Testing)
+        unset datatransfer_sftp_stack_name
+        octopus_deploy_stack_name=Core-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
         use_static_address=false
         log_retention=3
         schedule="13:00-2:00";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       Development)
+        unset datatransfer_sftp_stack_name
+        octopus_deploy_stack_name=Core-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
         use_static_address=false
@@ -470,13 +482,15 @@ else
     echo -n "."
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $environment-Octopus-Deploy \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo
-    echo "Stack dependency missing - $environment-Octopus-Deploy Stack does not exist!"
-    exit 79
-else
-    echo -n "."
+if [ -n "$octopus_deploy_stack_name" ]; then
+    if ! aws cloudformation describe-stacks --stack-name $octopus_deploy_stack_name \
+                                            --profile $profile --region $region --output text &> /dev/null; then
+        echo
+        echo "Stack dependency missing - $octopus_deploy_stack_name Stack does not exist!"
+        exit 79
+    else
+        echo -n "."
+    fi
 fi
 
 if ! aws cloudformation describe-stacks --stack-name $environment-WebSphereMQ \
@@ -506,14 +520,15 @@ else
     echo -n "."
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $environment-DataTransfer-SFTP \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo
-    echo "Stack dependency missing - $environment-DataTransfer-SFTP Stack does not exist!"
-#    exit 83
-    echo "TODO: This needs to be added later and integrated with this Stack"
-else
-    echo -n "."
+if [ -n "$datatransfer_sftp_stack_name" ]; then
+    if ! aws cloudformation describe-stacks --stack-name $datatransfer_sftp_stack_name \
+                                            --profile $profile --region $region --output text &> /dev/null; then
+        echo
+        echo "Stack dependency missing - $datatransfer_sftp_stack_name Stack does not exist!"
+        exit 83
+    else
+        echo -n "."
+    fi
 fi
 
 if ! aws cloudformation describe-stacks --stack-name $environment-Engine-Monitoring \
@@ -633,11 +648,11 @@ aws cloudformation create-stack --stack-name $environment-$application-$componen
                                 $template_parameter \\
                                 $stack_policy_parameter \\
                                 --parameters ParameterKey=EngineMonitoringStackName,ParameterValue=$environment-Engine-Monitoring \\
-                                             ParameterKey=DataTransferSFTPStackName,ParameterValue= \\
+                                             ParameterKey=DataTransferSFTPStackName,ParameterValue=$datatransfer_sftp_stack_name \\
                                              ParameterKey=MongoDBStackName,ParameterValue=$environment-MongoDB \\
                                              ParameterKey=RabbitMQStackName,ParameterValue=$environment-RabbitMQ \\
                                              ParameterKey=WebSphereMQStackName,ParameterValue=$environment-WebSphereMQ \\
-                                             ParameterKey=OctopusDeployStackName,ParameterValue=$environment-Octopus-Deploy \\
+                                             ParameterKey=OctopusDeployStackName,ParameterValue=$octopus_deploy_stack_name \\
                                              ParameterKey=VPNStackName,ParameterValue=$environment-OpenVPNAS \\
                                              ParameterKey=ActiveDirectoryStackName,ParameterValue=$environment-ActiveDirectory \\
                                              ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
diff --git a/application/bin/application-create-engine-monitoring-stack b/application/bin/application-create-engine-monitoring-stack
--- a/application/bin/application-create-engine-monitoring-stack
+++ b/application/bin/application-create-engine-monitoring-stack
@@ -228,24 +228,28 @@ if [ -z $environment ]; then
 else
     case $environment in
       Production)
+        octopus_deploy_stack_name=$environment-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
         use_static_address=false
         log_retention=30
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Staging)
+        octopus_deploy_stack_name=$environment-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
         use_static_address=false
         log_retention=7
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Testing)
+        octopus_deploy_stack_name=Core-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
         use_static_address=false
         log_retention=3
         schedule="13:00-2:00";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       Development)
+        octopus_deploy_stack_name=Core-Octopus-Deploy
         os_name="Windows Server 2012 R2"
         os_date="20170614"
         use_static_address=false
@@ -453,13 +457,15 @@ else
     echo -n "."
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $environment-Octopus-Deploy \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo
-    echo "Stack dependency missing - $environment-Octopus-Deploy Stack does not exist!"
-    exit 79
-else
-    echo -n "."
+if [ -n "$octopus_deploy_stack_name" ]; then
+    if ! aws cloudformation describe-stacks --stack-name $octopus_deploy_stack_name \
+                                            --profile $profile --region $region --output text &> /dev/null; then
+        echo
+        echo "Stack dependency missing - $octopus_deploy_stack_name Stack does not exist!"
+        exit 79
+    else
+        echo -n "."
+    fi
 fi
 echo " Done"
 sleep 1
@@ -569,7 +575,7 @@ read -r -d '' statement << EOS
 aws cloudformation create-stack --stack-name $environment-$application-$component \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=OctopusDeployStackName,ParameterValue=$environment-Octopus-Deploy \\
+                                --parameters ParameterKey=OctopusDeployStackName,ParameterValue=$octopus_deploy_stack_name \\
                                              ParameterKey=VPNStackName,ParameterValue=$environment-OpenVPNAS \\
                                              ParameterKey=ActiveDirectoryStackName,ParameterValue=$environment-ActiveDirectory \\
                                              ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
diff --git a/application/bin/application-create-webspheremq-stack b/application/bin/application-create-webspheremq-stack
--- a/application/bin/application-create-webspheremq-stack
+++ b/application/bin/application-create-webspheremq-stack
@@ -1,6 +1,8 @@
 #!/bin/bash
 #
-# This script creates the Application WebSphereMQ Stack in an Environment Account.
+# This script creates the Application WebSphereMQ Stack in an Environment Account,
+# or, a variant of the Application WebSphereMQ Stack containing only Client-related
+# Resources, connected to an existing shared WebSphereMQ Stack in a different VPC.
 #
 
 #  1. Initalize Environment
@@ -217,6 +219,7 @@ if [ -z $environment ]; then
 else
     case $environment in
       Production)
+        unset webspheremq_stack_name
         os_name="RHEL 7.3"
         os_date="20161026"
         use_static_address=false
@@ -224,6 +227,7 @@ else
         log_retention=30
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Staging)
+        webspheremq_stack_name=Core-WebSphereMQ
         os_name="RHEL 7.3"
         os_date="20161026"
         use_static_address=false
@@ -231,6 +235,7 @@ else
         log_retention=7
         schedule="";;  # 11:00 - 4:00 UTC = 3:00 AM - 8:00 PM PST = 6:00 AM - 11:00 PM EST
       Testing)
+        webspheremq_stack_name=Core-WebSphereMQ
         os_name="RHEL 7.3"
         os_date="20161026"
         use_static_address=false
@@ -238,6 +243,7 @@ else
         log_retention=0
         schedule="13:00-2:00";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       Development)
+        webspheremq_stack_name=Core-WebSphereMQ
         os_name="RHEL 7.3"
         os_date="20161026"
         use_static_address=false
@@ -245,6 +251,7 @@ else
         log_retention=0
         schedule="";; # 13:00 - 2:00 UTC = 5:00 AM - 6:00 PM PST = 8:00 AM - 9:00 PM EST
       Core)
+        unset webspheremq_stack_name
         os_name="RHEL 7.3"
         os_date="20161026"
         use_static_address=false
@@ -409,6 +416,19 @@ if ! aws cloudformation describe-stacks --stack-name $environment-OpenVPNAS \
 else
     echo -n "."
 fi
+
+# If the webspheremq_stack_name variable is set, this means we should create a client stack which will
+# integrate with an existing WebSphereMQ Application Stack which already exists in a different VPC/Environment
+if [ -n "$webspheremq_stack_name" ]; then
+    if ! aws cloudformation describe-stacks --stack-name $webspheremq_stack_name \
+                                            --profile $profile --region $region --output text &> /dev/null; then
+        echo
+        echo "Stack dependency missing - $webspheremq_stack_name Stack does not exist!"
+        exit 80
+    else
+        echo -n "."
+    fi
+fi
 echo " Done"
 sleep 1
 
@@ -479,6 +499,7 @@ read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
             s3://$templates_bucket/$template_folder \\
             --exclude '*' --include 'Application-WebSphereMQ.json' --include 'Application-WebSphereMQ-StackPolicy.json' \\
+                          --include 'Application-WebSphereMQ-Client.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -552,6 +573,26 @@ EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'}"
 
+client_template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Application-WebSphereMQ-Client.json"
+read -r -d '' client_statement << EOS
+aws cloudformation create-stack --stack-name $environment-$application \\
+                                $client_template_parameter \\
+                                $stack_policy_parameter \\
+                                --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
+                                             ParameterKey=WebSphereMQStackName,ParameterValue=$webspheremq_stack_name \\
+                                             ParameterKey=ApplicationName,ParameterValue=$application \\
+                                --tags Key=Owner,Value=$owner \\
+                                       Key=Company,Value=$company \\
+                                       Key=System,Value=$system \\
+                                       Key=Environment,Value=$environment \\
+                                       Key=Application,Value=$application \\
+                                --capabilities CAPABILITY_IAM \\
+                                --disable-rollback \\
+                                --profile $profile --region $region --output table
+EOS
+run_client_statement=$(echo "$client_statement" | sed -e '1s/^/# /;2,$ s/^/> /')
+eval_client_statement="${client_statement//\\$'\n'}"
+
 clear
 echo
 echo "============================================================"
@@ -562,7 +603,11 @@ echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "$statement"
+if [ -z "$webspheremq_stack_name" ]; then
+    echo "$statement"
+else
+    echo "$client_statement"
+fi
 
 if aws cloudformation describe-stacks --stack-name $environment-$application \
                                       --profile $profile --region $region --output text &> /dev/null; then
@@ -578,8 +623,13 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "$run_statement"
-        eval "$eval_statement"
+        if [ -z "$webspheremq_stack_name" ]; then
+            echo "$run_statement"
+            eval "$eval_statement"
+        else
+            echo "$run_client_statement"
+            eval "$eval_client_statement"
+        fi
 
         next
     fi
