Improvements and standardization of parameters

diff --git a/utility/bin/utility-create-linuxbastions-stack b/utility/bin/utility-create-linuxbastions-stack
--- a/utility/bin/utility-create-linuxbastions-stack
+++ b/utility/bin/utility-create-linuxbastions-stack
@@ -27,13 +27,18 @@ owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
+environment_size=${ENVIRONMENT_SIZE:-micro}
 utility=${UTILITY_NAME:-LinuxBastions}
 utility_domain=${UTILITY_DOMAIN:-lbastion}
 key=${AWS_KEY_NAME:-example}
 public_network=${PUBLIC_NETWORK:-0.0.0.0/0}
 public_network1=${PUBLIC_NETWORK1:-}
+public_network2=${PUBLIC_NETWORK2:-}
+public_network3=${PUBLIC_NETWORK3:-}
 private_network=${PRIVATE_NETWORK:-10.0.0.0/16}
 private_network1=${PRIVATE_NETWORK1:-}
+private_network2=${PRIVATE_NETWORK2:-}
+private_network3=${PRIVATE_NETWORK3:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -44,7 +49,7 @@ user=${AWS_USER_NAME:-administrator}
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
     echo "                  [-O owner] [-C company ] [-S system]"
-    echo "                  [-E environment]"
+    echo "                  [-E environment] [-Z size]"
     echo "                  [-U utility] [-D domain]"
     echo "                  [-k key]"
     echo "                  [-p network] [-P network ]"
@@ -57,6 +62,7 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
+    echo "  -Z size         Environment Size (default: $environment_size)"
     echo "  -U utility      Utility Name (default: $utility)"
     echo "  -D domain       Utility Domain (default: $utility_domain)"
     echo "  -k key          Key (default: $key)"
@@ -146,8 +152,9 @@ next() {
 
 
 #  3. Parse command line options
+#     - Note, using options 1-9 as hidden options to set additional network ranges
 
-while getopts IsfvO:C:S:E:U:D:k:p:P:r:a:u:? arg; do
+while getopts IsfvO:C:S:E:Z:U:D:k:p:4:5:6:P:7:8:9:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -157,11 +164,18 @@ while getopts IsfvO:C:S:E:U:D:k:p:P:r:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
+    Z)  environment_size="$OPTARG";;
     U)  utility="$OPTARG";;
     D)  utility_domain="$OPTARG";;
     k)  key="$OPTARG";;
     p)  public_network="$OPTARG";;
+    4)  public_network1="$OPTARG";;
+    5)  public_network2="$OPTARG";;
+    6)  public_network3="$OPTARG";;
     P)  private_network="$OPTARG";;
+    7)  private_network1="$OPTARG";;
+    8)  private_network2="$OPTARG";;
+    9)  private_network3="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -200,55 +214,75 @@ if [ -z $environment ]; then
 else
     case $environment in
       Production)
-        environment_size=medium
         usemultizone=true
         usestaticpublicaddress=true
         usestaticprivateaddress=true
         uselogmonitoring=true
-        uselocalusers=true;;
+        uselocalusers=true
+        useschedule=false
+        starttime=11 # 11:00 UTC = 3:00 AM PST = 6:00 AM EST
+        stoptime=4;; # 4:00 UTC = 8:00 PM PST = 11:00 PM EST
       Staging)
-        environment_size=small
         usemultizone=false
         usestaticpublicaddress=true
         usestaticprivateaddress=true
         uselogmonitoring=true
-        uselocalusers=true;;
+        uselocalusers=true
+        useschedule=true
+        starttime=13 # 13:00 UTC = 5:00 AM PST = 8:00 AM EST
+        stoptime=2;; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST
       Testing)
-        environment_size=micro
         usemultizone=false
         usestaticpublicaddress=true
         usestaticprivateaddress=true
         uselogmonitoring=true
-        uselocalusers=true;;
+        uselocalusers=true
+        useschedule=true
+        starttime=13 # 13:00 UTC = 5:00 AM PST = 8:00 AM EST
+        stoptime=2;; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST
       Development)
-        environment_size=micro
         usemultizone=false
         usestaticpublicaddress=true
         usestaticprivateaddress=true
         uselogmonitoring=true
-        uselocalusers=true;;
+        uselocalusers=true
+        useschedule=true
+        starttime=13 # 13:00 UTC = 5:00 AM PST = 8:00 AM EST
+        stoptime=2;; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST
       Core)
-        environment_size=micro
         usemultizone=false
         usestaticpublicaddress=true
         usestaticprivateaddress=true
         uselogmonitoring=true
-        uselocalusers=true;;
+        uselocalusers=true
+        useschedule=true
+        starttime=11 # 11:00 UTC = 3:00 AM PST = 6:00 AM EST
+        stoptime=4;; # 4:00 UTC = 8:00 PM PST = 11:00 PM EST
       Build)
-        environment_size=micro
         usemultizone=false
         usestaticpublicaddress=true
         usestaticprivateaddress=true
         uselogmonitoring=true
-        uselocalusers=true;;
+        uselocalusers=true
+        useschedule=true
+        starttime=13 # 13:00 UTC = 5:00 AM PST = 8:00 AM EST
+        stoptime=2;; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST
       *)
-        environment_size=micro
         usemultizone=false
         usestaticpublicaddress=true
         usestaticprivateaddress=true
         uselogmonitoring=true
-        uselocalusers=true;;
+        uselocalusers=true
+        useschedule=true
+        starttime=13 # 13:00 UTC = 5:00 AM PST = 8:00 AM EST
+        stoptime=2;; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST
     esac
+fi
+
+if [ -z $environment_size ]; then
+    echo "-Z size missing!"
+    echo "Could not automatically determine size, and it was not specified as a parameter"
+    exit 18
 fi
 
 if [ -z $utility ]; then
@@ -422,6 +456,8 @@ aws cloudformation create-stack --stack-name $environment-$utility \\
                                 --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
                                              ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
+                                             ParameterKey=CompanyName,ParameterValue=$company \\
+                                             ParameterKey=SystemName,ParameterValue=$system \\
                                              ParameterKey=EnvironmentSize,ParameterValue=$environment_size \\
                                              ParameterKey=UtilityName,ParameterValue=$utility \\
                                              ParameterKey=UtilityDomain,ParameterValue=$utility_domain \\
@@ -430,9 +466,17 @@ aws cloudformation create-stack --stack-name $environment-$utility \\
                                              ParameterKey=UseStaticPrivateAddress,ParameterValue=$usestaticprivateaddress \\
                                              ParameterKey=UseLogMonitoring,ParameterValue=$uselogmonitoring \\
                                              ParameterKey=UseLocalUsers,ParameterValue=$uselocalusers \\
+                                             ParameterKey=UseSchedule,ParameterValue=$useschedule \\
+                                             ParameterKey=StartTime,ParameterValue=$starttime \\
+                                             ParameterKey=StopTime,ParameterValue=$stoptime \\
                                              ParameterKey=PublicNetwork,ParameterValue=$public_network \\
+                                             ParameterKey=PublicNetwork1,ParameterValue=$public_network1 \\
+                                             ParameterKey=PublicNetwork2,ParameterValue=$public_network2 \\
+                                             ParameterKey=PublicNetwork3,ParameterValue=$public_network3 \\
                                              ParameterKey=PrivateNetwork,ParameterValue=$private_network \\
                                              ParameterKey=PrivateNetwork1,ParameterValue=$private_network1 \\
+                                             ParameterKey=PrivateNetwork2,ParameterValue=$private_network2 \\
+                                             ParameterKey=PrivateNetwork3,ParameterValue=$private_network3 \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
