Development - Environment Variable Overrides, DNS, CloudWatch Logs, Bootstrap Logic
* improve how some parameters set by env var but not overridable are handled
* add DNS to LinuxBastion; change naming conventions from application to utility
* added private DNS, finalized CloudWatch Logs
* added Bootstrap section, intended to bootstrap a new account

diff --git a/utility/bin/utility-update-linuxbastions-stack b/utility/bin/utility-update-linuxbastions-stack
--- a/utility/bin/utility-update-linuxbastions-stack
+++ b/utility/bin/utility-update-linuxbastions-stack
@@ -28,9 +28,13 @@ owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
-application=${APPLICATION_NAME:-LinuxBastions}
-key=${AWS_KEY_NAME:-demo}
-network=${ADMINISTRATOR_NETWORK:-0.0.0.0/0}
+utility=${UTILITY_NAME:-LinuxBastions}
+utility_domain=${UTILITY_DOMAIN:-lbastion}
+key=${AWS_KEY_NAME:-example}
+public_network=${PUBLIC_NETWORK:-0.0.0.0/0}
+public_network1=${PUBLIC_NETWORK1:-}
+private_network=${PRIVATE_NETWORK:-10.0.0.0/16}
+private_network1=${PRIVATE_NETWORK1:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -42,8 +46,9 @@ usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o]"
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment]"
-    echo "                  [-A application]"
-    echo "                  [-k key] [-n network ]"
+    echo "                  [-U utility] [-D domain]"
+    echo "                  [-k key]"
+    echo "                  [-p network] [-P network ]"
     echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
@@ -54,9 +59,11 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -A application  Application Name (default: $application)"
+    echo "  -U utility      Utility Name (default: $utility)"
+    echo "  -D domain       Utility Domain (default: $utility_domain)"
     echo "  -k key          Key (default: $key)"
-    echo "  -n network      Administrator Network (default: $network)"
+    echo "  -p network      Public Network (default: $public_network)"
+    echo "  -P network      Private Network (default: $private_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -142,7 +149,7 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvoO:C:S:E:A:k:n:r:a:u:? arg; do
+while getopts IsfvoO:C:S:E:U:D:k:p:P:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -153,9 +160,11 @@ while getopts IsfvoO:C:S:E:A:k:n:r:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    A)  application="$OPTARG";;
+    U)  utility="$OPTARG";;
+    D)  utility_domain="$OPTARG";;
     k)  key="$OPTARG";;
-    n)  network="$OPTARG";;
+    p)  public_network="$OPTARG";;
+    P)  private_network="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -193,18 +202,6 @@ if [ -z $environment ]; then
     exit 16
 else
     case $environment in
-      Core)
-        usemultizone=false
-        usestaticpublicaddress=true
-        usestaticprivateaddress=true
-        uselogmonitoring=false
-        uselocalusers=true;;
-      Build)
-        usemultizone=false
-        usestaticpublicaddress=true
-        usestaticprivateaddress=true
-        uselogmonitoring=false
-        uselocalusers=true;;
       Production)
         usemultizone=true
         usestaticpublicaddress=true
@@ -215,27 +212,51 @@ else
         usemultizone=false
         usestaticpublicaddress=true
         usestaticprivateaddress=true
-        uselogmonitoring=false
+        uselogmonitoring=true
         uselocalusers=true;;
       Testing)
         usemultizone=false
         usestaticpublicaddress=true
         usestaticprivateaddress=true
-        uselogmonitoring=false
-        uselocalusers=false;;
+        uselogmonitoring=true
+        uselocalusers=true;;
+      Development)
+        usemultizone=false
+        usestaticpublicaddress=true
+        usestaticprivateaddress=true
+        uselogmonitoring=true
+        uselocalusers=true;;
+      Core)
+        usemultizone=false
+        usestaticpublicaddress=true
+        usestaticprivateaddress=true
+        uselogmonitoring=true
+        uselocalusers=true;;
+      Build)
+        usemultizone=false
+        usestaticpublicaddress=true
+        usestaticprivateaddress=true
+        uselogmonitoring=true
+        uselocalusers=true;;
       *)
         usemultizone=false
-        usestaticpublicaddress=false
-        usestaticprivateaddress=false
-        uselogmonitoring=false
-        uselocalusers=false;;
+        usestaticpublicaddress=true
+        usestaticprivateaddress=true
+        uselogmonitoring=true
+        uselocalusers=true;;
     esac
 fi
 
-if [ -z $application ]; then
-    echo "-A application missing!"
-    echo "Could not automatically determine application, and it was not specified as a parameter"
+if [ -z $utility ]; then
+    echo "-U utility missing!"
+    echo "Could not automatically determine utility, and it was not specified as a parameter"
     exit 20
+fi
+
+if [ -z $utility_domain ]; then
+    echo "-D domain missing!"
+    echo "Could not automatically determine domain, and it was not specified as a parameter"
+    exit 22
 fi
 
 if [ -z $key ]; then
@@ -244,10 +265,16 @@ if [ -z $key ]; then
     exit 30
 fi
 
-if [ -z $network ]; then
-    echo "-N network missing!"
-    echo "Could not automatically determine network, and it was not specified as a parameter"
-    exit 32
+if [ -z $public_network ]; then
+    echo "-p network missing!"
+    echo "Could not automatically determine public network, and it was not specified as a parameter"
+    exit 34
+fi
+
+if [ -z $private_network ]; then
+    echo "-P network missing!"
+    echo "Could not automatically determine private network, and it was not specified as a parameter"
+    exit 36
 fi
 
 if [ -z $region ]; then
@@ -293,9 +320,9 @@ if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region
     unset templatesbucket
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
+if ! aws cloudformation describe-stacks --stack-name $environment-$utility \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - $environment-$application Stack does not exist!"
+    echo "Unable to update - $environment-$utility Stack does not exist!"
     exit 70
 fi
 
@@ -388,24 +415,28 @@ if [ $override = 1 ]; then
     stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
 fi
 read -r -d '' statement << EOS
-aws cloudformation update-stack --stack-name $environment-$application \\
+aws cloudformation update-stack --stack-name $environment-$utility \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
                                 --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
+                                             ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
-                                             ParameterKey=ApplicationName,ParameterValue=$application \\
+                                             ParameterKey=UtilityName,ParameterValue=$utility \\
+                                             ParameterKey=UtilityDomain,ParameterValue=$utility_domain \\
                                              ParameterKey=UseMultiZone,ParameterValue=$usemultizone \\
                                              ParameterKey=UseStaticPublicAddress,ParameterValue=$usestaticpublicaddress \\
                                              ParameterKey=UseStaticPrivateAddress,ParameterValue=$usestaticprivateaddress \\
                                              ParameterKey=UseLogMonitoring,ParameterValue=$uselogmonitoring \\
                                              ParameterKey=UseLocalUsers,ParameterValue=$uselocalusers \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
-                                             ParameterKey=AdministratorNetwork,ParameterValue=$network \\
+                                             ParameterKey=PublicNetwork,ParameterValue=$public_network \\
+                                             ParameterKey=PrivateNetwork,ParameterValue=$private_network \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
                                        Key=Environment,Value=$environment \\
+                                       Key=Utility,Value=$utility \\
                                 --capabilities CAPABILITY_IAM \\
                                 --profile $profile --region $region --output table
 EOS
@@ -437,7 +468,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name $environment-$application \\
+aws cloudformation describe-stacks --stack-name $environment-$utility \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -445,7 +476,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name $environment-$application --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name $environment-$utility --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -466,7 +497,7 @@ echo "$statement"
 echo
 echo "$statement2"
 
-if [ "$(aws cloudformation describe-stacks --stack-name $environment-$application \
+if [ "$(aws cloudformation describe-stacks --stack-name $environment-$utility \
                                            --query 'Stacks[].StackStatus' \
                                            --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
     echo
@@ -491,7 +522,7 @@ else
             echo "$run_statement2"
             eval "$eval_statement2"
 
-            status=$(aws cloudformation describe-stacks --stack-name $environment-$application \
+            status=$(aws cloudformation describe-stacks --stack-name $environment-$utility \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
             if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
@@ -544,7 +575,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stack-resources --stack-name $environment-$application \\
+aws cloudformation describe-stack-resources --stack-name $environment-$utility \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
                                             --profile $profile --region $region --output table
 EOS
