initial version of WebServers, without logging

diff --git a/example/bin/example-update-webservers-stack b/example/bin/example-update-webservers-stack
--- a/example/bin/example-update-webservers-stack
+++ b/example/bin/example-update-webservers-stack
@@ -12,32 +12,40 @@ bindir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 templatesdir=${bindir%/*}/templates
 tmpdir=/var/tmp
 
-if [ -z "$IROPS_HOME" ]; then
-    echo "IROPS_HOME not set, please source the appropriate irops-define-<environment> script."
-    exit 1
-fi
-
 step=0
 speed_max=400
 run_default=10
 pause_default=2
 next_default=5
 update_default=15
-update_attempts=20
+update_attempts=40
 
 interactive=1
 speed=100
 verbose=0
 override=0
+dummy=0
+owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+environment_size=${ENVIRONMENT_SIZE:-micro}
 application=${APPLICATION_NAME:-WebServers}
+application_domain=${APPLICATION_DOMAIN:-mws}
 application_version=${APPLICATION_VERSION:-1.0.0}
-application_domain=${APPLICATION_DOMAIN:-demo.iropshub.com}
-key=${AWS_KEY_NAME:-demo}
+key=${AWS_KEY_NAME:-example}
 network=${ADMINISTRATOR_NETWORK:-0.0.0.0/0}
+network1=${ADMINISTRATOR_NETWORK1:-}
+network2=${ADMINISTRATOR_NETWORK2:-}
+network3=${ADMINISTRATOR_NETWORK3:-}
+public_network=${PUBLIC_NETWORK:-0.0.0.0/0}
+public_network1=${PUBLIC_NETWORK1:-}
+public_network2=${PUBLIC_NETWORK2:-}
+public_network3=${PUBLIC_NETWORK3:-}
+private_network=${PRIVATE_NETWORK:-10.0.0.0/16}
+private_network1=${PRIVATE_NETWORK1:-}
+private_network2=${PRIVATE_NETWORK2:-}
+private_network3=${PRIVATE_NETWORK3:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -46,26 +54,31 @@ user=${AWS_USER_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o]"
-    echo "                  [-C company ] [-S system] [-E environment] [-O owner]"
-    echo "                  [-A application ] [-V version] [-D domain]"
-    echo "                  [-K key] [-N network ]"
+    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o] [-d]"
+    echo "                  [-O owner] [-C company ] [-S system]"
+    echo "                  [-E environment] [-Z size]"
+    echo "                  [-A application ] [-D domain] [-V version]"
+    echo "                  [-k key] [-n network ]"
+    echo "                  [-p network] [-P network ]"
     echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
     echo "  -o              override StackPolicy"
+    echo "  -d              use dummy application"
+    echo "  -O owner        Owner Email (default: $owner)"
     echo "  -C company      Company Name (default: $company)"
-    echo "  -L location     Location Name (default: $location)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -O owner        Owner Email (default: $owner)"
+    echo "  -Z size         Environment Size (default: $environment_size)"
     echo "  -A application  Application Name (default: $application)"
-    echo "  -V version      Application Version (default: $application_version)"
     echo "  -D domain       Application Domain (default: $application_domain)"
-    echo "  -K key          Key (default: $key)"
-    echo "  -N network      Administrator Network (default: $network)"
+    echo "  -V version      Application Version (default: $application_version)"
+    echo "  -k key          Key (default: $key)"
+    echo "  -n network      Administrator Network (default: $network)"
+    echo "  -p network      Public Network (default: $public_network)"
+    echo "  -P network      Private Network (default: $private_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -150,24 +163,37 @@ next() {
 
 
 #  3. Parse command line options
+#     - Note, using options 1-9 as hidden options to set additional network ranges
 
-while getopts IsfvoC:L:S:E:O:A:V:D:K:N:r:a:u:? arg; do
+while getopts IsfvodO:C:S:E:Z:A:D:V:k:n:1:2:3:p:4:5:6:P:7:8:9:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
     o)  override=1;;
+    d)  dummy=1;;
+    O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
-    L)  location="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    O)  owner="$OPTARG";;
+    Z)  environment_size="$OPTARG";;
     A)  application="$OPTARG";;
-    V)  application_version="$OPTARG";;
     D)  application_domain="$OPTARG";;
-    K)  key="$OPTARG";;
-    N)  network="$OPTARG";;
+    V)  application_version="$OPTARG";;
+    k)  key="$OPTARG";;
+    n)  network="$OPTARG";;
+    1)  network1="$OPTARG";;
+    2)  network2="$OPTARG";;
+    3)  network3="$OPTARG";;
+    p)  public_network="$OPTARG";;
+    4)  public_network1="$OPTARG";;
+    5)  public_network2="$OPTARG";;
+    6)  public_network3="$OPTARG";;
+    P)  private_network="$OPTARG";;
+    7)  private_network1="$OPTARG";;
+    8)  private_network2="$OPTARG";;
+    9)  private_network3="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -181,10 +207,82 @@ shift $(($OPTIND - 1))
 
 #  4. Validate environment
 
+if [ -z $owner ]; then
+    echo "-O owner missing!"
+    echo "Could not automatically determine owner, and it was not specified as a parameter"
+    exit 10
+fi
+
+if [ -z $company ]; then
+    echo "-C company missing!"
+    echo "Could not automatically determine company, and it was not specified as a parameter"
+    exit 12
+fi
+
+if [ -z $system ]; then
+    echo "-S system missing!"
+    echo "Could not automatically determine system, and it was not specified as a parameter"
+    exit 14
+fi
+
+if [ -z $environment ]; then
+    echo "-E environment missing!"
+    echo "Could not automatically determine environment, and it was not specified as a parameter"
+    exit 16
+fi
+
+if [ -z $environment_size ]; then
+    echo "-Z size missing!"
+    echo "Could not automatically determine size, and it was not specified as a parameter"
+    exit 18
+fi
+
+if [ -z $application ]; then
+    echo "-A application missing!"
+    echo "Could not automatically determine application, and it was not specified as a parameter"
+    exit 20
+fi
+
+if [ -z $application_domain ]; then
+    echo "-D domain missing!"
+    echo "Could not automatically determine domain, and it was not specified as a parameter"
+    exit 22
+fi
+
+if [ -z $application_version ]; then
+    echo "-V version missing!"
+    echo "Could not automatically determine version, and it was not specified as a parameter"
+    exit 24
+fi
+
+if [ -z $key ]; then
+    echo "-k key missing!"
+    echo "Could not automatically determine key, and it was not specified as a parameter"
+    exit 30
+fi
+
+if [ -z $network ]; then
+    echo "-n network missing!"
+    echo "Could not automatically determine network, and it was not specified as a parameter"
+    exit 32
+fi
+
+if [ -z $public_network ]; then
+    echo "-p network missing!"
+    echo "Could not automatically determine public network, and it was not specified as a parameter"
+    exit 34
+fi
+
+if [ -z $private_network ]; then
+    echo "-P network missing!"
+    echo "Could not automatically determine private network, and it was not specified as a parameter"
+    exit 36
+fi
+
 if [ -z $region ]; then
     echo "-r region missing!"
     echo "Could not automatically determine region, and it was not specified as a parameter"
-    exit 20
+    exit 50
 else
     case $region in
       us-east-1)
@@ -193,20 +291,20 @@ else
         s3_domain=s3-$region.amazonaws.com;;
     *)
         echo "-r $region invalid: Please specify a valid region"
-        exit 21;;
+        exit 51;;
     esac
 fi
 
 if [ -z $account ]; then
     echo "-a account missing!"
     echo "Could not automatically determine account, and it was not specified as a parameter"
-    exit 22
+    exit 52
 fi
 
 if [ -z $user ]; then
     echo "-u user missing!"
     echo "Could not automatically determine user, and it was not specified as a parameter"
-    exit 24
+    exit 54
 fi
 
 profile=$account-$user
@@ -214,7 +312,7 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 53
+    exit 60
 fi
 
 templatesbucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
@@ -224,16 +322,18 @@ if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region
     unset templatesbucket
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - $environment-VPC Stack does not exist!"
-    exit 2
+examplesbucket=${AWS_EXAMPLES_BUCKET:-examples-$region-$account}
+examplespath=/$application
+
+if ! aws s3api head-bucket --bucket $examplesbucket --profile $profile --region $region 2> /dev/null; then
+    echo "$examplesbucket S3 bucket does not exist!"
+    exit 68
 fi
 
 if ! aws cloudformation describe-stacks --stack-name $environment-$application \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo "Unable to update - $environment-$application Stack does not exist!"
-    exit 3
+    exit 70
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -253,7 +353,7 @@ aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'} 2> /dev/null"
+eval_statement="${statement//\\$'\n'}"
 
 if [ $verbose = 1 ]; then
     clear
@@ -288,7 +388,7 @@ aws s3 sync $templatesdir \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'} 2> /dev/null"
+eval_statement="${statement//\\$'\n'}"
 
 if [ ! -z $templatesbucket ]; then
     clear
@@ -314,12 +414,17 @@ fi
 
 
 ((++step))
+if [ $dummy = 1 ]; then
+    # unset download location, which triggers creation of dummy application page within the template
+    unset examplesbucket
+fi
+
 if [ ! -z $templatesbucket ]; then
     template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Example-WebServers.json"
     stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Example-WebServers-StackPolicy.json"
 else
-    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Example-WebServers.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Example-WebServers-StackPolicy.json"
+    template_parameter="--template-body file://$templatesdir/Example-WebServers.json"
+    stack_policy_parameter="--stack-policy-body file://$templatesdir/Example-WebServers-StackPolicy.json"
 fi
 if [ $override = 1 ]; then
     stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
@@ -328,19 +433,32 @@ read -r -d '' statement << EOS
 aws cloudformation update-stack --stack-name $environment-$application \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=EnvironmentVPCStackName,ParameterValue=$environment-VPC \\
+                                --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
+                                             ParameterKey=KeyName,ParameterValue=$key \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
-                                             ParameterKey=EnvironmentName,ParameterValue=$environment \\
+                                             ParameterKey=EnvironmentSize,ParameterValue=$environment_size \\
+                                             ParameterKey=ApplicationsBucket,ParameterValue=$examplesbucket \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
-                                             ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
                                              ParameterKey=ApplicationDomain,ParameterValue=$application_domain \\
-                                             ParameterKey=KeyName,ParameterValue=$key \\
+                                             ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
                                              ParameterKey=AdministratorNetwork,ParameterValue=$network \\
-                                --tags Key=Company,Value=$company \\
+                                             ParameterKey=AdministratorNetwork1,ParameterValue=$network1 \\
+                                             ParameterKey=AdministratorNetwork2,ParameterValue=$network2 \\
+                                             ParameterKey=AdministratorNetwork3,ParameterValue=$network3 \\
+                                             ParameterKey=PublicNetwork,ParameterValue=$public_network \\
+                                             ParameterKey=PublicNetwork1,ParameterValue=$public_network1 \\
+                                             ParameterKey=PublicNetwork2,ParameterValue=$public_network2 \\
+                                             ParameterKey=PublicNetwork3,ParameterValue=$public_network3 \\
+                                             ParameterKey=PrivateNetwork,ParameterValue=$private_network \\
+                                             ParameterKey=PrivateNetwork1,ParameterValue=$private_network1 \\
+                                             ParameterKey=PrivateNetwork2,ParameterValue=$private_network2 \\
+                                             ParameterKey=PrivateNetwork3,ParameterValue=$private_network3 \\
+                                --tags Key=Owner,Value=$owner \\
+                                       Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
                                        Key=Environment,Value=$environment \\
-                                       Key=Owner,Value=$owner \\
+                                       Key=Application,Value=$application \\
                                 --capabilities CAPABILITY_IAM \\
                                 --profile $profile --region $region --output table
 EOS
@@ -481,7 +599,7 @@ fi
 read -r -d '' statement << EOS
 aws cloudformation describe-stack-resources --stack-name $environment-$application \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
-                                            --profile $profile --region $region --output table 2> /dev/null
+                                            --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
