renamed nestedwebserver to nestedlinuxwebserver; switched to new network address env vars

diff --git a/example/bin/example-update-nestedlinuxwebserver-stack b/example/bin/example-update-nestedlinuxwebserver-stack
--- a/example/bin/example-update-nestedlinuxwebserver-stack
+++ b/example/bin/example-update-nestedlinuxwebserver-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script updates the Example NestedWebServer Stack in an Environment Account.
+# This script updates the Example NestedLinuxWebServer Stack in an Environment Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -30,22 +30,22 @@ company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
 environment_size=${ENVIRONMENT_SIZE:-micro}
-application=${APPLICATION_NAME:-NestedWebServer}
-application_domain=${APPLICATION_DOMAIN:-nws}
+application=${APPLICATION_NAME:-NestedLinuxWebServer}
+application_domain=${APPLICATION_DOMAIN:-lws}
 application_version=${APPLICATION_VERSION:-2.0.0}
 key=${AWS_KEY_NAME:-example}
-network=${ADMINISTRATOR_NETWORK:-0.0.0.0/0}
-network1=${ADMINISTRATOR_NETWORK1:-}
-network2=${ADMINISTRATOR_NETWORK2:-}
-network3=${ADMINISTRATOR_NETWORK3:-}
-public_network=${PUBLIC_NETWORK:-0.0.0.0/0}
-public_network1=${PUBLIC_NETWORK1:-}
-public_network2=${PUBLIC_NETWORK2:-}
-public_network3=${PUBLIC_NETWORK3:-}
-private_network=${PRIVATE_NETWORK:-10.0.0.0/16}
-private_network1=${PRIVATE_NETWORK1:-}
-private_network2=${PRIVATE_NETWORK2:-}
-private_network3=${PRIVATE_NETWORK3:-}
+private_user_network=${PRIVATE_USER_NETWORK:-10.0.0.0/16}
+private_user_network1=${PRIVATE_USER_NETWORK1:-}
+private_user_network2=${PRIVATE_USER_NETWORK2:-}
+private_administrator_network=${PRIVATE_ADMINISTRATOR_NETWORK:-10.0.0.0/16}
+private_administrator_network1=${PRIVATE_ADMINISTRATOR_NETWORK1:-}
+private_administrator_network2=${PRIVATE_ADMINISTRATOR_NETWORK2:-}
+public_user_network=${PUBLIC_USER_NETWORK:-0.0.0.0/0}
+public_user_network1=${PUBLIC_USER_NETWORK1:-}
+public_user_network2=${PUBLIC_USER_NETWORK2:-}
+public_administrator_network=${PUBLIC_ADMINISTRATOR_NETWORK:-0.0.0.0/0}
+public_administrator_network1=${PUBLIC_ADMINISTRATOR_NETWORK1:-}
+public_administrator_network2=${PUBLIC_ADMINISTRATOR_NETWORK2:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -58,8 +58,9 @@ usage () {
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment] [-Z size]"
     echo "                  [-A application ] [-D domain] [-V version]"
-    echo "                  [-k key] [-n network ]"
+    echo "                  [-k key]"
     echo "                  [-p network] [-P network ]"
+    echo "                  [-n network] [-N network ]"
     echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
@@ -76,9 +77,10 @@ usage () {
     echo "  -D domain       Application Domain (default: $application_domain)"
     echo "  -V version      Application Version (default: $application_version)"
     echo "  -k key          Key (default: $key)"
-    echo "  -n network      Administrator Network (default: $network)"
-    echo "  -p network      Public Network (default: $public_network)"
-    echo "  -P network      Private Network (default: $private_network)"
+    echo "  -p network      Public User Network (default: $public_user_network)"
+    echo "  -P network      Public Administrator Network (default: $public_administrator_network)"
+    echo "  -n network      Private User Network (default: $private_user_network)"
+    echo "  -N network      Private Administrator Network (default: $private_administrator_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -163,9 +165,9 @@ next() {
 
 
 #  3. Parse command line options
-#     - Note, using options 1-9 as hidden options to set additional network ranges
+#     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvodO:C:S:E:Z:A:D:V:k:n:1:2:3:p:4:5:6:P:7:8:9:r:a:u:? arg; do
+while getopts IsfvodO:C:S:E:Z:A:D:V:k:p:1:2:P:3:4:n:5:6:N:7:8:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -182,18 +184,18 @@ while getopts IsfvodO:C:S:E:Z:A:D:V:k:n:1:2:3:p:4:5:6:P:7:8:9:r:a:u:? arg; do
     D)  application_domain="$OPTARG";;
     V)  application_version="$OPTARG";;
     k)  key="$OPTARG";;
-    n)  network="$OPTARG";;
-    1)  network1="$OPTARG";;
-    2)  network2="$OPTARG";;
-    3)  network3="$OPTARG";;
-    p)  public_network="$OPTARG";;
-    4)  public_network1="$OPTARG";;
-    5)  public_network2="$OPTARG";;
-    6)  public_network3="$OPTARG";;
-    P)  private_network="$OPTARG";;
-    7)  private_network1="$OPTARG";;
-    8)  private_network2="$OPTARG";;
-    9)  private_network3="$OPTARG";;
+    p)  public_user_network="$OPTARG";;
+    1)  public_user_network1="$OPTARG";;
+    2)  public_user_network2="$OPTARG";;
+    P)  public_administrator_network="$OPTARG";;
+    3)  public_administrator_network1="$OPTARG";;
+    4)  public_administrator_network2="$OPTARG";;
+    n)  private_user_network="$OPTARG";;
+    5)  private_user_network1="$OPTARG";;
+    6)  private_user_network2="$OPTARG";;
+    N)  private_administrator_network="$OPTARG";;
+    7)  private_administrator_network1="$OPTARG";;
+    8)  private_administrator_network2="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -229,6 +231,30 @@ if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
     exit 16
+else
+    case $environment in
+      Production)
+        instance_os=RHEL
+        use_log_monitoring=true;;
+      Staging)
+        instance_os=AMZN
+        use_log_monitoring=true;;
+      Testing)
+        instance_os=AMZN
+        use_log_monitoring=false;;
+      Development)
+        instance_os=AMZN
+        use_log_monitoring=false;;
+      Core)
+        instance_os=AMZN
+        use_log_monitoring=true;;
+      Build)
+        instance_os=AMZN
+        use_log_monitoring=false;;
+      *)
+        instance_os=AMZN
+        use_log_monitoring=false;;
+    esac
 fi
 
 if [ -z $environment_size ]; then
@@ -261,22 +287,28 @@ if [ -z $key ]; then
     exit 30
 fi
 
-if [ -z $network ]; then
-    echo "-n network missing!"
-    echo "Could not automatically determine network, and it was not specified as a parameter"
-    exit 32
-fi
-
-if [ -z $public_network ]; then
+if [ -z $public_user_network ]; then
     echo "-p network missing!"
-    echo "Could not automatically determine public network, and it was not specified as a parameter"
-    exit 34
+    echo "Could not automatically determine public user network, and it was not specified as a parameter"
+    exit 40
 fi
 
-if [ -z $private_network ]; then
+if [ -z $public_administrator_network ]; then
     echo "-P network missing!"
-    echo "Could not automatically determine private network, and it was not specified as a parameter"
-    exit 36
+    echo "Could not automatically determine public administrator network, and it was not specified as a parameter"
+    exit 42
+fi
+
+if [ -z $private_user_network ]; then
+    echo "-n network missing!"
+    echo "Could not automatically determine private user network, and it was not specified as a parameter"
+    exit 44
+fi
+
+if [ -z $private_administrator_network ]; then
+    echo "-N network missing!"
+    echo "Could not automatically determine private administrator network, and it was not specified as a parameter"
+    exit 46
 fi
 
 if [ -z $region ]; then
@@ -287,7 +319,7 @@ else
     case $region in
       us-east-1)
         s3_domain=s3.amazonaws.com;;
-      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+      us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
         s3_domain=s3-$region.amazonaws.com;;
     *)
         echo "-r $region invalid: Please specify a valid region"
@@ -316,7 +348,7 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
 fi
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-templates_folder=example
+template_folder=example
 
 if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
     echo "$templates_bucket S3 bucket does not exist!"
@@ -324,7 +356,8 @@ if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --regio
 fi
 
 examples_bucket=${AWS_EXAMPLES_BUCKET:-examples-$region-$account}
-examples_folder=$application
+example_folder=LinuxWebServer
+example_object=LinuxWebServer-$application_version.tgz
 
 if ! aws s3api head-bucket --bucket $examples_bucket --profile $profile --region $region 2> /dev/null; then
     echo "$examples_bucket S3 bucket does not exist!"
@@ -384,12 +417,13 @@ fi
 ((++step))
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
-            s3://$templates_bucket/$templates_folder \\
-            --exclude '*' --include 'Example-NestedWebServer.json' --include 'Example-NestedWebServer-StackPolicy.json' \\
-            --include 'Example-NestedWebServer-Role.json' \\
-            --include 'Example-NestedWebServer-SecurityGroup.json' \\
-            --include 'Example-NestedWebServer-Instance.json' \\
-            --include 'Example-NestedWebServer-DomainName.json' \\
+            s3://$templates_bucket/$template_folder \\
+            --exclude '*' --include 'Example-NestedLinuxWebServer.json' --include 'Example-NestedLinuxWebServer-StackPolicy.json' \\
+            --include 'Example-NestedLinuxWebServer-Role.json' \\
+            --include 'Example-NestedLinuxWebServer-Logs.json' \\
+            --include 'Example-NestedLinuxWebServer-SecurityGroup.json' \\
+            --include 'Example-NestedLinuxWebServer-Instance.json' \\
+            --include 'Example-NestedLinuxWebServer-DomainNames.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -422,8 +456,8 @@ if [ $dummy = 1 ]; then
     unset examples_bucket
 fi
 
-template_parameter="--template-url https://$s3_domain/$templates_bucket/$templates_folder/Example-NestedWebServer.json"
-stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$templates_folder/Example-NestedWebServer-StackPolicy.json"
+template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Example-NestedLinuxWebServer.json"
+stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Example-NestedLinuxWebServer-StackPolicy.json"
 if [ $override = 1 ]; then
     stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
 fi
@@ -432,28 +466,35 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
                                 --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
+                                             ParameterKey=CustomIdentifierFunctionsStackName,ParameterValue=CustomIdentifierFunctions \\
+                                             ParameterKey=StandardAMIFunctionsStackName,ParameterValue=StandardAMIFunctions \\
+                                             ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
                                              ParameterKey=TemplatesBucket,ParameterValue=$templates_bucket \\
-                                             ParameterKey=TemplatesFolder,ParameterValue=$templates_folder \\
+                                             ParameterKey=TemplateFolder,ParameterValue=$template_folder \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
                                              ParameterKey=EnvironmentSize,ParameterValue=$environment_size \\
+                                             ParameterKey=InstanceOS,ParameterValue=$instance_os \\
                                              ParameterKey=ApplicationsBucket,ParameterValue=$examples_bucket \\
+                                             ParameterKey=ApplicationFolder,ParameterValue=$example_folder \\
+                                             ParameterKey=ApplicationObject,ParameterValue=$example_object \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
                                              ParameterKey=ApplicationDomain,ParameterValue=$application_domain \\
                                              ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
-                                             ParameterKey=AdministratorNetwork,ParameterValue=$network \\
-                                             ParameterKey=AdministratorNetwork1,ParameterValue=$network1 \\
-                                             ParameterKey=AdministratorNetwork2,ParameterValue=$network2 \\
-                                             ParameterKey=AdministratorNetwork3,ParameterValue=$network3 \\
-                                             ParameterKey=PublicNetwork,ParameterValue=$public_network \\
-                                             ParameterKey=PublicNetwork1,ParameterValue=$public_network1 \\
-                                             ParameterKey=PublicNetwork2,ParameterValue=$public_network2 \\
-                                             ParameterKey=PublicNetwork3,ParameterValue=$public_network3 \\
-                                             ParameterKey=PrivateNetwork,ParameterValue=$private_network \\
-                                             ParameterKey=PrivateNetwork1,ParameterValue=$private_network1 \\
-                                             ParameterKey=PrivateNetwork2,ParameterValue=$private_network2 \\
-                                             ParameterKey=PrivateNetwork3,ParameterValue=$private_network3 \\
+                                             ParameterKey=UseLogMonitoring,ParameterValue=$use_log_monitoring \\
+                                             ParameterKey=PublicUserNetwork,ParameterValue=$public_user_network \\
+                                             ParameterKey=PublicUserNetwork1,ParameterValue=$public_user_network1 \\
+                                             ParameterKey=PublicUserNetwork2,ParameterValue=$public_user_network2 \\
+                                             ParameterKey=PublicAdministratorNetwork,ParameterValue=$public_administrator_network \\
+                                             ParameterKey=PublicAdministratorNetwork1,ParameterValue=$public_administrator_network1 \\
+                                             ParameterKey=PublicAdministratorNetwork2,ParameterValue=$public_administrator_network2 \\
+                                             ParameterKey=PrivateUserNetwork,ParameterValue=$private_user_network \\
+                                             ParameterKey=PrivateUserNetwork1,ParameterValue=$private_user_network1 \\
+                                             ParameterKey=PrivateUserNetwork2,ParameterValue=$private_user_network2 \\
+                                             ParameterKey=PrivateAdministratorNetwork,ParameterValue=$private_administrator_network \\
+                                             ParameterKey=PrivateAdministratorNetwork1,ParameterValue=$private_administrator_network1 \\
+                                             ParameterKey=PrivateAdministratorNetwork2,ParameterValue=$private_administrator_network2 \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
