Improvements and standardization of parameters

diff --git a/example/bin/example-update-webserver-stack b/example/bin/example-update-webserver-stack
--- a/example/bin/example-update-webserver-stack
+++ b/example/bin/example-update-webserver-stack
@@ -18,7 +18,7 @@ run_default=10
 pause_default=2
 next_default=5
 update_default=15
-update_attempts=20
+update_attempts=40
 
 interactive=1
 speed=100
@@ -29,16 +29,23 @@ owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
+environment_size=${ENVIRONMENT_SIZE:-micro}
 application=${APPLICATION_NAME:-WebServer}
 application_domain=${APPLICATION_DOMAIN:-ws}
 application_version=${APPLICATION_VERSION:-1.0.0}
 key=${AWS_KEY_NAME:-example}
 network=${ADMINISTRATOR_NETWORK:-0.0.0.0/0}
 network1=${ADMINISTRATOR_NETWORK1:-}
+network2=${ADMINISTRATOR_NETWORK2:-}
+network3=${ADMINISTRATOR_NETWORK3:-}
 public_network=${PUBLIC_NETWORK:-0.0.0.0/0}
 public_network1=${PUBLIC_NETWORK1:-}
+public_network2=${PUBLIC_NETWORK2:-}
+public_network3=${PUBLIC_NETWORK3:-}
 private_network=${PRIVATE_NETWORK:-10.0.0.0/16}
 private_network1=${PRIVATE_NETWORK1:-}
+private_network2=${PRIVATE_NETWORK2:-}
+private_network3=${PRIVATE_NETWORK3:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -49,7 +56,7 @@ user=${AWS_USER_NAME:-administrator}
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o] [-d]"
     echo "                  [-O owner] [-C company ] [-S system]"
-    echo "                  [-E environment]"
+    echo "                  [-E environment] [-Z size]"
     echo "                  [-A application ] [-D domain] [-V version]"
     echo "                  [-k key] [-n network ]"
     echo "                  [-p network] [-P network ]"
@@ -62,9 +69,9 @@ usage () {
     echo "  -d              use dummy application"
     echo "  -O owner        Owner Email (default: $owner)"
     echo "  -C company      Company Name (default: $company)"
-    echo "  -L location     Location Name (default: $location)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
+    echo "  -Z size         Environment Size (default: $environment_size)"
     echo "  -A application  Application Name (default: $application)"
     echo "  -D domain       Application Domain (default: $application_domain)"
     echo "  -V version      Application Version (default: $application_version)"
@@ -156,8 +163,9 @@ next() {
 
 
 #  3. Parse command line options
+#     - Note, using options 1-9 as hidden options to set additional network ranges
 
-while getopts IsfvodO:C:L:S:E:A:V:k:n:p:P:r:a:u:? arg; do
+while getopts IsfvodO:C:S:E:Z:A:D:V:k:n:1:2:3:p:4:5:6:P:7:8:9:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -167,16 +175,25 @@ while getopts IsfvodO:C:L:S:E:A:V:k:n:p:P:r:a:u:? arg; do
     d)  dummy=1;;
     O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
-    L)  location="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
+    Z)  environment_size="$OPTARG";;
     A)  application="$OPTARG";;
     D)  application_domain="$OPTARG";;
     V)  application_version="$OPTARG";;
     k)  key="$OPTARG";;
     n)  network="$OPTARG";;
+    1)  network1="$OPTARG";;
+    2)  network2="$OPTARG";;
+    3)  network3="$OPTARG";;
     p)  public_network="$OPTARG";;
+    4)  public_network1="$OPTARG";;
+    5)  public_network2="$OPTARG";;
+    6)  public_network3="$OPTARG";;
     P)  private_network="$OPTARG";;
+    7)  private_network1="$OPTARG";;
+    8)  private_network2="$OPTARG";;
+    9)  private_network3="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -212,23 +229,12 @@ if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
     exit 16
-else
-    case $environment in
-      Production)
-        environmentsize=medium;;
-      Staging)
-        environment_size=small;;
-      Testing)
-        environment_size=micro;;
-      Development)
-        environment_size=micro;;
-      Core)
-        environment_size=micro;;
-      Build)
-        environment_size=micro;;
-      *)
-        environment_size=micro;;
-    esac
+fi
+
+if [ -z $environment_size ]; then
+    echo "-Z size missing!"
+    echo "Could not automatically determine size, and it was not specified as a parameter"
+    exit 18
 fi
 
 if [ -z $application ]; then
@@ -429,15 +435,25 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                 $stack_policy_parameter \\
                                 --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
+                                             ParameterKey=CompanyName,ParameterValue=$company \\
+                                             ParameterKey=SystemName,ParameterValue=$system \\
                                              ParameterKey=EnvironmentSize,ParameterValue=$environment_size \\
                                              ParameterKey=ApplicationsBucket,ParameterValue=$examplesbucket \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
                                              ParameterKey=ApplicationDomain,ParameterValue=$application_domain \\
                                              ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
                                              ParameterKey=AdministratorNetwork,ParameterValue=$network \\
+                                             ParameterKey=AdministratorNetwork1,ParameterValue=$network1 \\
+                                             ParameterKey=AdministratorNetwork2,ParameterValue=$network2 \\
+                                             ParameterKey=AdministratorNetwork3,ParameterValue=$network3 \\
                                              ParameterKey=PublicNetwork,ParameterValue=$public_network \\
+                                             ParameterKey=PublicNetwork1,ParameterValue=$public_network1 \\
+                                             ParameterKey=PublicNetwork2,ParameterValue=$public_network2 \\
+                                             ParameterKey=PublicNetwork3,ParameterValue=$public_network3 \\
                                              ParameterKey=PrivateNetwork,ParameterValue=$private_network \\
                                              ParameterKey=PrivateNetwork1,ParameterValue=$private_network1 \\
+                                             ParameterKey=PrivateNetwork2,ParameterValue=$private_network2 \\
+                                             ParameterKey=PrivateNetwork3,ParameterValue=$private_network3 \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
