Update driver scripts with recent fixes for consistency

diff --git a/example/bin/example-update-linuxwebservers-stack b/example/bin/example-update-linuxwebservers-stack
--- a/example/bin/example-update-linuxwebservers-stack
+++ b/example/bin/example-update-linuxwebservers-stack
@@ -25,7 +25,7 @@ speed=100
 verbose=0
 override=0
 dummy=0
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
@@ -55,12 +55,12 @@ key=${AWS_KEY_NAME:-example}
 
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o] [-d]"
-    echo "                  [-O owner] [-C company ] [-S system]"
+    echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment] [-T type]"
-    echo "                  [-A application ] [-D domain] [-V version]"
-    echo "                  [-p network] [-P network ]"
-    echo "                  [-n network] [-N network ]"
-    echo "                  [-r region ] [-a account] [-u user] [-k key]"
+    echo "                  [-A application] [-D domain] [-V version]"
+    echo "                  [-p network] [-P network]"
+    echo "                  [-n network] [-N network]"
+    echo "                  [-r region] [-a account] [-u user] [-k key]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -279,10 +279,8 @@ else
         normal_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         reduced_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       *)
-        os_name="Amazon Linux"
-        log_retention=0
-        normal_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
-        reduced_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
+        echo "-E $environment invalid! Must be Production, Staging, Testing, Development, Core or Build"
+        exit 21;;
     esac
 fi
 
diff --git a/example/bin/example-update-nestedlinuxwebserver-stack b/example/bin/example-update-nestedlinuxwebserver-stack
--- a/example/bin/example-update-nestedlinuxwebserver-stack
+++ b/example/bin/example-update-nestedlinuxwebserver-stack
@@ -25,7 +25,7 @@ speed=100
 verbose=0
 override=0
 dummy=0
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
@@ -55,12 +55,12 @@ key=${AWS_KEY_NAME:-example}
 
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o] [-d]"
-    echo "                  [-O owner] [-C company ] [-S system]"
+    echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment] [-T type]"
-    echo "                  [-A application ] [-D domain] [-V version]"
-    echo "                  [-p network] [-P network ]"
-    echo "                  [-n network] [-N network ]"
-    echo "                  [-r region ] [-a account] [-u user] [-k key]"
+    echo "                  [-A application] [-D domain] [-V version]"
+    echo "                  [-p network] [-P network]"
+    echo "                  [-n network] [-N network]"
+    echo "                  [-r region] [-a account] [-u user] [-k key]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -166,7 +166,7 @@ next() {
 #  3. Parse command line options
 #     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvdO:C:S:E:T:A:D:V:p:1:2:P:3:4:n:5:6:N:7:8:r:a:u:k:? arg; do
+while getopts IsfvodO:C:S:E:T:A:D:V:p:1:2:P:3:4:n:5:6:N:7:8:r:a:u:k:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -267,8 +267,8 @@ else
         os_name="Amazon Linux"
         log_retention=0;;
       *)
-        os_name="Amazon Linux"
-        log_retention=0;;
+        echo "-E $environment invalid! Must be Production, Staging, Testing, Development, Core or Build"
+        exit 21;;
     esac
 fi
 
