improvements to Example-WebServer application

diff --git a/example/bin/example-update-webserver-stack b/example/bin/example-update-webserver-stack
--- a/example/bin/example-update-webserver-stack
+++ b/example/bin/example-update-webserver-stack
@@ -23,14 +23,27 @@ update_attempts=20
 interactive=1
 speed=100
 verbose=0
+dummy=0
 owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
 application=${APPLICATION_NAME:-WebServer}
+application_domain=${APPLICATION_DOMAIN:-ws}
 application_version=${APPLICATION_VERSION:-1.0.0}
-key=${AWS_KEY_NAME:-demo}
+key=${AWS_KEY_NAME:-example}
 network=${ADMINISTRATOR_NETWORK:-0.0.0.0/0}
+network1=${ADMINISTRATOR_NETWORK1:-}
+network2=${ADMINISTRATOR_NETWORK2:-}
+network3=${ADMINISTRATOR_NETWORK3:-}
+public_network=${PUBLIC_NETWORK:-0.0.0.0/0}
+public_network1=${PUBLIC_NETWORK1:-}
+public_network2=${PUBLIC_NETWORK2:-}
+public_network3=${PUBLIC_NETWORK3:-}
+private_network=${PRIVATE_NETWORK:-}
+private_network1=${PRIVATE_NETWORK1:-}
+private_network2=${PRIVATE_NETWORK2:-}
+private_network3=${PRIVATE_NETWORK3:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -39,11 +52,12 @@ user=${AWS_USER_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
+    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-d]"
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment]"
-    echo "                  [-A application ] [-V version]"
+    echo "                  [-A application ] [-D domain] [-V version]"
     echo "                  [-k key] [-n network ]"
+    echo "                  [-p network] [-P network ]"
     echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
@@ -55,9 +69,12 @@ usage () {
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
     echo "  -A application  Application Name (default: $application)"
+    echo "  -D domain       Application Domain (default: $application_domain)"
     echo "  -V version      Application Version (default: $application_version)"
     echo "  -k key          Key (default: $key)"
     echo "  -n network      Administrator Network (default: $network)"
+    echo "  -p network      Public Network (default: $public_network)"
+    echo "  -P network      Private Network (default: $private_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -143,21 +160,25 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvO:C:L:S:E:A:V:k:n:r:a:u:? arg; do
+while getopts IsfvdO:C:L:S:E:A:V:k:n:p:P:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
+    d)  dummy=1;;
     O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
     L)  location="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
     A)  application="$OPTARG";;
+    D)  application_domain="$OPTARG";;
     V)  application_version="$OPTARG";;
     k)  key="$OPTARG";;
     n)  network="$OPTARG";;
+    p)  public_network="$OPTARG";;
+    P)  private_network="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -201,22 +222,40 @@ if [ -z $application ]; then
     exit 20
 fi
 
-if [ -z $application_version ]; then
-    echo "-V version missing!"
-    echo "Could not automatically determine version, and it was not specified as a parameter"
+if [ -z $application_domain ]; then
+    echo "-D domain missing!"
+    echo "Could not automatically determine domain, and it was not specified as a parameter"
     exit 22
 fi
 
+if [ -z $application_version ]; then
+    echo "-V version missing!"
+    echo "Could not automatically determine version, and it was not specified as a parameter"
+    exit 24
+fi
+
 if [ -z $key ]; then
-    echo "-K key missing!"
+    echo "-k key missing!"
     echo "Could not automatically determine key, and it was not specified as a parameter"
     exit 30
 fi
 
 if [ -z $network ]; then
-    echo "-N network missing!"
+    echo "-n network missing!"
     echo "Could not automatically determine network, and it was not specified as a parameter"
     exit 32
+fi
+
+if [ -z $public_network ]; then
+    echo "-p network missing!"
+    echo "Could not automatically determine public network, and it was not specified as a parameter"
+    exit 34
+fi
+
+if [ -z $private_network ]; then
+    echo "-P network missing!"
+    echo "Could not automatically determine private network, and it was not specified as a parameter"
+    exit 36
 fi
 
 if [ -z $region ]; then
@@ -354,6 +393,11 @@ fi
 
 
 ((++step))
+if [ $dummy = 1 ]; then
+    # unset download location, which triggers creation of dummy application page within the template
+    unset examplesbucket
+fi
+
 if [ ! -z $templatesbucket ]; then
     template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Example-WebServer.json"
     stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Example-WebServer-StackPolicy.json"
@@ -369,14 +413,18 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
+                                             ParameterKey=ApplicationDomain,ParameterValue=$application_domain \\
                                              ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
                                              ParameterKey=ApplicationBucket,ParameterValue=$examplesbucket \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
                                              ParameterKey=AdministratorNetwork,ParameterValue=$network \\
+                                             ParameterKey=PublicNetwork,ParameterValue=$public_network \\
+                                             ParameterKey=PrivateNetwork,ParameterValue=$private_network \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
                                        Key=Environment,Value=$environment \\
+                                       Key=Application,Value=$application \\
                                 --capabilities CAPABILITY_IAM \\
                                 --profile $profile --region $region --output table
 EOS
