bringing WindowsWebServer up to date with recent changes

diff --git a/example/bin/example-update-windowswebserver-stack b/example/bin/example-update-windowswebserver-stack
--- a/example/bin/example-update-windowswebserver-stack
+++ b/example/bin/example-update-windowswebserver-stack
@@ -29,11 +29,10 @@ owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
-environment_size=${ENVIRONMENT_SIZE:-small}
+environment_type=${ENVIRONMENT_TYPE:-small}
 application=${APPLICATION_NAME:-WindowsWebServer}
 application_domain=${APPLICATION_DOMAIN:-wws}
 application_version=${APPLICATION_VERSION:-3.0.0}
-key=${AWS_KEY_NAME:-example}
 public_user_network=${PUBLIC_USER_NETWORK:-0.0.0.0/0}
 public_user_network1=${PUBLIC_USER_NETWORK1:-}
 public_user_network2=${PUBLIC_USER_NETWORK2:-}
@@ -49,6 +48,7 @@ private_administrator_network2=${PRIVATE_ADMINISTRATOR_NETWORK2:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
+key=${AWS_KEY_NAME:-example}
 
 
 #  2. Define functions
@@ -56,12 +56,11 @@ user=${AWS_USER_NAME:-administrator}
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o] [-d]"
     echo "                  [-O owner] [-C company ] [-S system]"
-    echo "                  [-E environment] [-Z size]"
+    echo "                  [-E environment] [-T type]"
     echo "                  [-A application ] [-D domain] [-V version]"
-    echo "                  [-k key]"
     echo "                  [-p network] [-P network ]"
     echo "                  [-n network] [-N network ]"
-    echo "                  [-r region ] [-a account] [-u user]"
+    echo "                  [-r region ] [-a account] [-u user] [-k key]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
@@ -72,11 +71,10 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -Z size         Environment Size (default: $environment_size)"
+    echo "  -T type         Environment Type (default: $environment_type)"
     echo "  -A application  Application Name (default: $application)"
     echo "  -D domain       Application Domain (default: $application_domain)"
     echo "  -V version      Application Version (default: $application_version)"
-    echo "  -k key          Key (default: $key)"
     echo "  -p network      Public User Network (default: $public_user_network)"
     echo "  -P network      Public Administrator Network (default: $public_administrator_network)"
     echo "  -n network      Private User Network (default: $private_user_network)"
@@ -84,6 +82,7 @@ usage () {
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
+    echo "  -k key          Key (default: $key)"
 }
 
 run() {
@@ -167,23 +166,21 @@ next() {
 #  3. Parse command line options
 #     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvodO:C:S:E:Z:A:D:V:k:p:1:2:P:3:4:n:5:6:N:7:8:r:a:u:? arg; do
+while getopts IsfvodO:C:S:E:T:A:D:V:p:1:2:P:3:4:n:5:6:N:7:8:r:a:u:k:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
-    o)  override=1;;
     d)  dummy=1;;
     O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    Z)  environment_size="$OPTARG";;
+    T)  environment_type="$OPTARG";;
     A)  application="$OPTARG";;
     D)  application_domain="$OPTARG";;
     V)  application_version="$OPTARG";;
-    k)  key="$OPTARG";;
     p)  public_user_network="$OPTARG";;
     1)  public_user_network1="$OPTARG";;
     2)  public_user_network2="$OPTARG";;
@@ -199,6 +196,7 @@ while getopts IsfvodO:C:S:E:Z:A:D:V:k:p:1:2:P:3:4:n:5:6:N:7:8:r:a:u:? arg; do
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
+    k)  key="$OPTARG";;
     ?)  usage
         exit 1;;
     esac
@@ -219,72 +217,98 @@ if [ -z $company ]; then
     echo "-C company missing!"
     echo "Could not automatically determine company, and it was not specified as a parameter"
     exit 12
+else
+    case $company in
+      Travel)
+        ;;
+      *)
+        echo "-C $company invalid! Must be Travel"
+        exit 13;;
+    esac
 fi
 
 if [ -z $system ]; then
     echo "-S system missing!"
     echo "Could not automatically determine system, and it was not specified as a parameter"
     exit 14
+else
+    case $system in
+      IROPS)
+        ;;
+      *)
+        echo "-S $system invalid! Must be IROPS"
+        exit 15;;
+    esac
 fi
 
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
-    exit 16
+    exit 20
 else
     case $environment in
       Production)
-        instance_os="Windows Server 2016"
+        os_name="Windows Server 2016"
         log_retention=30;;
       Staging)
-        instance_os="Windows Server 2012 R2"
+        os_name="Windows Server 2012 R2"
         log_retention=7;;
       Testing)
-        instance_os="Windows Server 2012 R2"
+        os_name="Windows Server 2012 R2"
         log_retention=0;;
       Development)
-        instance_os="Windows Server 2012 R2"
+        os_name="Windows Server 2012 R2"
         log_retention=0;;
       Core)
-        instance_os="Windows Server 2012 R2"
+        os_name="Windows Server 2012 R2"
         log_retention=14;;
       Build)
-        instance_os="Windows Server 2012 R2"
+        os_name="Windows Server 2012 R2"
         log_retention=0;;
       *)
-        instance_os="Windows Server 2012 R2"
+        os_name="Windows Server 2012 R2"
         log_retention=0;;
     esac
 fi
 
-if [ -z $environment_size ]; then
-    echo "-Z size missing!"
-    echo "Could not automatically determine size, and it was not specified as a parameter"
-    exit 18
+if [ -z $environment_type ]; then
+    echo "-T type missing!"
+    echo "Could not automatically determine environment type, and it was not specified as a parameter"
+    exit 22
+else
+    case $environment_type in
+      small|medium|large|xlarge)
+        ;;
+      *)
+        echo "-T $environment_type invalid! Must be small, medium, large or xlarge"
+        exit 23;;
+    esac
 fi
 
 if [ -z $application ]; then
     echo "-A application missing!"
     echo "Could not automatically determine application, and it was not specified as a parameter"
-    exit 20
+    exit 30
+else
+    case $application in
+      WindowsWebServer)
+        ;;
+      *)
+        echo "-A $application invalid! Must be LinuxWebServer"
+        exit 31;;
+    esac
 fi
 
 if [ -z $application_domain ]; then
     echo "-D domain missing!"
     echo "Could not automatically determine domain, and it was not specified as a parameter"
-    exit 22
+    exit 32
 fi
 
 if [ -z $application_version ]; then
     echo "-V version missing!"
     echo "Could not automatically determine version, and it was not specified as a parameter"
-    exit 24
-fi
-
-if [ -z $key ]; then
-    echo "-k key missing!"
-    echo "Could not automatically determine key, and it was not specified as a parameter"
-    exit 30
+    exit 34
 fi
 
 if [ -z $public_user_network ]; then
@@ -321,7 +345,7 @@ else
         s3_domain=s3.amazonaws.com;;
       us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
         s3_domain=s3-$region.amazonaws.com;;
-    *)
+      *)
         echo "-r $region invalid: Please specify a valid region"
         exit 51;;
     esac
@@ -339,35 +363,32 @@ if [ -z $user ]; then
     exit 54
 fi
 
+if [ -z $key ]; then
+    echo "-k key missing!"
+    echo "Could not automatically determine key, and it was not specified as a parameter"
+    exit 56
+fi
+
 profile=$account-$user
 
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 60
-fi
-
-templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-template_folder=example
-
-if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
-    unset templates_bucket
-fi
-
-examples_bucket=${AWS_EXAMPLES_BUCKET:-examples-$region-$account}
-example_folder=$application
-example_object=$application-$application_version.zip
-
-if ! aws s3api head-bucket --bucket $examples_bucket --profile $profile --region $region 2> /dev/null; then
-    echo "$examples_bucket S3 bucket does not exist!"
-    exit 68
+    exit 58
 fi
 
 if ! aws cloudformation describe-stacks --stack-name $environment-$application \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo "Unable to update - $environment-$application Stack does not exist!"
-    exit 70
+    exit 80
 fi
+
+templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
+template_folder=example
+
+examples_bucket=${AWS_EXAMPLES_BUCKET:-examples-$region-$account}
+example_folder=WindowsWebServer
+example_object=WindowsWebServer-$application_version.zip
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -423,42 +444,34 @@ EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'}"
 
-if [ ! -z $templates_bucket ]; then
-    clear
-    echo
-    echo "============================================================"
-    echo
-    echo "$(printf '%2d' $step). Sync Template and Policy to ($templates_bucket) Bucket"
-    echo
-    echo "============================================================"
-    echo
-    echo "Commands:"
-    echo
-    echo "$statement"
+clear
+echo
+echo "============================================================"
+echo
+echo "$(printf '%2d' $step). Sync Template and Policy to ($templates_bucket) Bucket"
+echo
+echo "============================================================"
+echo
+echo "Commands:"
+echo
+echo "$statement"
 
-    next 50
+next 50
 
-    echo
-    echo "$run_statement"
-    eval "$eval_statement"
+echo
+echo "$run_statement"
+eval "$eval_statement"
 
-    next 50
-fi
+next 50
 
 
 ((++step))
 if [ $dummy = 1 ]; then
-    # unset download location, which triggers creation of dummy application page within the template
-    unset examples_bucket
+    unset example_object
 fi
 
-if [ ! -z $templates_bucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Example-WindowsWebServer.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Example-WindowsWebServer-StackPolicy.json"
-else
-    template_parameter="--template-body file://$templatesdir/Example-WindowsWebServer.json"
-    stack_policy_parameter="--stack-policy-body file://$templatesdir/Example-WindowsWebServer-StackPolicy.json"
-fi
+template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Example-WindowsWebServer.json"
+stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Example-WindowsWebServer-StackPolicy.json"
 if [ $override = 1 ]; then
     stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
 fi
@@ -469,13 +482,13 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                 --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
                                              ParameterKey=CustomIdentifierFunctionsStackName,ParameterValue=CustomIdentifierFunctions \\
                                              ParameterKey=StandardAMIFunctionsStackName,ParameterValue=StandardAMIFunctions \\
+                                             ParameterKey=StandardBucketsStackName,ParameterValue=StandardBuckets \\
                                              ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
-                                             ParameterKey=EnvironmentSize,ParameterValue=$environment_size \\
-                                             ParameterKey=InstanceOS,ParameterValue="$instance_os" \\
-                                             ParameterKey=ApplicationsBucket,ParameterValue=$examples_bucket \\
+                                             ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
+                                             ParameterKey=OSName,ParameterValue="$os_name" \\
                                              ParameterKey=ApplicationFolder,ParameterValue=$example_folder \\
                                              ParameterKey=ApplicationObject,ParameterValue=$example_object \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
