improvements to WindowsWebServer, WebServer, WebServers for consistency, change from Demo to Travel

diff --git a/example/bin/example-update-windowswebserver-stack b/example/bin/example-update-windowswebserver-stack
--- a/example/bin/example-update-windowswebserver-stack
+++ b/example/bin/example-update-windowswebserver-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script creates the Example WindowsServer Stack in an Environment Account.
+# This script updates the Example WindowsWebServer Stack in an Environment Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -17,20 +17,21 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-create_default=15
-create_attempts=40
+update_default=15
+update_attempts=40
 
 interactive=1
 speed=100
 verbose=0
+override=0
 dummy=0
 owner=${OWNER_EMAIL:-$USER@hpe.com}
-company=${COMPANY_NAME:-Demo}
+company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
-environment_size=${ENVIRONMENT_SIZE:-micro}
-application=${APPLICATION_NAME:-WindowsServer}
-application_domain=${APPLICATION_DOMAIN:-windows}
+environment_size=${ENVIRONMENT_SIZE:-small}
+application=${APPLICATION_NAME:-WindowsWebServer}
+application_domain=${APPLICATION_DOMAIN:-wws}
 application_version=${APPLICATION_VERSION:-3.0.0}
 key=${AWS_KEY_NAME:-example}
 network=${ADMINISTRATOR_NETWORK:-0.0.0.0/0}
@@ -53,7 +54,7 @@ user=${AWS_USER_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-d]"
+    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-o] [-d]"
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment] [-Z size]"
     echo "                  [-A application ] [-D domain] [-V version]"
@@ -64,6 +65,7 @@ usage () {
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
+    echo "  -o              override StackPolicy"
     echo "  -d              use dummy application"
     echo "  -O owner        Owner Email (default: $owner)"
     echo "  -C company      Company Name (default: $company)"
@@ -163,12 +165,13 @@ next() {
 #  3. Parse command line options
 #     - Note, using options 1-9 as hidden options to set additional network ranges
 
-while getopts IsfvdO:C:S:E:Z:A:D:V:k:n:1:2:3:p:4:5:6:P:7:8:9:r:a:u:? arg; do
+while getopts IsfvodO:C:S:E:Z:A:D:V:k:n:1:2:3:p:4:5:6:P:7:8:9:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
+    o)  override=1;;
     d)  dummy=1;;
     O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
@@ -312,24 +315,24 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 60
 fi
 
-templatesbucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-templatespath=/example
+templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
+templates_path=/example
 
-if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region $region 2> /dev/null; then
-    unset templatesbucket
+if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
+    unset templates_bucket
 fi
 
-examplesbucket=${AWS_EXAMPLES_BUCKET:-examples-$region-$account}
-examplespath=/$application
+examples_bucket=${AWS_EXAMPLES_BUCKET:-examples-$region-$account}
+examples_path=/$application
 
-if ! aws s3api head-bucket --bucket $examplesbucket --profile $profile --region $region 2> /dev/null; then
-    echo "$examplesbucket S3 bucket does not exist!"
+if ! aws s3api head-bucket --bucket $examples_bucket --profile $profile --region $region 2> /dev/null; then
+    echo "$examples_bucket S3 bucket does not exist!"
     exit 68
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
+if ! aws cloudformation describe-stacks --stack-name $environment-$application \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "$environment-VPC Stack does not exist!"
+    echo "Unable to update - $environment-$application Stack does not exist!"
     exit 70
 fi
 
@@ -380,19 +383,19 @@ fi
 ((++step))
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
-            s3://$templatesbucket$templatespath \\
-            --exclude '*' --include 'Example-WindowsServer.json' --include 'Example-WindowsServer-StackPolicy.json' \\
+            s3://$templates_bucket$templates_path \\
+            --exclude '*' --include 'Example-WindowsWebServer.json' --include 'Example-WindowsWebServer-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'}"
 
-if [ ! -z $templatesbucket ]; then
+if [ ! -z $templates_bucket ]; then
     clear
     echo
     echo "============================================================"
     echo
-    echo "$(printf '%2d' $step). Sync Template and Policy to ($templatesbucket) Bucket"
+    echo "$(printf '%2d' $step). Sync Template and Policy to ($templates_bucket) Bucket"
     echo
     echo "============================================================"
     echo
@@ -413,18 +416,21 @@ fi
 ((++step))
 if [ $dummy = 1 ]; then
     # unset download location, which triggers creation of dummy application page within the template
-    unset examplesbucket
+    unset examples_bucket
 fi
 
-if [ ! -z $templatesbucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Example-WindowsServer.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Example-WindowsServer-StackPolicy.json"
+if [ ! -z $templates_bucket ]; then
+    template_parameter="--template-url https://$s3_domain/$templates_bucket$templates_path/Example-WindowsWebServer.json"
+    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket$templates_path/Example-WindowsWebServer-StackPolicy.json"
 else
-    template_parameter="--template-body file://$templatesdir/Example-WindowsServer.json"
-    stack_policy_parameter="--stack-policy-body file://$templatesdir/Example-WindowsServer-StackPolicy.json"
+    template_parameter="--template-body file://$templatesdir/Example-WindowsWebServer.json"
+    stack_policy_parameter="--stack-policy-body file://$templatesdir/Example-WindowsWebServer-StackPolicy.json"
+fi
+if [ $override = 1 ]; then
+    stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
 fi
 read -r -d '' statement << EOS
-aws cloudformation create-stack --stack-name $environment-$application \\
+aws cloudformation update-stack --stack-name $environment-$application \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
                                 --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
@@ -432,7 +438,7 @@ aws cloudformation create-stack --stack-name $environment-$application \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
                                              ParameterKey=EnvironmentSize,ParameterValue=$environment_size \\
-                                             ParameterKey=ApplicationsBucket,ParameterValue=$examplesbucket \\
+                                             ParameterKey=ApplicationsBucket,ParameterValue=$examples_bucket \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
                                              ParameterKey=ApplicationDomain,ParameterValue=$application_domain \\
                                              ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
@@ -463,7 +469,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Create the Stack"
+echo "$(printf '%2d' $step). Update the Stack"
 echo
 echo "============================================================"
 echo
@@ -471,25 +477,14 @@ echo "Commands:"
 echo
 echo "$statement"
 
-if aws cloudformation describe-stacks --stack-name $environment-$application \
-                                      --profile $profile --region $region --output text &> /dev/null; then
+run
+
+if [ $choice = y ]; then
     echo
-    tput rev
-    echo "Already Created!"
-    tput sgr0
+    echo "$run_statement"
+    eval "$eval_statement"
 
-    next 50
-
-else
-    run
-
-    if [ $choice = y ]; then
-        echo
-        echo "$run_statement"
-        eval "$eval_statement"
-
-        next
-    fi
+    next
 fi
 
 
@@ -514,7 +509,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Monitor Stack creation"
+echo "$(printf '%2d' $step). Monitor Stack update"
 echo
 echo "============================================================"
 echo
@@ -526,7 +521,7 @@ echo "$statement2"
 
 if [ "$(aws cloudformation describe-stacks --stack-name $environment-$application \
                                            --query 'Stacks[].StackStatus' \
-                                           --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
+                                           --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
     echo
     tput rev
     echo "Already Complete!"
@@ -543,8 +538,8 @@ else
         eval "$eval_statement"
 
         attempt=0
-        seconds=$create_default
-        while ((attempt++ <= create_attempts)); do
+        seconds=$update_default
+        while ((attempt++ <= update_attempts)); do
             echo
             echo "$run_statement2"
             eval "$eval_statement2"
@@ -552,7 +547,7 @@ else
             status=$(aws cloudformation describe-stacks --stack-name $environment-$application \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
-            if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
+            if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
                 break
             else
                 echo
@@ -573,7 +568,7 @@ aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'}"
+eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 if [ $verbose = 1 ]; then
     clear
