First Nested Application Stack example

diff --git a/example/bin/example-create-nestedwebserver-stack b/example/bin/example-create-nestedwebserver-stack
--- a/example/bin/example-create-nestedwebserver-stack
+++ b/example/bin/example-create-nestedwebserver-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script deletes the Example WebServer Stack in an Environment Account.
+# This script creates the Example NestedWebServer Stack in an Environment Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -17,14 +17,27 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-delete_default=15
-delete_attempts=20
+create_default=15
+create_attempts=20
 
 interactive=1
 speed=100
 verbose=0
+dummy=0
+owner=${OWNER_EMAIL:-$USER@hpe.com}
+company=${COMPANY_NAME:-Demo}
+system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
-application=${APPLICATION_NAME:-WebServer}
+application=${APPLICATION_NAME:-NestedWebServer}
+application_domain=${APPLICATION_DOMAIN:-nws}
+application_version=${APPLICATION_VERSION:-1.0.0}
+key=${AWS_KEY_NAME:-example}
+network=${ADMINISTRATOR_NETWORK:-0.0.0.0/0}
+network1=${ADMINISTRATOR_NETWORK1:-}
+public_network=${PUBLIC_NETWORK:-0.0.0.0/0}
+public_network1=${PUBLIC_NETWORK1:-}
+private_network=${PRIVATE_NETWORK:-}
+private_network1=${PRIVATE_NETWORK1:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -33,15 +46,29 @@ user=${AWS_USER_NAME:-administrator}
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
-    echo "                  [-E environment] [-A application ]"
+    echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v] [-d]"
+    echo "                  [-O owner] [-C company ] [-S system]"
+    echo "                  [-E environment]"
+    echo "                  [-A application ] [-D domain] [-V version]"
+    echo "                  [-k key] [-n network ]"
+    echo "                  [-p network] [-P network ]"
     echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
+    echo "  -d              use dummy application"
+    echo "  -O owner        Owner Email (default: $owner)"
+    echo "  -C company      Company Name (default: $company)"
+    echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
     echo "  -A application  Application Name (default: $application)"
+    echo "  -D domain       Application Domain (default: $application_domain)"
+    echo "  -V version      Application Version (default: $application_version)"
+    echo "  -k key          Key (default: $key)"
+    echo "  -n network      Administrator Network (default: $network)"
+    echo "  -p network      Public Network (default: $public_network)"
+    echo "  -P network      Private Network (default: $private_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -127,14 +154,24 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvE:A:r:a:u:? arg; do
+while getopts IsfvdO:C:S:E:A:D:V:k:n:p:P:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
+    d)  dummy=1;;
+    O)  owner="$OPTARG";;
+    C)  company="$OPTARG";;
+    S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
     A)  application="$OPTARG";;
+    D)  application_domain="$OPTARG";;
+    V)  application_version="$OPTARG";;
+    k)  key="$OPTARG";;
+    n)  network="$OPTARG";;
+    p)  public_network="$OPTARG";;
+    P)  private_network="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -148,6 +185,24 @@ shift $(($OPTIND - 1))
 
 #  4. Validate environment
 
+if [ -z $owner ]; then
+    echo "-O owner missing!"
+    echo "Could not automatically determine owner, and it was not specified as a parameter"
+    exit 10
+fi
+
+if [ -z $company ]; then
+    echo "-C company missing!"
+    echo "Could not automatically determine company, and it was not specified as a parameter"
+    exit 12
+fi
+
+if [ -z $system ]; then
+    echo "-S system missing!"
+    echo "Could not automatically determine system, and it was not specified as a parameter"
+    exit 14
+fi
+
 if [ -z $environment ]; then
     echo "-E environment missing!"
     echo "Could not automatically determine environment, and it was not specified as a parameter"
@@ -158,6 +213,42 @@ if [ -z $application ]; then
     echo "-A application missing!"
     echo "Could not automatically determine application, and it was not specified as a parameter"
     exit 20
+fi
+
+if [ -z $application_domain ]; then
+    echo "-D domain missing!"
+    echo "Could not automatically determine domain, and it was not specified as a parameter"
+    exit 22
+fi
+
+if [ -z $application_version ]; then
+    echo "-V version missing!"
+    echo "Could not automatically determine version, and it was not specified as a parameter"
+    exit 24
+fi
+
+if [ -z $key ]; then
+    echo "-k key missing!"
+    echo "Could not automatically determine key, and it was not specified as a parameter"
+    exit 30
+fi
+
+if [ -z $network ]; then
+    echo "-n network missing!"
+    echo "Could not automatically determine network, and it was not specified as a parameter"
+    exit 32
+fi
+
+if [ -z $public_network ]; then
+    echo "-p network missing!"
+    echo "Could not automatically determine public network, and it was not specified as a parameter"
+    exit 34
+fi
+
+if [ -z $private_network ]; then
+    echo "-P network missing!"
+    echo "Could not automatically determine private network, and it was not specified as a parameter"
+    exit 36
 fi
 
 if [ -z $region ]; then
@@ -196,9 +287,25 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 60
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
+templatesbucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
+templatespath=/example
+
+if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region $region 2> /dev/null; then
+    echo "$templatesbucket S3 bucket does not exist!"
+    exit 62
+fi
+
+examplesbucket=${AWS_EXAMPLES_BUCKET:-examples-$region-$account}
+examplespath=/$application
+
+if ! aws s3api head-bucket --bucket $examplesbucket --profile $profile --region $region 2> /dev/null; then
+    echo "$examplesbucket S3 bucket does not exist!"
+    exit 68
+fi
+
+if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to delete - $environment-$application Stack does not exist!"
+    echo "$environment-VPC Stack does not exist!"
     exit 70
 fi
 
@@ -248,17 +355,23 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation delete-stack --stack-name $environment-$application \\
-                                --profile $profile --region $region --output table
+aws s3 sync $templatesdir \\
+            s3://$templatesbucket$templatespath \\
+            --exclude '*' --include 'Example-NestedWebServer.json' --include 'Example-NestedWebServer-StackPolicy.json' \\
+            --include 'Example-NestedWebServer-Role.json' \\
+            --include 'Example-NestedWebServer-SecurityGroup.json' \\
+            --include 'Example-NestedWebServer-Instance.json' \\
+            --include 'Example-NestedWebServer-RecordSet.json' \\
+            --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'} 2> /dev/null"
+eval_statement="${statement//\\$'\n'}"
 
 clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Delete the Stack"
+echo "$(printf '%2d' $step). Sync Template and Policy to ($templatesbucket) Bucket"
 echo
 echo "============================================================"
 echo
@@ -266,11 +379,66 @@ echo "Commands:"
 echo
 echo "$statement"
 
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
-                                        --profile $profile --region $region --output text &> /dev/null; then
+next 50
+
+echo
+echo "$run_statement"
+eval "$eval_statement"
+
+next 50
+
+
+((++step))
+if [ $dummy = 1 ]; then
+    # unset download location, which triggers creation of dummy application page within the template
+    unset examplesbucket
+fi
+
+template_parameter="--template-url https://$s3_domain/$templatesbucket$templatespath/Example-NestedWebServer.json"
+stack_policy_parameter="--stack-policy-url https://$s3_domain/$templatesbucket$templatespath/Example-NestedWebServer-StackPolicy.json"
+read -r -d '' statement << EOS
+aws cloudformation create-stack --stack-name $environment-$application \\
+                                $template_parameter \\
+                                $stack_policy_parameter \\
+                                --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
+                                             ParameterKey=TemplatesBucket,ParameterValue=$templatesbucket \\
+                                             ParameterKey=TemplatesPath,ParameterValue=$templatespath \\
+                                             ParameterKey=ApplicationsBucket,ParameterValue=$examplesbucket \\
+                                             ParameterKey=ApplicationName,ParameterValue=$application \\
+                                             ParameterKey=ApplicationDomain,ParameterValue=$application_domain \\
+                                             ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
+                                             ParameterKey=KeyName,ParameterValue=$key \\
+                                             ParameterKey=AdministratorNetwork,ParameterValue=$network \\
+                                             ParameterKey=PublicNetwork,ParameterValue=$public_network \\
+                                             ParameterKey=PrivateNetwork,ParameterValue=$private_network \\
+                                --tags Key=Owner,Value=$owner \\
+                                       Key=Company,Value=$company \\
+                                       Key=System,Value=$system \\
+                                       Key=Environment,Value=$environment \\
+                                       Key=Application,Value=$application \\
+                                --capabilities CAPABILITY_IAM \\
+                                --profile $profile --region $region --output table
+EOS
+run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
+eval_statement="${statement//\\$'\n'}"
+
+clear
+echo
+echo "============================================================"
+echo
+echo "$(printf '%2d' $step). Create the Stack"
+echo
+echo "============================================================"
+echo
+echo "Commands:"
+echo
+echo "$statement"
+
+if aws cloudformation describe-stacks --stack-name $environment-$application \
+                                      --profile $profile --region $region --output text &> /dev/null; then
     echo
     tput rev
-    echo "Already Deleted!"
+    echo "Already Created!"
     tput sgr0
 
     next 50
@@ -309,7 +477,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Monitor Stack deletion"
+echo "$(printf '%2d' $step). Monitor Stack creation"
 echo
 echo "============================================================"
 echo
@@ -319,11 +487,12 @@ echo "$statement"
 echo
 echo "$statement2"
 
-if ! aws cloudformation describe-stacks --stack-name $environment-$application \
-                                        --profile $profile --region $region &> /dev/null; then
+if [ "$(aws cloudformation describe-stacks --stack-name $environment-$application \
+                                           --query 'Stacks[].StackStatus' \
+                                           --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
     echo
     tput rev
-    echo "Already Deleted!"
+    echo "Already Complete!"
     tput sgr0
 
     next 50
@@ -337,8 +506,8 @@ else
         eval "$eval_statement"
 
         attempt=0
-        seconds=$delete_default
-        while ((attempt++ <= delete_attempts)); do
+        seconds=$create_default
+        while ((attempt++ <= create_attempts)); do
             echo
             echo "$run_statement2"
             eval "$eval_statement2"
@@ -375,6 +544,40 @@ if [ $verbose = 1 ]; then
     echo "============================================================"
     echo
     echo "$(printf '%2d' $step). List Resulting Stacks"
+    echo
+    echo "============================================================"
+    echo
+    echo "Commands:"
+    echo
+    echo "$statement"
+
+    run 50
+
+    if [ $choice = y ]; then
+        echo
+        echo "$run_statement"
+        eval "$eval_statement"
+
+        next
+    fi
+fi
+
+
+((++step))
+read -r -d '' statement << EOS
+aws cloudformation describe-stack-resources --stack-name $environment-$application \\
+                                            --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
+                                            --profile $profile --region $region --output table
+EOS
+run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
+eval_statement="${statement//\\$'\n'} 2> /dev/null"
+
+if [ $verbose = 1 ]; then
+    clear
+    echo
+    echo "============================================================"
+    echo
+    echo "$(printf '%2d' $step). List Resulting Stack Resources"
     echo
     echo "============================================================"
     echo
