renamed nestedwebservers to nestedlinuxwebservers; switched to new network address env vars

diff --git a/example/bin/example-update-nestedlinuxwebservers-stack b/example/bin/example-update-nestedlinuxwebservers-stack
--- a/example/bin/example-update-nestedlinuxwebservers-stack
+++ b/example/bin/example-update-nestedlinuxwebservers-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script updates the Example NestedWebServers Stack in an Environment Account.
+# This script updates the Example NestedLinuxWebServers Stack in an Environment Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -30,22 +30,22 @@ company=${COMPANY_NAME:-Travel}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
 environment_size=${ENVIRONMENT_SIZE:-micro}
-application=${APPLICATION_NAME:-NestedWebServers}
-application_domain=${APPLICATION_DOMAIN:-nmws}
+application=${APPLICATION_NAME:-NestedLinuxWebServers}
+application_domain=${APPLICATION_DOMAIN:-lws}
 application_version=${APPLICATION_VERSION:-2.0.0}
 key=${AWS_KEY_NAME:-example}
-network=${ADMINISTRATOR_NETWORK:-0.0.0.0/0}
-network1=${ADMINISTRATOR_NETWORK1:-}
-network2=${ADMINISTRATOR_NETWORK2:-}
-network3=${ADMINISTRATOR_NETWORK3:-}
-public_network=${PUBLIC_NETWORK:-0.0.0.0/0}
-public_network1=${PUBLIC_NETWORK1:-}
-public_network2=${PUBLIC_NETWORK2:-}
-public_network3=${PUBLIC_NETWORK3:-}
-private_network=${PRIVATE_NETWORK:-10.0.0.0/16}
-private_network1=${PRIVATE_NETWORK1:-}
-private_network2=${PRIVATE_NETWORK2:-}
-private_network3=${PRIVATE_NETWORK3:-}
+private_user_network=${PRIVATE_USER_NETWORK:-10.0.0.0/16}
+private_user_network1=${PRIVATE_USER_NETWORK1:-}
+private_user_network2=${PRIVATE_USER_NETWORK2:-}
+private_administrator_network=${PRIVATE_ADMINISTRATOR_NETWORK:-10.0.0.0/16}
+private_administrator_network1=${PRIVATE_ADMINISTRATOR_NETWORK1:-}
+private_administrator_network2=${PRIVATE_ADMINISTRATOR_NETWORK2:-}
+public_user_network=${PUBLIC_USER_NETWORK:-0.0.0.0/0}
+public_user_network1=${PUBLIC_USER_NETWORK1:-}
+public_user_network2=${PUBLIC_USER_NETWORK2:-}
+public_administrator_network=${PUBLIC_ADMINISTRATOR_NETWORK:-0.0.0.0/0}
+public_administrator_network1=${PUBLIC_ADMINISTRATOR_NETWORK1:-}
+public_administrator_network2=${PUBLIC_ADMINISTRATOR_NETWORK2:-}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -58,8 +58,9 @@ usage () {
     echo "                  [-O owner] [-C company ] [-S system]"
     echo "                  [-E environment] [-Z size]"
     echo "                  [-A application ] [-D domain] [-V version]"
-    echo "                  [-k key] [-n network ]"
+    echo "                  [-k key]"
     echo "                  [-p network] [-P network ]"
+    echo "                  [-n network] [-N network ]"
     echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
@@ -76,9 +77,10 @@ usage () {
     echo "  -D domain       Application Domain (default: $application_domain)"
     echo "  -V version      Application Version (default: $application_version)"
     echo "  -k key          Key (default: $key)"
-    echo "  -n network      Administrator Network (default: $network)"
-    echo "  -p network      Public Network (default: $public_network)"
-    echo "  -P network      Private Network (default: $private_network)"
+    echo "  -p network      Public User Network (default: $public_user_network)"
+    echo "  -P network      Public Administrator Network (default: $public_administrator_network)"
+    echo "  -n network      Private User Network (default: $private_user_network)"
+    echo "  -N network      Private Administrator Network (default: $private_administrator_network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -163,9 +165,9 @@ next() {
 
 
 #  3. Parse command line options
-#     - Note, using options 1-9 as hidden options to set additional network ranges
+#     - Note, using options 1-8 as hidden options to set additional network ranges
 
-while getopts IsfvodO:C:S:E:Z:A:D:V:k:n:1:2:3:p:4:5:6:P:7:8:9:r:a:u:? arg; do
+while getopts IsfvodO:C:S:E:Z:A:D:V:k:p:1:2:P:3:4:n:5:6:N:7:8:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -232,36 +234,43 @@ if [ -z $environment ]; then
 else
     case $environment in
       Production)
+        instance_os=RHEL
         use_log_monitoring=true
         use_schedule=false
         normal_schedule="0 11 * * 1-5" # 11:00 UTC = 3:00 AM PST = 6:00 AM EST, Mon-Fri
         reduced_schedule="0 4 * * *";; # 4:00 UTC = 8:00 PM PST = 11:00 PM EST, Mon-Fri
       Staging)
+        instance_os=AMZN
         use_log_monitoring=true
         use_schedule=true
         normal_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         reduced_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       Testing)
+        instance_os=AMZN
         use_log_monitoring=false
         use_schedule=true
         normal_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         reduced_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       Development)
+        instance_os=AMZN
         use_log_monitoring=false
         use_schedule=true
         normal_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         reduced_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       Core)
+        instance_os=AMZN
         use_log_monitoring=true
         use_schedule=true
         normal_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         reduced_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       Build)
+        instance_os=AMZN
         use_log_monitoring=false
         use_schedule=true
         normal_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
         reduced_schedule="0 2 * * *";; # 2:00 UTC = 6:00 PM PST = 9:00 PM EST, Mon-Fri
       *)
+        instance_os=AMZN
         use_log_monitoring=false
         use_schedule=true
         normal_schedule="0 13 * * 1-5" # 13:00 UTC = 5:00 AM PST = 8:00 AM EST, Mon-Fri
@@ -299,22 +308,28 @@ if [ -z $key ]; then
     exit 30
 fi
 
-if [ -z $network ]; then
-    echo "-n network missing!"
-    echo "Could not automatically determine network, and it was not specified as a parameter"
-    exit 32
-fi
-
-if [ -z $public_network ]; then
+if [ -z $public_user_network ]; then
     echo "-p network missing!"
-    echo "Could not automatically determine public network, and it was not specified as a parameter"
-    exit 34
+    echo "Could not automatically determine public user network, and it was not specified as a parameter"
+    exit 40
 fi
 
-if [ -z $private_network ]; then
+if [ -z $public_administrator_network ]; then
     echo "-P network missing!"
-    echo "Could not automatically determine private network, and it was not specified as a parameter"
-    exit 36
+    echo "Could not automatically determine public administrator network, and it was not specified as a parameter"
+    exit 42
+fi
+
+if [ -z $private_user_network ]; then
+    echo "-n network missing!"
+    echo "Could not automatically determine private user network, and it was not specified as a parameter"
+    exit 44
+fi
+
+if [ -z $private_administrator_network ]; then
+    echo "-N network missing!"
+    echo "Could not automatically determine private administrator network, and it was not specified as a parameter"
+    exit 46
 fi
 
 if [ -z $region ]; then
@@ -325,7 +340,7 @@ else
     case $region in
       us-east-1)
         s3_domain=s3.amazonaws.com;;
-      us-east-2|us-west-1|us-west-2|ca-central-1|sa-east-1|eu-west-1|eu-west-2|eu-central-1|ap-northeast-1|ap-northeast-2|ap-south-1|ap-southeast-1|ap-southeast-2)
+      us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
         s3_domain=s3-$region.amazonaws.com;;
     *)
         echo "-r $region invalid: Please specify a valid region"
@@ -354,7 +369,7 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
 fi
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-templates_folder=example
+template_folder=example
 
 if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
     echo "$templates_bucket S3 bucket does not exist!"
@@ -362,7 +377,8 @@ if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --regio
 fi
 
 examples_bucket=${AWS_EXAMPLES_BUCKET:-examples-$region-$account}
-examples_folder=$application
+example_folder=LinuxWebServer
+example_object=LinuxWebServer-$application_version.tgz
 
 if ! aws s3api head-bucket --bucket $examples_bucket --profile $profile --region $region 2> /dev/null; then
     echo "$examples_bucket S3 bucket does not exist!"
@@ -422,14 +438,14 @@ fi
 ((++step))
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
-            s3://$templates_bucket/$templates_folder \\
-            --exclude '*' --include 'Example-NestedWebServers.json' --include 'Example-NestedWebServers-StackPolicy.json' \\
-            --include 'Example-NestedWebServers-Role.json' \\
-            --include 'Example-NestedWebServers-Logs.json' \\
-            --include 'Example-NestedWebServers-SecurityGroups.json' \\
-            --include 'Example-NestedWebServers-LoadBalancer.json' \\
-            --include 'Example-NestedWebServers-Instances.json' \\
-            --include 'Example-NestedWebServers-DomainNames.json' \\
+            s3://$templates_bucket/$template_folder \\
+            --exclude '*' --include 'Example-NestedLinuxWebServers.json' --include 'Example-NestedLinuxWebServers-StackPolicy.json' \\
+            --include 'Example-NestedLinuxWebServers-Role.json' \\
+            --include 'Example-NestedLinuxWebServers-Logs.json' \\
+            --include 'Example-NestedLinuxWebServers-SecurityGroups.json' \\
+            --include 'Example-NestedLinuxWebServers-LoadBalancer.json' \\
+            --include 'Example-NestedLinuxWebServers-Instances.json' \\
+            --include 'Example-NestedLinuxWebServers-DomainNames.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
@@ -462,8 +478,8 @@ if [ $dummy = 1 ]; then
     unset examples_bucket
 fi
 
-template_parameter="--template-url https://$s3_domain/$templates_bucket/$templates_folder/Example-NestedWebServers.json"
-stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$templates_folder/Example-NestedWebServers-StackPolicy.json"
+template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Example-NestedLinuxWebServers.json"
+stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Example-NestedLinuxWebServers-StackPolicy.json"
 if [ $override = 1 ]; then
     stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
 fi
@@ -472,13 +488,19 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
                                 --parameters ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
+                                             ParameterKey=CustomIdentifierFunctionsStackName,ParameterValue=CustomIdentifierFunctions \\
+                                             ParameterKey=StandardAMIFunctionsStackName,ParameterValue=StandardAMIFunctions \\
+                                             ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
                                              ParameterKey=TemplatesBucket,ParameterValue=$templates_bucket \\
-                                             ParameterKey=TemplatesFolder,ParameterValue=$templates_folder \\
+                                             ParameterKey=TemplateFolder,ParameterValue=$template_folder \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
                                              ParameterKey=EnvironmentSize,ParameterValue=$environment_size \\
+                                             ParameterKey=InstanceOS,ParameterValue=$instance_os \\
                                              ParameterKey=ApplicationsBucket,ParameterValue=$examples_bucket \\
+                                             ParameterKey=ApplicationFolder,ParameterValue=$example_folder \\
+                                             ParameterKey=ApplicationObject,ParameterValue=$example_object \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
                                              ParameterKey=ApplicationDomain,ParameterValue=$application_domain \\
                                              ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
@@ -486,18 +508,18 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                              ParameterKey=UseSchedule,ParameterValue=$use_schedule \\
                                              ParameterKey=NormalSchedule,ParameterValue="$normal_schedule" \\
                                              ParameterKey=ReducedSchedule,ParameterValue="$reduced_schedule" \\
-                                             ParameterKey=AdministratorNetwork,ParameterValue=$network \\
-                                             ParameterKey=AdministratorNetwork1,ParameterValue=$network1 \\
-                                             ParameterKey=AdministratorNetwork2,ParameterValue=$network2 \\
-                                             ParameterKey=AdministratorNetwork3,ParameterValue=$network3 \\
-                                             ParameterKey=PublicNetwork,ParameterValue=$public_network \\
-                                             ParameterKey=PublicNetwork1,ParameterValue=$public_network1 \\
-                                             ParameterKey=PublicNetwork2,ParameterValue=$public_network2 \\
-                                             ParameterKey=PublicNetwork3,ParameterValue=$public_network3 \\
-                                             ParameterKey=PrivateNetwork,ParameterValue=$private_network \\
-                                             ParameterKey=PrivateNetwork1,ParameterValue=$private_network1 \\
-                                             ParameterKey=PrivateNetwork2,ParameterValue=$private_network2 \\
-                                             ParameterKey=PrivateNetwork3,ParameterValue=$private_network3 \\
+                                             ParameterKey=PublicUserNetwork,ParameterValue=$public_user_network \\
+                                             ParameterKey=PublicUserNetwork1,ParameterValue=$public_user_network1 \\
+                                             ParameterKey=PublicUserNetwork2,ParameterValue=$public_user_network2 \\
+                                             ParameterKey=PublicAdministratorNetwork,ParameterValue=$public_administrator_network \\
+                                             ParameterKey=PublicAdministratorNetwork1,ParameterValue=$public_administrator_network1 \\
+                                             ParameterKey=PublicAdministratorNetwork2,ParameterValue=$public_administrator_network2 \\
+                                             ParameterKey=PrivateUserNetwork,ParameterValue=$private_user_network \\
+                                             ParameterKey=PrivateUserNetwork1,ParameterValue=$private_user_network1 \\
+                                             ParameterKey=PrivateUserNetwork2,ParameterValue=$private_user_network2 \\
+                                             ParameterKey=PrivateAdministratorNetwork,ParameterValue=$private_administrator_network \\
+                                             ParameterKey=PrivateAdministratorNetwork1,ParameterValue=$private_administrator_network1 \\
+                                             ParameterKey=PrivateAdministratorNetwork2,ParameterValue=$private_administrator_network2 \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
